var namespace_aspose_1_1_pdf_1_1_engine_1_1_i_o_1_1_convert_strategies =
[
    [ "ConversionFontData", "class_aspose_1_1_pdf_1_1_engine_1_1_i_o_1_1_convert_strategies_1_1_conversion_font_data.html", "class_aspose_1_1_pdf_1_1_engine_1_1_i_o_1_1_convert_strategies_1_1_conversion_font_data" ],
    [ "FontErrorInfo", "class_aspose_1_1_pdf_1_1_engine_1_1_i_o_1_1_convert_strategies_1_1_font_error_info.html", "class_aspose_1_1_pdf_1_1_engine_1_1_i_o_1_1_convert_strategies_1_1_font_error_info" ],
    [ "FontSymbol", "class_aspose_1_1_pdf_1_1_engine_1_1_i_o_1_1_convert_strategies_1_1_font_symbol.html", "class_aspose_1_1_pdf_1_1_engine_1_1_i_o_1_1_convert_strategies_1_1_font_symbol" ],
    [ "IConversionFontDataUpdater", "class_aspose_1_1_pdf_1_1_engine_1_1_i_o_1_1_convert_strategies_1_1_i_conversion_font_data_updater.html", "class_aspose_1_1_pdf_1_1_engine_1_1_i_o_1_1_convert_strategies_1_1_i_conversion_font_data_updater" ],
    [ "IConversionInfo", "class_aspose_1_1_pdf_1_1_engine_1_1_i_o_1_1_convert_strategies_1_1_i_conversion_info.html", "class_aspose_1_1_pdf_1_1_engine_1_1_i_o_1_1_convert_strategies_1_1_i_conversion_info" ]
];