var namespace_aspose_1_1_pub =
[
    [ "Utils", "namespace_aspose_1_1_pub_1_1_utils.html", "namespace_aspose_1_1_pub_1_1_utils" ],
    [ "AssemblyConstants", "class_aspose_1_1_pub_1_1_assembly_constants.html", null ],
    [ "BaseStyle", "class_aspose_1_1_pub_1_1_base_style.html", "class_aspose_1_1_pub_1_1_base_style" ],
    [ "BuildVersionInfo", "class_aspose_1_1_pub_1_1_build_version_info.html", null ],
    [ "DocSummaryInfo", "class_aspose_1_1_pub_1_1_doc_summary_info.html", "class_aspose_1_1_pub_1_1_doc_summary_info" ],
    [ "Document", "class_aspose_1_1_pub_1_1_document.html", "class_aspose_1_1_pub_1_1_document" ],
    [ "Fill", "class_aspose_1_1_pub_1_1_fill.html", "class_aspose_1_1_pub_1_1_fill" ],
    [ "GradientFill", "class_aspose_1_1_pub_1_1_gradient_fill.html", "class_aspose_1_1_pub_1_1_gradient_fill" ],
    [ "ImageFill", "class_aspose_1_1_pub_1_1_image_fill.html", "class_aspose_1_1_pub_1_1_image_fill" ],
    [ "IPdfConverter", "class_aspose_1_1_pub_1_1_i_pdf_converter.html", "class_aspose_1_1_pub_1_1_i_pdf_converter" ],
    [ "IPubParser", "class_aspose_1_1_pub_1_1_i_pub_parser.html", "class_aspose_1_1_pub_1_1_i_pub_parser" ],
    [ "License", "class_aspose_1_1_pub_1_1_license.html", "class_aspose_1_1_pub_1_1_license" ],
    [ "MetaInfo", "class_aspose_1_1_pub_1_1_meta_info.html", "class_aspose_1_1_pub_1_1_meta_info" ],
    [ "ParagraphStyle", "class_aspose_1_1_pub_1_1_paragraph_style.html", "class_aspose_1_1_pub_1_1_paragraph_style" ],
    [ "PatternFill", "class_aspose_1_1_pub_1_1_pattern_fill.html", "class_aspose_1_1_pub_1_1_pattern_fill" ],
    [ "PubEmbeddedFont", "class_aspose_1_1_pub_1_1_pub_embedded_font.html", "class_aspose_1_1_pub_1_1_pub_embedded_font" ],
    [ "PubFactory", "class_aspose_1_1_pub_1_1_pub_factory.html", "class_aspose_1_1_pub_1_1_pub_factory" ],
    [ "SolidFill", "class_aspose_1_1_pub_1_1_solid_fill.html", "class_aspose_1_1_pub_1_1_solid_fill" ],
    [ "StopPoint", "class_aspose_1_1_pub_1_1_stop_point.html", "class_aspose_1_1_pub_1_1_stop_point" ],
    [ "SummaryInfo", "class_aspose_1_1_pub_1_1_summary_info.html", "class_aspose_1_1_pub_1_1_summary_info" ],
    [ "TextGroup", "class_aspose_1_1_pub_1_1_text_group.html", "class_aspose_1_1_pub_1_1_text_group" ],
    [ "TextParagraph", "class_aspose_1_1_pub_1_1_text_paragraph.html", "class_aspose_1_1_pub_1_1_text_paragraph" ],
    [ "TextStyle", "class_aspose_1_1_pub_1_1_text_style.html", "class_aspose_1_1_pub_1_1_text_style" ]
];