var class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_job_features =
[
    [ "JobDuplexAllDocumentsContiguously", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_job_features_1_1_job_duplex_all_documents_contiguously.html", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_job_features_1_1_job_duplex_all_documents_contiguously" ],
    [ "JobInputBin", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_job_features_1_1_job_input_bin.html", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_job_features_1_1_job_input_bin" ]
];