var class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_page_features =
[
    [ "PageInputBin", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_page_features_1_1_page_input_bin.html", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_page_features_1_1_page_input_bin" ]
];