var class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_scored_properties =
[
    [ "DuplexMode", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_scored_properties_1_1_duplex_mode.html", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_scored_properties_1_1_duplex_mode" ]
];