var class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_parameter_inits =
[
    [ "JobCopiesAllDocuments", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_parameter_inits_1_1_job_copies_all_documents.html", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_parameter_inits_1_1_job_copies_all_documents" ]
];