var namespace_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata =
[
    [ "DocumentFeature", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_document_feature.html", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_document_feature" ],
    [ "DocumentFeatures", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_document_features.html", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_document_features" ],
    [ "DocumentPrintTicket", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_document_print_ticket.html", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_document_print_ticket" ],
    [ "Feature", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_feature.html", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_feature" ],
    [ "Features", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_features.html", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_features" ],
    [ "IFeatureItem", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_i_feature_item.html", null ],
    [ "IOptionItem", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_i_option_item.html", null ],
    [ "IPrintTicketItem", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_i_print_ticket_item.html", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_i_print_ticket_item" ],
    [ "IPropertyItem", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_i_property_item.html", null ],
    [ "IScoredPropertyItem", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_i_scored_property_item.html", null ],
    [ "JobFeature", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_job_feature.html", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_job_feature" ],
    [ "JobFeatures", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_job_features.html", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_job_features" ],
    [ "JobPrintTicket", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_job_print_ticket.html", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_job_print_ticket" ],
    [ "NamespaceDoc", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_namespace_doc.html", null ],
    [ "Option", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_option.html", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_option" ],
    [ "Options", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_options.html", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_options" ],
    [ "PageFeature", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_page_feature.html", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_page_feature" ],
    [ "PageFeatures", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_page_features.html", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_page_features" ],
    [ "PagePrintTicket", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_page_print_ticket.html", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_page_print_ticket" ],
    [ "ParameterInit", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_parameter_init.html", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_parameter_init" ],
    [ "ParameterInits", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_parameter_inits.html", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_parameter_inits" ],
    [ "PrintTicket", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_print_ticket.html", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_print_ticket" ],
    [ "Properties", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_properties.html", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_properties" ],
    [ "Property", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_property.html", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_property" ],
    [ "ScoredProperties", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_scored_properties.html", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_scored_properties" ],
    [ "ScoredProperty", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_scored_property.html", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_scored_property" ],
    [ "Value", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_value.html", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_value" ],
    [ "Values", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_values.html", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_values" ],
    [ "ValueType", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_value_type.html", "class_aspose_1_1_page_1_1_x_p_s_1_1_xps_metadata_1_1_value_type" ]
];