var namespace_aspose_1_1_email_1_1_clients =
[
    [ "Activity", "namespace_aspose_1_1_email_1_1_clients_1_1_activity.html", "namespace_aspose_1_1_email_1_1_clients_1_1_activity" ],
    [ "Exchange", "namespace_aspose_1_1_email_1_1_clients_1_1_exchange.html", "namespace_aspose_1_1_email_1_1_clients_1_1_exchange" ],
    [ "Google", "namespace_aspose_1_1_email_1_1_clients_1_1_google.html", "namespace_aspose_1_1_email_1_1_clients_1_1_google" ],
    [ "Graph", "namespace_aspose_1_1_email_1_1_clients_1_1_graph.html", "namespace_aspose_1_1_email_1_1_clients_1_1_graph" ],
    [ "Imap", "namespace_aspose_1_1_email_1_1_clients_1_1_imap.html", "namespace_aspose_1_1_email_1_1_clients_1_1_imap" ],
    [ "Pop3", "namespace_aspose_1_1_email_1_1_clients_1_1_pop3.html", "namespace_aspose_1_1_email_1_1_clients_1_1_pop3" ],
    [ "Smtp", "namespace_aspose_1_1_email_1_1_clients_1_1_smtp.html", "namespace_aspose_1_1_email_1_1_clients_1_1_smtp" ],
    [ "AsyncCommandResultEventArgs", "class_aspose_1_1_email_1_1_clients_1_1_async_command_result_event_args.html", "class_aspose_1_1_email_1_1_clients_1_1_async_command_result_event_args" ],
    [ "CommandStatus", "class_aspose_1_1_email_1_1_clients_1_1_command_status.html", "class_aspose_1_1_email_1_1_clients_1_1_command_status" ],
    [ "Details_NetworkException", "class_aspose_1_1_email_1_1_clients_1_1_details___network_exception.html", "class_aspose_1_1_email_1_1_clients_1_1_details___network_exception" ],
    [ "EmailClient", "class_aspose_1_1_email_1_1_clients_1_1_email_client.html", "class_aspose_1_1_email_1_1_clients_1_1_email_client" ],
    [ "HttpProxy", "class_aspose_1_1_email_1_1_clients_1_1_http_proxy.html", "class_aspose_1_1_email_1_1_clients_1_1_http_proxy" ],
    [ "IAsyncResultExt", "class_aspose_1_1_email_1_1_clients_1_1_i_async_result_ext.html", "class_aspose_1_1_email_1_1_clients_1_1_i_async_result_ext" ],
    [ "ICommand", "class_aspose_1_1_email_1_1_clients_1_1_i_command.html", "class_aspose_1_1_email_1_1_clients_1_1_i_command" ],
    [ "IConnection", "class_aspose_1_1_email_1_1_clients_1_1_i_connection.html", "class_aspose_1_1_email_1_1_clients_1_1_i_connection" ],
    [ "IMultipleServicesTokenProvider", "class_aspose_1_1_email_1_1_clients_1_1_i_multiple_services_token_provider.html", "class_aspose_1_1_email_1_1_clients_1_1_i_multiple_services_token_provider" ],
    [ "ITokenProvider", "class_aspose_1_1_email_1_1_clients_1_1_i_token_provider.html", "class_aspose_1_1_email_1_1_clients_1_1_i_token_provider" ],
    [ "MessageInfoBase", "class_aspose_1_1_email_1_1_clients_1_1_message_info_base.html", "class_aspose_1_1_email_1_1_clients_1_1_message_info_base" ],
    [ "NameValuePair", "class_aspose_1_1_email_1_1_clients_1_1_name_value_pair.html", "class_aspose_1_1_email_1_1_clients_1_1_name_value_pair" ],
    [ "OAuthNetworkCredential", "class_aspose_1_1_email_1_1_clients_1_1_o_auth_network_credential.html", "class_aspose_1_1_email_1_1_clients_1_1_o_auth_network_credential" ],
    [ "OAuthToken", "class_aspose_1_1_email_1_1_clients_1_1_o_auth_token.html", "class_aspose_1_1_email_1_1_clients_1_1_o_auth_token" ],
    [ "PageInfo", "class_aspose_1_1_email_1_1_clients_1_1_page_info.html", "class_aspose_1_1_email_1_1_clients_1_1_page_info" ],
    [ "PipeliningStatus", "class_aspose_1_1_email_1_1_clients_1_1_pipelining_status.html", "class_aspose_1_1_email_1_1_clients_1_1_pipelining_status" ],
    [ "Proxy", "class_aspose_1_1_email_1_1_clients_1_1_proxy.html", "class_aspose_1_1_email_1_1_clients_1_1_proxy" ],
    [ "SecurityOptionsExtensions", "class_aspose_1_1_email_1_1_clients_1_1_security_options_extensions.html", "class_aspose_1_1_email_1_1_clients_1_1_security_options_extensions" ],
    [ "SocksProxy", "class_aspose_1_1_email_1_1_clients_1_1_socks_proxy.html", "class_aspose_1_1_email_1_1_clients_1_1_socks_proxy" ],
    [ "TokenProvider", "class_aspose_1_1_email_1_1_clients_1_1_token_provider.html", "class_aspose_1_1_email_1_1_clients_1_1_token_provider" ]
];