var namespace_aspose_1_1_email_1_1_clients_1_1_imap =
[
    [ "AppendMessagesResult", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_append_messages_result.html", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_append_messages_result" ],
    [ "BackupSettings", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_backup_settings.html", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_backup_settings" ],
    [ "BaseSearchConditions", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_base_search_conditions.html", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_base_search_conditions" ],
    [ "ESearchOptions", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_e_search_options.html", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_e_search_options" ],
    [ "IImapMonitoringState", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_i_imap_monitoring_state.html", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_i_imap_monitoring_state" ],
    [ "ImapClient", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_imap_client.html", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_imap_client" ],
    [ "ImapFolderInfo", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_imap_folder_info.html", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_imap_folder_info" ],
    [ "ImapFolderInfoCollection", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_imap_folder_info_collection.html", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_imap_folder_info_collection" ],
    [ "ImapFolderInfoCollectionBase", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_imap_folder_info_collection_base.html", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_imap_folder_info_collection_base" ],
    [ "ImapIdentificationInfo", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_imap_identification_info.html", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_imap_identification_info" ],
    [ "ImapMailboxInfo", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_imap_mailbox_info.html", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_imap_mailbox_info" ],
    [ "ImapMessageFlags", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_imap_message_flags.html", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_imap_message_flags" ],
    [ "ImapMessageInfo", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_imap_message_info.html", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_imap_message_info" ],
    [ "ImapMessageInfoCollection", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_imap_message_info_collection.html", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_imap_message_info_collection" ],
    [ "ImapMessageInfoCollectionBase", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_imap_message_info_collection_base.html", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_imap_message_info_collection_base" ],
    [ "ImapMonitoringErrorEventArgs", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_imap_monitoring_error_event_args.html", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_imap_monitoring_error_event_args" ],
    [ "ImapMonitoringEventArgs", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_imap_monitoring_event_args.html", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_imap_monitoring_event_args" ],
    [ "ImapNamespace", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_imap_namespace.html", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_imap_namespace" ],
    [ "ImapPageInfo", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_imap_page_info.html", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_imap_page_info" ],
    [ "ImapQueryBuilder", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_imap_query_builder.html", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_imap_query_builder" ],
    [ "ImapQuota", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_imap_quota.html", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_imap_quota" ],
    [ "ImapQuotaRoot", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_imap_quota_root.html", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_imap_quota_root" ],
    [ "MessageThreadResult", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_message_thread_result.html", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_message_thread_result" ],
    [ "ModificationSequenceField", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_modification_sequence_field.html", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_modification_sequence_field" ],
    [ "PageSettings", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_page_settings.html", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_page_settings" ],
    [ "PageSettingsAsync", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_page_settings_async.html", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_page_settings_async" ],
    [ "RangeSeqSet", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_range_seq_set.html", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_range_seq_set" ],
    [ "RestoreSettings", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_restore_settings.html", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_restore_settings" ],
    [ "RestoreSettingsAsync", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_restore_settings_async.html", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_restore_settings_async" ],
    [ "SequenceSetBaseValue", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_sequence_set_base_value.html", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_sequence_set_base_value" ],
    [ "SequenceSetField", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_sequence_set_field.html", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_sequence_set_field" ],
    [ "SimpleSeqSet", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_simple_seq_set.html", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_simple_seq_set" ],
    [ "SortConditions", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_sort_conditions.html", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_sort_conditions" ],
    [ "ThreadSearchConditions", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_thread_search_conditions.html", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_thread_search_conditions" ],
    [ "XGMThreadSearchConditions", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_x_g_m_thread_search_conditions.html", "class_aspose_1_1_email_1_1_clients_1_1_imap_1_1_x_g_m_thread_search_conditions" ]
];