var namespace_system_1_1_net =
[
    [ "Cache", "namespace_system_1_1_net_1_1_cache.html", "namespace_system_1_1_net_1_1_cache" ],
    [ "Http", "namespace_system_1_1_net_1_1_http.html", "namespace_system_1_1_net_1_1_http" ],
    [ "NetworkInformation", "namespace_system_1_1_net_1_1_network_information.html", "namespace_system_1_1_net_1_1_network_information" ],
    [ "Security", "namespace_system_1_1_net_1_1_security.html", "namespace_system_1_1_net_1_1_security" ],
    [ "Sockets", "namespace_system_1_1_net_1_1_sockets.html", "namespace_system_1_1_net_1_1_sockets" ],
    [ "Cookie", "class_system_1_1_net_1_1_cookie.html", "class_system_1_1_net_1_1_cookie" ],
    [ "CookieCollection", "class_system_1_1_net_1_1_cookie_collection.html", "class_system_1_1_net_1_1_cookie_collection" ],
    [ "CookieComparer", "class_system_1_1_net_1_1_cookie_comparer.html", "class_system_1_1_net_1_1_cookie_comparer" ],
    [ "CookieContainer", "class_system_1_1_net_1_1_cookie_container.html", "class_system_1_1_net_1_1_cookie_container" ],
    [ "CookieParser", "class_system_1_1_net_1_1_cookie_parser.html", "class_system_1_1_net_1_1_cookie_parser" ],
    [ "CredentialCache", "class_system_1_1_net_1_1_credential_cache.html", "class_system_1_1_net_1_1_credential_cache" ],
    [ "Details_CookieException", "class_system_1_1_net_1_1_details___cookie_exception.html", "class_system_1_1_net_1_1_details___cookie_exception" ],
    [ "Details_WebException", "class_system_1_1_net_1_1_details___web_exception.html", "class_system_1_1_net_1_1_details___web_exception" ],
    [ "Dns", "class_system_1_1_net_1_1_dns.html", "class_system_1_1_net_1_1_dns" ],
    [ "DnsEndPoint", "class_system_1_1_net_1_1_dns_end_point.html", "class_system_1_1_net_1_1_dns_end_point" ],
    [ "EndPoint", "class_system_1_1_net_1_1_end_point.html", "class_system_1_1_net_1_1_end_point" ],
    [ "FileWebRequest", "class_system_1_1_net_1_1_file_web_request.html", "class_system_1_1_net_1_1_file_web_request" ],
    [ "FileWebResponse", "class_system_1_1_net_1_1_file_web_response.html", "class_system_1_1_net_1_1_file_web_response" ],
    [ "FtpWebRequest", "class_system_1_1_net_1_1_ftp_web_request.html", null ],
    [ "FtpWebResponse", "class_system_1_1_net_1_1_ftp_web_response.html", "class_system_1_1_net_1_1_ftp_web_response" ],
    [ "HeaderVariantInfo", "class_system_1_1_net_1_1_header_variant_info.html", "class_system_1_1_net_1_1_header_variant_info" ],
    [ "HttpKnownHeaderNames", "class_system_1_1_net_1_1_http_known_header_names.html", "class_system_1_1_net_1_1_http_known_header_names" ],
    [ "HttpRequestHeaderExtensions", "class_system_1_1_net_1_1_http_request_header_extensions.html", "class_system_1_1_net_1_1_http_request_header_extensions" ],
    [ "HttpResponseHeaderExtensions", "class_system_1_1_net_1_1_http_response_header_extensions.html", "class_system_1_1_net_1_1_http_response_header_extensions" ],
    [ "HttpStatusDescription", "class_system_1_1_net_1_1_http_status_description.html", "class_system_1_1_net_1_1_http_status_description" ],
    [ "HttpVersion", "class_system_1_1_net_1_1_http_version.html", "class_system_1_1_net_1_1_http_version" ],
    [ "HttpWebRequest", "class_system_1_1_net_1_1_http_web_request.html", "class_system_1_1_net_1_1_http_web_request" ],
    [ "HttpWebResponse", "class_system_1_1_net_1_1_http_web_response.html", "class_system_1_1_net_1_1_http_web_response" ],
    [ "ICredentials", "class_system_1_1_net_1_1_i_credentials.html", "class_system_1_1_net_1_1_i_credentials" ],
    [ "ICredentialsByHost", "class_system_1_1_net_1_1_i_credentials_by_host.html", "class_system_1_1_net_1_1_i_credentials_by_host" ],
    [ "IPAddress", "class_system_1_1_net_1_1_i_p_address.html", "class_system_1_1_net_1_1_i_p_address" ],
    [ "IPEndPoint", "class_system_1_1_net_1_1_i_p_end_point.html", "class_system_1_1_net_1_1_i_p_end_point" ],
    [ "IPHostEntry", "class_system_1_1_net_1_1_i_p_host_entry.html", "class_system_1_1_net_1_1_i_p_host_entry" ],
    [ "IWebProxy", "class_system_1_1_net_1_1_i_web_proxy.html", "class_system_1_1_net_1_1_i_web_proxy" ],
    [ "IWebRequestCreate", "class_system_1_1_net_1_1_i_web_request_create.html", "class_system_1_1_net_1_1_i_web_request_create" ],
    [ "NetworkCredential", "class_system_1_1_net_1_1_network_credential.html", "class_system_1_1_net_1_1_network_credential" ],
    [ "PathList", "class_system_1_1_net_1_1_path_list.html", "class_system_1_1_net_1_1_path_list" ],
    [ "ServicePoint", "class_system_1_1_net_1_1_service_point.html", "class_system_1_1_net_1_1_service_point" ],
    [ "ServicePointManager", "class_system_1_1_net_1_1_service_point_manager.html", "class_system_1_1_net_1_1_service_point_manager" ],
    [ "SocketAddress", "class_system_1_1_net_1_1_socket_address.html", "class_system_1_1_net_1_1_socket_address" ],
    [ "UriScheme", "class_system_1_1_net_1_1_uri_scheme.html", "class_system_1_1_net_1_1_uri_scheme" ],
    [ "WebClient", "class_system_1_1_net_1_1_web_client.html", "class_system_1_1_net_1_1_web_client" ],
    [ "WebHeaderCollection", "class_system_1_1_net_1_1_web_header_collection.html", "class_system_1_1_net_1_1_web_header_collection" ],
    [ "WebProxy", "class_system_1_1_net_1_1_web_proxy.html", "class_system_1_1_net_1_1_web_proxy" ],
    [ "WebRequest", "class_system_1_1_net_1_1_web_request.html", "class_system_1_1_net_1_1_web_request" ],
    [ "WebRequestMethods", "class_system_1_1_net_1_1_web_request_methods.html", [
      [ "File", "class_system_1_1_net_1_1_web_request_methods_1_1_file.html", "class_system_1_1_net_1_1_web_request_methods_1_1_file" ],
      [ "Ftp", "class_system_1_1_net_1_1_web_request_methods_1_1_ftp.html", "class_system_1_1_net_1_1_web_request_methods_1_1_ftp" ],
      [ "Http", "class_system_1_1_net_1_1_web_request_methods_1_1_http.html", "class_system_1_1_net_1_1_web_request_methods_1_1_http" ]
    ] ],
    [ "WebResponse", "class_system_1_1_net_1_1_web_response.html", "class_system_1_1_net_1_1_web_response" ]
];