var annotated_dup =
[
    [ "asposebarcode", "namespaceasposebarcode.html", [
      [ "Assist", "namespaceasposebarcode_1_1_assist.html", [
        [ "BaseJavaClass", "classasposebarcode_1_1_assist_1_1_base_java_class.html", "classasposebarcode_1_1_assist_1_1_base_java_class" ],
        [ "Rectangle", "classasposebarcode_1_1_assist_1_1_rectangle.html", "classasposebarcode_1_1_assist_1_1_rectangle" ],
        [ "Point", "classasposebarcode_1_1_assist_1_1_point.html", "classasposebarcode_1_1_assist_1_1_point" ],
        [ "License", "classasposebarcode_1_1_assist_1_1_license.html", "classasposebarcode_1_1_assist_1_1_license" ],
        [ "BarCodeException", "classasposebarcode_1_1_assist_1_1_bar_code_exception.html", "classasposebarcode_1_1_assist_1_1_bar_code_exception" ]
      ] ],
      [ "ComplexBarcode", "namespaceasposebarcode_1_1_complex_barcode.html", [
        [ "IComplexCodetext", "classasposebarcode_1_1_complex_barcode_1_1_i_complex_codetext.html", "classasposebarcode_1_1_complex_barcode_1_1_i_complex_codetext" ],
        [ "ComplexBarcodeGenerator", "classasposebarcode_1_1_complex_barcode_1_1_complex_barcode_generator.html", "classasposebarcode_1_1_complex_barcode_1_1_complex_barcode_generator" ],
        [ "Address", "classasposebarcode_1_1_complex_barcode_1_1_address.html", "classasposebarcode_1_1_complex_barcode_1_1_address" ],
        [ "AddressType", "classasposebarcode_1_1_complex_barcode_1_1_address_type.html", null ],
        [ "AlternativeScheme", "classasposebarcode_1_1_complex_barcode_1_1_alternative_scheme.html", "classasposebarcode_1_1_complex_barcode_1_1_alternative_scheme" ],
        [ "ComplexCodetextReader", "classasposebarcode_1_1_complex_barcode_1_1_complex_codetext_reader.html", null ],
        [ "QrBillStandardVersion", "classasposebarcode_1_1_complex_barcode_1_1_qr_bill_standard_version.html", null ],
        [ "SwissQRBill", "classasposebarcode_1_1_complex_barcode_1_1_swiss_q_r_bill.html", "classasposebarcode_1_1_complex_barcode_1_1_swiss_q_r_bill" ],
        [ "SwissQRCodetext", "classasposebarcode_1_1_complex_barcode_1_1_swiss_q_r_codetext.html", "classasposebarcode_1_1_complex_barcode_1_1_swiss_q_r_codetext" ],
        [ "MailmarkCodetext", "classasposebarcode_1_1_complex_barcode_1_1_mailmark_codetext.html", "classasposebarcode_1_1_complex_barcode_1_1_mailmark_codetext" ],
        [ "Mailmark2DCodetext", "classasposebarcode_1_1_complex_barcode_1_1_mailmark2_d_codetext.html", "classasposebarcode_1_1_complex_barcode_1_1_mailmark2_d_codetext" ],
        [ "Mailmark2DType", "classasposebarcode_1_1_complex_barcode_1_1_mailmark2_d_type.html", null ]
      ] ],
      [ "Generation", "namespaceasposebarcode_1_1_generation.html", [
        [ "BarcodeGenerator", "classasposebarcode_1_1_generation_1_1_barcode_generator.html", "classasposebarcode_1_1_generation_1_1_barcode_generator" ],
        [ "BarcodeParameters", "classasposebarcode_1_1_generation_1_1_barcode_parameters.html", "classasposebarcode_1_1_generation_1_1_barcode_parameters" ],
        [ "BaseGenerationParameters", "classasposebarcode_1_1_generation_1_1_base_generation_parameters.html", "classasposebarcode_1_1_generation_1_1_base_generation_parameters" ],
        [ "BorderParameters", "classasposebarcode_1_1_generation_1_1_border_parameters.html", "classasposebarcode_1_1_generation_1_1_border_parameters" ],
        [ "CaptionParameters", "classasposebarcode_1_1_generation_1_1_caption_parameters.html", "classasposebarcode_1_1_generation_1_1_caption_parameters" ],
        [ "Unit", "classasposebarcode_1_1_generation_1_1_unit.html", "classasposebarcode_1_1_generation_1_1_unit" ],
        [ "Padding", "classasposebarcode_1_1_generation_1_1_padding.html", "classasposebarcode_1_1_generation_1_1_padding" ],
        [ "CodetextParameters", "classasposebarcode_1_1_generation_1_1_codetext_parameters.html", "classasposebarcode_1_1_generation_1_1_codetext_parameters" ],
        [ "PostalParameters", "classasposebarcode_1_1_generation_1_1_postal_parameters.html", "classasposebarcode_1_1_generation_1_1_postal_parameters" ],
        [ "AustralianPostParameters", "classasposebarcode_1_1_generation_1_1_australian_post_parameters.html", "classasposebarcode_1_1_generation_1_1_australian_post_parameters" ],
        [ "CodablockParameters", "classasposebarcode_1_1_generation_1_1_codablock_parameters.html", "classasposebarcode_1_1_generation_1_1_codablock_parameters" ],
        [ "DataBarParameters", "classasposebarcode_1_1_generation_1_1_data_bar_parameters.html", "classasposebarcode_1_1_generation_1_1_data_bar_parameters" ],
        [ "DataMatrixParameters", "classasposebarcode_1_1_generation_1_1_data_matrix_parameters.html", "classasposebarcode_1_1_generation_1_1_data_matrix_parameters" ],
        [ "PatchCodeParameters", "classasposebarcode_1_1_generation_1_1_patch_code_parameters.html", "classasposebarcode_1_1_generation_1_1_patch_code_parameters" ],
        [ "Code16KParameters", "classasposebarcode_1_1_generation_1_1_code16_k_parameters.html", "classasposebarcode_1_1_generation_1_1_code16_k_parameters" ],
        [ "DotCodeParameters", "classasposebarcode_1_1_generation_1_1_dot_code_parameters.html", "classasposebarcode_1_1_generation_1_1_dot_code_parameters" ],
        [ "ITFParameters", "classasposebarcode_1_1_generation_1_1_i_t_f_parameters.html", "classasposebarcode_1_1_generation_1_1_i_t_f_parameters" ],
        [ "QrParameters", "classasposebarcode_1_1_generation_1_1_qr_parameters.html", "classasposebarcode_1_1_generation_1_1_qr_parameters" ],
        [ "Pdf417Parameters", "classasposebarcode_1_1_generation_1_1_pdf417_parameters.html", "classasposebarcode_1_1_generation_1_1_pdf417_parameters" ],
        [ "SupplementParameters", "classasposebarcode_1_1_generation_1_1_supplement_parameters.html", "classasposebarcode_1_1_generation_1_1_supplement_parameters" ],
        [ "MaxiCodeParameters", "classasposebarcode_1_1_generation_1_1_maxi_code_parameters.html", "classasposebarcode_1_1_generation_1_1_maxi_code_parameters" ],
        [ "AztecParameters", "classasposebarcode_1_1_generation_1_1_aztec_parameters.html", "classasposebarcode_1_1_generation_1_1_aztec_parameters" ],
        [ "CodabarParameters", "classasposebarcode_1_1_generation_1_1_codabar_parameters.html", "classasposebarcode_1_1_generation_1_1_codabar_parameters" ],
        [ "CouponParameters", "classasposebarcode_1_1_generation_1_1_coupon_parameters.html", "classasposebarcode_1_1_generation_1_1_coupon_parameters" ],
        [ "FontUnit", "classasposebarcode_1_1_generation_1_1_font_unit.html", "classasposebarcode_1_1_generation_1_1_font_unit" ],
        [ "ExtCodetextBuilder", "classasposebarcode_1_1_generation_1_1_ext_codetext_builder.html", "classasposebarcode_1_1_generation_1_1_ext_codetext_builder" ],
        [ "QrExtCodetextBuilder", "classasposebarcode_1_1_generation_1_1_qr_ext_codetext_builder.html", "classasposebarcode_1_1_generation_1_1_qr_ext_codetext_builder" ],
        [ "QrStructuredAppendParameters", "classasposebarcode_1_1_generation_1_1_qr_structured_append_parameters.html", "classasposebarcode_1_1_generation_1_1_qr_structured_append_parameters" ],
        [ "MacroCharacter", "classasposebarcode_1_1_generation_1_1_macro_character.html", null ],
        [ "FontStyle", "classasposebarcode_1_1_generation_1_1_font_style.html", null ],
        [ "CodabarSymbol", "classasposebarcode_1_1_generation_1_1_codabar_symbol.html", null ],
        [ "DataMatrixEncodeMode", "classasposebarcode_1_1_generation_1_1_data_matrix_encode_mode.html", null ],
        [ "BorderDashStyle", "classasposebarcode_1_1_generation_1_1_border_dash_style.html", null ],
        [ "ITF14BorderType", "classasposebarcode_1_1_generation_1_1_i_t_f14_border_type.html", null ],
        [ "QREncodeMode", "classasposebarcode_1_1_generation_1_1_q_r_encode_mode.html", null ],
        [ "DataMatrixEccType", "classasposebarcode_1_1_generation_1_1_data_matrix_ecc_type.html", null ],
        [ "QRVersion", "classasposebarcode_1_1_generation_1_1_q_r_version.html", null ],
        [ "AztecSymbolMode", "classasposebarcode_1_1_generation_1_1_aztec_symbol_mode.html", null ],
        [ "Pdf417ErrorLevel", "classasposebarcode_1_1_generation_1_1_pdf417_error_level.html", null ],
        [ "Pdf417CompactionMode", "classasposebarcode_1_1_generation_1_1_pdf417_compaction_mode.html", null ],
        [ "QRErrorLevel", "classasposebarcode_1_1_generation_1_1_q_r_error_level.html", null ],
        [ "QREncodeType", "classasposebarcode_1_1_generation_1_1_q_r_encode_type.html", null ],
        [ "CodabarChecksumMode", "classasposebarcode_1_1_generation_1_1_codabar_checksum_mode.html", null ],
        [ "CodeLocation", "classasposebarcode_1_1_generation_1_1_code_location.html", null ],
        [ "FontMode", "classasposebarcode_1_1_generation_1_1_font_mode.html", null ],
        [ "TextAlignment", "classasposebarcode_1_1_generation_1_1_text_alignment.html", null ],
        [ "AutoSizeMode", "classasposebarcode_1_1_generation_1_1_auto_size_mode.html", null ],
        [ "GraphicsUnit", "classasposebarcode_1_1_generation_1_1_graphics_unit.html", null ],
        [ "EncodeTypes", "classasposebarcode_1_1_generation_1_1_encode_types.html", null ],
        [ "PatchFormat", "classasposebarcode_1_1_generation_1_1_patch_format.html", null ],
        [ "ECIEncodings", "classasposebarcode_1_1_generation_1_1_e_c_i_encodings.html", null ],
        [ "EnableChecksum", "classasposebarcode_1_1_generation_1_1_enable_checksum.html", null ],
        [ "Code128Emulation", "classasposebarcode_1_1_generation_1_1_code128_emulation.html", null ],
        [ "BarCodeImageFormat", "classasposebarcode_1_1_generation_1_1_bar_code_image_format.html", null ],
        [ "CustomerInformationInterpretingType", "classasposebarcode_1_1_generation_1_1_customer_information_interpreting_type.html", null ]
      ] ],
      [ "Recognition", "namespaceasposebarcode_1_1_recognition.html", [
        [ "BarCodeReader", "classasposebarcode_1_1_recognition_1_1_bar_code_reader.html", "classasposebarcode_1_1_recognition_1_1_bar_code_reader" ],
        [ "Quadrangle", "classasposebarcode_1_1_recognition_1_1_quadrangle.html", "classasposebarcode_1_1_recognition_1_1_quadrangle" ],
        [ "QRExtendedParameters", "classasposebarcode_1_1_recognition_1_1_q_r_extended_parameters.html", "classasposebarcode_1_1_recognition_1_1_q_r_extended_parameters" ],
        [ "Pdf417ExtendedParameters", "classasposebarcode_1_1_recognition_1_1_pdf417_extended_parameters.html", "classasposebarcode_1_1_recognition_1_1_pdf417_extended_parameters" ],
        [ "OneDExtendedParameters", "classasposebarcode_1_1_recognition_1_1_one_d_extended_parameters.html", "classasposebarcode_1_1_recognition_1_1_one_d_extended_parameters" ],
        [ "Code128ExtendedParameters", "classasposebarcode_1_1_recognition_1_1_code128_extended_parameters.html", "classasposebarcode_1_1_recognition_1_1_code128_extended_parameters" ],
        [ "BarcodeSvmDetectorSettings", "classasposebarcode_1_1_recognition_1_1_barcode_svm_detector_settings.html", "classasposebarcode_1_1_recognition_1_1_barcode_svm_detector_settings" ],
        [ "BarCodeResult", "classasposebarcode_1_1_recognition_1_1_bar_code_result.html", "classasposebarcode_1_1_recognition_1_1_bar_code_result" ],
        [ "BarCodeRegionParameters", "classasposebarcode_1_1_recognition_1_1_bar_code_region_parameters.html", "classasposebarcode_1_1_recognition_1_1_bar_code_region_parameters" ],
        [ "BarCodeExtendedParameters", "classasposebarcode_1_1_recognition_1_1_bar_code_extended_parameters.html", "classasposebarcode_1_1_recognition_1_1_bar_code_extended_parameters" ],
        [ "QualitySettings", "classasposebarcode_1_1_recognition_1_1_quality_settings.html", "classasposebarcode_1_1_recognition_1_1_quality_settings" ],
        [ "Code128DataPortion", "classasposebarcode_1_1_recognition_1_1_code128_data_portion.html", "classasposebarcode_1_1_recognition_1_1_code128_data_portion" ],
        [ "DataBarExtendedParameters", "classasposebarcode_1_1_recognition_1_1_data_bar_extended_parameters.html", "classasposebarcode_1_1_recognition_1_1_data_bar_extended_parameters" ],
        [ "AustraliaPostSettings", "classasposebarcode_1_1_recognition_1_1_australia_post_settings.html", "classasposebarcode_1_1_recognition_1_1_australia_post_settings" ],
        [ "BarcodeSettings", "classasposebarcode_1_1_recognition_1_1_barcode_settings.html", "classasposebarcode_1_1_recognition_1_1_barcode_settings" ],
        [ "RecognitionAbortedException", "classasposebarcode_1_1_recognition_1_1_recognition_aborted_exception.html", "classasposebarcode_1_1_recognition_1_1_recognition_aborted_exception" ],
        [ "DecodeType", "classasposebarcode_1_1_recognition_1_1_decode_type.html", null ],
        [ "Code128SubType", "classasposebarcode_1_1_recognition_1_1_code128_sub_type.html", null ],
        [ "CustomerInformationInterpretingType", "classasposebarcode_1_1_recognition_1_1_customer_information_interpreting_type.html", null ],
        [ "BarCodeConfidence", "classasposebarcode_1_1_recognition_1_1_bar_code_confidence.html", null ],
        [ "ChecksumValidation", "classasposebarcode_1_1_recognition_1_1_checksum_validation.html", null ]
      ] ]
    ] ]
];