var hierarchy =
[
    [ "asposebarcode.Generation.Code128Emulation", "classasposebarcode_1_1_generation_1_1_code128_emulation.html", null ],
    [ "Exception", null, [
      [ "asposebarcode.Assist.BarCodeException", "classasposebarcode_1_1_assist_1_1_bar_code_exception.html", null ],
      [ "asposebarcode.Recognition.RecognitionAbortedException", "classasposebarcode_1_1_recognition_1_1_recognition_aborted_exception.html", null ]
    ] ],
    [ "asposebarcode.Generation.MacroCharacter", "classasposebarcode_1_1_generation_1_1_macro_character.html", null ],
    [ "object", null, [
      [ "asposebarcode.Assist.BaseJavaClass", "classasposebarcode_1_1_assist_1_1_base_java_class.html", [
        [ "asposebarcode.Assist.License", "classasposebarcode_1_1_assist_1_1_license.html", null ],
        [ "asposebarcode.Assist.Point", "classasposebarcode_1_1_assist_1_1_point.html", null ],
        [ "asposebarcode.Assist.Rectangle", "classasposebarcode_1_1_assist_1_1_rectangle.html", null ],
        [ "asposebarcode.ComplexBarcode.Address", "classasposebarcode_1_1_complex_barcode_1_1_address.html", null ],
        [ "asposebarcode.ComplexBarcode.AlternativeScheme", "classasposebarcode_1_1_complex_barcode_1_1_alternative_scheme.html", null ],
        [ "asposebarcode.ComplexBarcode.ComplexBarcodeGenerator", "classasposebarcode_1_1_complex_barcode_1_1_complex_barcode_generator.html", null ],
        [ "asposebarcode.ComplexBarcode.ComplexCodetextReader", "classasposebarcode_1_1_complex_barcode_1_1_complex_codetext_reader.html", null ],
        [ "asposebarcode.ComplexBarcode.IComplexCodetext", "classasposebarcode_1_1_complex_barcode_1_1_i_complex_codetext.html", [
          [ "asposebarcode.ComplexBarcode.Mailmark2DCodetext", "classasposebarcode_1_1_complex_barcode_1_1_mailmark2_d_codetext.html", null ],
          [ "asposebarcode.ComplexBarcode.MailmarkCodetext", "classasposebarcode_1_1_complex_barcode_1_1_mailmark_codetext.html", null ],
          [ "asposebarcode.ComplexBarcode.SwissQRCodetext", "classasposebarcode_1_1_complex_barcode_1_1_swiss_q_r_codetext.html", null ]
        ] ],
        [ "asposebarcode.ComplexBarcode.SwissQRBill", "classasposebarcode_1_1_complex_barcode_1_1_swiss_q_r_bill.html", null ],
        [ "asposebarcode.Generation.AustralianPostParameters", "classasposebarcode_1_1_generation_1_1_australian_post_parameters.html", null ],
        [ "asposebarcode.Generation.AztecParameters", "classasposebarcode_1_1_generation_1_1_aztec_parameters.html", null ],
        [ "asposebarcode.Generation.BarcodeGenerator", "classasposebarcode_1_1_generation_1_1_barcode_generator.html", null ],
        [ "asposebarcode.Generation.BarcodeParameters", "classasposebarcode_1_1_generation_1_1_barcode_parameters.html", null ],
        [ "asposebarcode.Generation.BaseGenerationParameters", "classasposebarcode_1_1_generation_1_1_base_generation_parameters.html", null ],
        [ "asposebarcode.Generation.BorderParameters", "classasposebarcode_1_1_generation_1_1_border_parameters.html", null ],
        [ "asposebarcode.Generation.CaptionParameters", "classasposebarcode_1_1_generation_1_1_caption_parameters.html", null ],
        [ "asposebarcode.Generation.CodabarParameters", "classasposebarcode_1_1_generation_1_1_codabar_parameters.html", null ],
        [ "asposebarcode.Generation.CodablockParameters", "classasposebarcode_1_1_generation_1_1_codablock_parameters.html", null ],
        [ "asposebarcode.Generation.Code16KParameters", "classasposebarcode_1_1_generation_1_1_code16_k_parameters.html", null ],
        [ "asposebarcode.Generation.CodetextParameters", "classasposebarcode_1_1_generation_1_1_codetext_parameters.html", null ],
        [ "asposebarcode.Generation.CouponParameters", "classasposebarcode_1_1_generation_1_1_coupon_parameters.html", null ],
        [ "asposebarcode.Generation.DataBarParameters", "classasposebarcode_1_1_generation_1_1_data_bar_parameters.html", null ],
        [ "asposebarcode.Generation.DataMatrixParameters", "classasposebarcode_1_1_generation_1_1_data_matrix_parameters.html", null ],
        [ "asposebarcode.Generation.DotCodeParameters", "classasposebarcode_1_1_generation_1_1_dot_code_parameters.html", null ],
        [ "asposebarcode.Generation.ExtCodetextBuilder", "classasposebarcode_1_1_generation_1_1_ext_codetext_builder.html", [
          [ "asposebarcode.Generation.QrExtCodetextBuilder", "classasposebarcode_1_1_generation_1_1_qr_ext_codetext_builder.html", null ]
        ] ],
        [ "asposebarcode.Generation.FontUnit", "classasposebarcode_1_1_generation_1_1_font_unit.html", null ],
        [ "asposebarcode.Generation.ITFParameters", "classasposebarcode_1_1_generation_1_1_i_t_f_parameters.html", null ],
        [ "asposebarcode.Generation.MaxiCodeParameters", "classasposebarcode_1_1_generation_1_1_maxi_code_parameters.html", null ],
        [ "asposebarcode.Generation.Padding", "classasposebarcode_1_1_generation_1_1_padding.html", null ],
        [ "asposebarcode.Generation.PatchCodeParameters", "classasposebarcode_1_1_generation_1_1_patch_code_parameters.html", null ],
        [ "asposebarcode.Generation.Pdf417Parameters", "classasposebarcode_1_1_generation_1_1_pdf417_parameters.html", null ],
        [ "asposebarcode.Generation.PostalParameters", "classasposebarcode_1_1_generation_1_1_postal_parameters.html", null ],
        [ "asposebarcode.Generation.QrParameters", "classasposebarcode_1_1_generation_1_1_qr_parameters.html", null ],
        [ "asposebarcode.Generation.QrStructuredAppendParameters", "classasposebarcode_1_1_generation_1_1_qr_structured_append_parameters.html", null ],
        [ "asposebarcode.Generation.SupplementParameters", "classasposebarcode_1_1_generation_1_1_supplement_parameters.html", null ],
        [ "asposebarcode.Generation.Unit", "classasposebarcode_1_1_generation_1_1_unit.html", null ],
        [ "asposebarcode.Recognition.AustraliaPostSettings", "classasposebarcode_1_1_recognition_1_1_australia_post_settings.html", null ],
        [ "asposebarcode.Recognition.BarCodeExtendedParameters", "classasposebarcode_1_1_recognition_1_1_bar_code_extended_parameters.html", null ],
        [ "asposebarcode.Recognition.BarCodeReader", "classasposebarcode_1_1_recognition_1_1_bar_code_reader.html", null ],
        [ "asposebarcode.Recognition.BarCodeRegionParameters", "classasposebarcode_1_1_recognition_1_1_bar_code_region_parameters.html", null ],
        [ "asposebarcode.Recognition.BarCodeResult", "classasposebarcode_1_1_recognition_1_1_bar_code_result.html", null ],
        [ "asposebarcode.Recognition.BarcodeSettings", "classasposebarcode_1_1_recognition_1_1_barcode_settings.html", null ],
        [ "asposebarcode.Recognition.BarcodeSvmDetectorSettings", "classasposebarcode_1_1_recognition_1_1_barcode_svm_detector_settings.html", null ],
        [ "asposebarcode.Recognition.Code128DataPortion", "classasposebarcode_1_1_recognition_1_1_code128_data_portion.html", null ],
        [ "asposebarcode.Recognition.Code128ExtendedParameters", "classasposebarcode_1_1_recognition_1_1_code128_extended_parameters.html", null ],
        [ "asposebarcode.Recognition.DataBarExtendedParameters", "classasposebarcode_1_1_recognition_1_1_data_bar_extended_parameters.html", null ],
        [ "asposebarcode.Recognition.OneDExtendedParameters", "classasposebarcode_1_1_recognition_1_1_one_d_extended_parameters.html", null ],
        [ "asposebarcode.Recognition.Pdf417ExtendedParameters", "classasposebarcode_1_1_recognition_1_1_pdf417_extended_parameters.html", null ],
        [ "asposebarcode.Recognition.QRExtendedParameters", "classasposebarcode_1_1_recognition_1_1_q_r_extended_parameters.html", null ],
        [ "asposebarcode.Recognition.Quadrangle", "classasposebarcode_1_1_recognition_1_1_quadrangle.html", null ],
        [ "asposebarcode.Recognition.QualitySettings", "classasposebarcode_1_1_recognition_1_1_quality_settings.html", null ]
      ] ]
    ] ],
    [ "Enum", null, [
      [ "asposebarcode.ComplexBarcode.AddressType", "classasposebarcode_1_1_complex_barcode_1_1_address_type.html", null ],
      [ "asposebarcode.ComplexBarcode.Mailmark2DType", "classasposebarcode_1_1_complex_barcode_1_1_mailmark2_d_type.html", null ],
      [ "asposebarcode.ComplexBarcode.QrBillStandardVersion", "classasposebarcode_1_1_complex_barcode_1_1_qr_bill_standard_version.html", null ],
      [ "asposebarcode.Generation.AutoSizeMode", "classasposebarcode_1_1_generation_1_1_auto_size_mode.html", null ],
      [ "asposebarcode.Generation.AztecSymbolMode", "classasposebarcode_1_1_generation_1_1_aztec_symbol_mode.html", null ],
      [ "asposebarcode.Generation.BarCodeImageFormat", "classasposebarcode_1_1_generation_1_1_bar_code_image_format.html", null ],
      [ "asposebarcode.Generation.BorderDashStyle", "classasposebarcode_1_1_generation_1_1_border_dash_style.html", null ],
      [ "asposebarcode.Generation.CodabarChecksumMode", "classasposebarcode_1_1_generation_1_1_codabar_checksum_mode.html", null ],
      [ "asposebarcode.Generation.CodabarSymbol", "classasposebarcode_1_1_generation_1_1_codabar_symbol.html", null ],
      [ "asposebarcode.Generation.CodeLocation", "classasposebarcode_1_1_generation_1_1_code_location.html", null ],
      [ "asposebarcode.Generation.CustomerInformationInterpretingType", "classasposebarcode_1_1_generation_1_1_customer_information_interpreting_type.html", null ],
      [ "asposebarcode.Generation.DataMatrixEccType", "classasposebarcode_1_1_generation_1_1_data_matrix_ecc_type.html", null ],
      [ "asposebarcode.Generation.DataMatrixEncodeMode", "classasposebarcode_1_1_generation_1_1_data_matrix_encode_mode.html", null ],
      [ "asposebarcode.Generation.ECIEncodings", "classasposebarcode_1_1_generation_1_1_e_c_i_encodings.html", null ],
      [ "asposebarcode.Generation.EnableChecksum", "classasposebarcode_1_1_generation_1_1_enable_checksum.html", null ],
      [ "asposebarcode.Generation.EncodeTypes", "classasposebarcode_1_1_generation_1_1_encode_types.html", null ],
      [ "asposebarcode.Generation.FontMode", "classasposebarcode_1_1_generation_1_1_font_mode.html", null ],
      [ "asposebarcode.Generation.FontStyle", "classasposebarcode_1_1_generation_1_1_font_style.html", null ],
      [ "asposebarcode.Generation.GraphicsUnit", "classasposebarcode_1_1_generation_1_1_graphics_unit.html", null ],
      [ "asposebarcode.Generation.ITF14BorderType", "classasposebarcode_1_1_generation_1_1_i_t_f14_border_type.html", null ],
      [ "asposebarcode.Generation.PatchFormat", "classasposebarcode_1_1_generation_1_1_patch_format.html", null ],
      [ "asposebarcode.Generation.Pdf417CompactionMode", "classasposebarcode_1_1_generation_1_1_pdf417_compaction_mode.html", null ],
      [ "asposebarcode.Generation.Pdf417ErrorLevel", "classasposebarcode_1_1_generation_1_1_pdf417_error_level.html", null ],
      [ "asposebarcode.Generation.QREncodeMode", "classasposebarcode_1_1_generation_1_1_q_r_encode_mode.html", null ],
      [ "asposebarcode.Generation.QREncodeType", "classasposebarcode_1_1_generation_1_1_q_r_encode_type.html", null ],
      [ "asposebarcode.Generation.QRErrorLevel", "classasposebarcode_1_1_generation_1_1_q_r_error_level.html", null ],
      [ "asposebarcode.Generation.QRVersion", "classasposebarcode_1_1_generation_1_1_q_r_version.html", null ],
      [ "asposebarcode.Generation.TextAlignment", "classasposebarcode_1_1_generation_1_1_text_alignment.html", null ],
      [ "asposebarcode.Recognition.BarCodeConfidence", "classasposebarcode_1_1_recognition_1_1_bar_code_confidence.html", null ],
      [ "asposebarcode.Recognition.ChecksumValidation", "classasposebarcode_1_1_recognition_1_1_checksum_validation.html", null ],
      [ "asposebarcode.Recognition.Code128SubType", "classasposebarcode_1_1_recognition_1_1_code128_sub_type.html", null ],
      [ "asposebarcode.Recognition.CustomerInformationInterpretingType", "classasposebarcode_1_1_recognition_1_1_customer_information_interpreting_type.html", null ],
      [ "asposebarcode.Recognition.DecodeType", "classasposebarcode_1_1_recognition_1_1_decode_type.html", null ]
    ] ]
];