var namespace_system_1_1_text =
[
    [ "Details", "namespace_system_1_1_text_1_1_details.html", null ],
    [ "RegularExpressions", "namespace_system_1_1_text_1_1_regular_expressions.html", "namespace_system_1_1_text_1_1_regular_expressions" ],
    [ "ASCIIEncoding", "class_system_1_1_text_1_1_a_s_c_i_i_encoding.html", "class_system_1_1_text_1_1_a_s_c_i_i_encoding" ],
    [ "Decoder", "class_system_1_1_text_1_1_decoder.html", "class_system_1_1_text_1_1_decoder" ],
    [ "DecoderExceptionFallback", "class_system_1_1_text_1_1_decoder_exception_fallback.html", "class_system_1_1_text_1_1_decoder_exception_fallback" ],
    [ "DecoderExceptionFallbackBuffer", "class_system_1_1_text_1_1_decoder_exception_fallback_buffer.html", "class_system_1_1_text_1_1_decoder_exception_fallback_buffer" ],
    [ "DecoderFallback", "class_system_1_1_text_1_1_decoder_fallback.html", "class_system_1_1_text_1_1_decoder_fallback" ],
    [ "DecoderFallbackBuffer", "class_system_1_1_text_1_1_decoder_fallback_buffer.html", "class_system_1_1_text_1_1_decoder_fallback_buffer" ],
    [ "Details_DecoderFallbackException", "class_system_1_1_text_1_1_details___decoder_fallback_exception.html", "class_system_1_1_text_1_1_details___decoder_fallback_exception" ],
    [ "DecoderReplacementFallback", "class_system_1_1_text_1_1_decoder_replacement_fallback.html", "class_system_1_1_text_1_1_decoder_replacement_fallback" ],
    [ "DecoderReplacementFallbackBuffer", "class_system_1_1_text_1_1_decoder_replacement_fallback_buffer.html", "class_system_1_1_text_1_1_decoder_replacement_fallback_buffer" ],
    [ "Encoder", "class_system_1_1_text_1_1_encoder.html", "class_system_1_1_text_1_1_encoder" ],
    [ "EncoderExceptionFallback", "class_system_1_1_text_1_1_encoder_exception_fallback.html", "class_system_1_1_text_1_1_encoder_exception_fallback" ],
    [ "EncoderExceptionFallbackBuffer", "class_system_1_1_text_1_1_encoder_exception_fallback_buffer.html", "class_system_1_1_text_1_1_encoder_exception_fallback_buffer" ],
    [ "EncoderFallback", "class_system_1_1_text_1_1_encoder_fallback.html", "class_system_1_1_text_1_1_encoder_fallback" ],
    [ "EncoderFallbackBuffer", "class_system_1_1_text_1_1_encoder_fallback_buffer.html", "class_system_1_1_text_1_1_encoder_fallback_buffer" ],
    [ "Details_EncoderFallbackException", "class_system_1_1_text_1_1_details___encoder_fallback_exception.html", "class_system_1_1_text_1_1_details___encoder_fallback_exception" ],
    [ "EncoderReplacementFallback", "class_system_1_1_text_1_1_encoder_replacement_fallback.html", "class_system_1_1_text_1_1_encoder_replacement_fallback" ],
    [ "EncoderReplacementFallbackBuffer", "class_system_1_1_text_1_1_encoder_replacement_fallback_buffer.html", "class_system_1_1_text_1_1_encoder_replacement_fallback_buffer" ],
    [ "EncodingInfo", "class_system_1_1_text_1_1_encoding_info.html", "class_system_1_1_text_1_1_encoding_info" ],
    [ "Encoding", "class_system_1_1_text_1_1_encoding.html", "class_system_1_1_text_1_1_encoding" ],
    [ "EncodingDecoder", "class_system_1_1_text_1_1_encoding_decoder.html", "class_system_1_1_text_1_1_encoding_decoder" ],
    [ "EncodingEncoder", "class_system_1_1_text_1_1_encoding_encoder.html", "class_system_1_1_text_1_1_encoding_encoder" ],
    [ "ICUDecoder", "class_system_1_1_text_1_1_i_c_u_decoder.html", "class_system_1_1_text_1_1_i_c_u_decoder" ],
    [ "ICUEncoder", "class_system_1_1_text_1_1_i_c_u_encoder.html", "class_system_1_1_text_1_1_i_c_u_encoder" ],
    [ "ICUEncoding", "class_system_1_1_text_1_1_i_c_u_encoding.html", "class_system_1_1_text_1_1_i_c_u_encoding" ],
    [ "Latin1Encoding", "class_system_1_1_text_1_1_latin1_encoding.html", "class_system_1_1_text_1_1_latin1_encoding" ],
    [ "StringBuilder", "class_system_1_1_text_1_1_string_builder.html", "class_system_1_1_text_1_1_string_builder" ],
    [ "UnicodeEncoding", "class_system_1_1_text_1_1_unicode_encoding.html", "class_system_1_1_text_1_1_unicode_encoding" ],
    [ "UTF32Encoding", "class_system_1_1_text_1_1_u_t_f32_encoding.html", "class_system_1_1_text_1_1_u_t_f32_encoding" ],
    [ "UTF7Encoding", "class_system_1_1_text_1_1_u_t_f7_encoding.html", "class_system_1_1_text_1_1_u_t_f7_encoding" ],
    [ "UTF8Encoding", "class_system_1_1_text_1_1_u_t_f8_encoding.html", "class_system_1_1_text_1_1_u_t_f8_encoding" ],
    [ "DecoderFallbackException", "namespace_system_1_1_text.html#a3e9475a2685b015d49390f47a7870459", null ],
    [ "EncoderFallbackException", "namespace_system_1_1_text.html#a0ca359e7bf6d565ddb236283f5f84f2c", null ],
    [ "ICUEncodingPtr", "namespace_system_1_1_text.html#a8e9a2fbcbe2e886793a66bbc7246eb9f", null ],
    [ "NormalizationForm", "namespace_system_1_1_text.html#a0e9edef1066fd6236ab1a9076fc654b8", [
      [ "FormC", "namespace_system_1_1_text.html#a0e9edef1066fd6236ab1a9076fc654b8ad545d7924397dac826afd17f81ed4bd0", null ],
      [ "FormD", "namespace_system_1_1_text.html#a0e9edef1066fd6236ab1a9076fc654b8a21aaf61d7e17ea089f3c347e2230b476", null ],
      [ "FormKC", "namespace_system_1_1_text.html#a0e9edef1066fd6236ab1a9076fc654b8a5fd3985c441cf337a14772a8128d2eba", null ],
      [ "FormKD", "namespace_system_1_1_text.html#a0e9edef1066fd6236ab1a9076fc654b8a040dd5ae05e98fcd9ff1bc03baa91815", null ]
    ] ]
];