var annotated =
[
    [ "Aspose", "namespace_aspose.html", [
      [ "Words", "namespace_aspose_1_1_words.html", [
        [ "BuildingBlocks", "namespace_aspose_1_1_words_1_1_building_blocks.html", [
          [ "BuildingBlock", "class_aspose_1_1_words_1_1_building_blocks_1_1_building_block.html", "class_aspose_1_1_words_1_1_building_blocks_1_1_building_block" ],
          [ "BuildingBlockCollection", "class_aspose_1_1_words_1_1_building_blocks_1_1_building_block_collection.html", "class_aspose_1_1_words_1_1_building_blocks_1_1_building_block_collection" ],
          [ "GlossaryDocument", "class_aspose_1_1_words_1_1_building_blocks_1_1_glossary_document.html", "class_aspose_1_1_words_1_1_building_blocks_1_1_glossary_document" ]
        ] ],
        [ "Comparing", "namespace_aspose_1_1_words_1_1_comparing.html", [
          [ "CompareOptions", "class_aspose_1_1_words_1_1_comparing_1_1_compare_options.html", "class_aspose_1_1_words_1_1_comparing_1_1_compare_options" ]
        ] ],
        [ "DigitalSignatures", "namespace_aspose_1_1_words_1_1_digital_signatures.html", [
          [ "CertificateHolder", "class_aspose_1_1_words_1_1_digital_signatures_1_1_certificate_holder.html", "class_aspose_1_1_words_1_1_digital_signatures_1_1_certificate_holder" ],
          [ "DigitalSignature", "class_aspose_1_1_words_1_1_digital_signatures_1_1_digital_signature.html", "class_aspose_1_1_words_1_1_digital_signatures_1_1_digital_signature" ],
          [ "DigitalSignatureCollection", "class_aspose_1_1_words_1_1_digital_signatures_1_1_digital_signature_collection.html", "class_aspose_1_1_words_1_1_digital_signatures_1_1_digital_signature_collection" ],
          [ "DigitalSignatureUtil", "class_aspose_1_1_words_1_1_digital_signatures_1_1_digital_signature_util.html", "class_aspose_1_1_words_1_1_digital_signatures_1_1_digital_signature_util" ],
          [ "SignOptions", "class_aspose_1_1_words_1_1_digital_signatures_1_1_sign_options.html", "class_aspose_1_1_words_1_1_digital_signatures_1_1_sign_options" ]
        ] ],
        [ "Drawing", "namespace_aspose_1_1_words_1_1_drawing.html", [
          [ "Charts", "namespace_aspose_1_1_words_1_1_drawing_1_1_charts.html", [
            [ "AxisBound", "class_aspose_1_1_words_1_1_drawing_1_1_charts_1_1_axis_bound.html", "class_aspose_1_1_words_1_1_drawing_1_1_charts_1_1_axis_bound" ],
            [ "AxisDisplayUnit", "class_aspose_1_1_words_1_1_drawing_1_1_charts_1_1_axis_display_unit.html", "class_aspose_1_1_words_1_1_drawing_1_1_charts_1_1_axis_display_unit" ],
            [ "AxisScaling", "class_aspose_1_1_words_1_1_drawing_1_1_charts_1_1_axis_scaling.html", "class_aspose_1_1_words_1_1_drawing_1_1_charts_1_1_axis_scaling" ],
            [ "Chart", "class_aspose_1_1_words_1_1_drawing_1_1_charts_1_1_chart.html", "class_aspose_1_1_words_1_1_drawing_1_1_charts_1_1_chart" ],
            [ "ChartAxis", "class_aspose_1_1_words_1_1_drawing_1_1_charts_1_1_chart_axis.html", "class_aspose_1_1_words_1_1_drawing_1_1_charts_1_1_chart_axis" ],
            [ "ChartDataLabel", "class_aspose_1_1_words_1_1_drawing_1_1_charts_1_1_chart_data_label.html", "class_aspose_1_1_words_1_1_drawing_1_1_charts_1_1_chart_data_label" ],
            [ "ChartDataLabelCollection", "class_aspose_1_1_words_1_1_drawing_1_1_charts_1_1_chart_data_label_collection.html", "class_aspose_1_1_words_1_1_drawing_1_1_charts_1_1_chart_data_label_collection" ],
            [ "ChartDataPoint", "class_aspose_1_1_words_1_1_drawing_1_1_charts_1_1_chart_data_point.html", "class_aspose_1_1_words_1_1_drawing_1_1_charts_1_1_chart_data_point" ],
            [ "ChartDataPointCollection", "class_aspose_1_1_words_1_1_drawing_1_1_charts_1_1_chart_data_point_collection.html", "class_aspose_1_1_words_1_1_drawing_1_1_charts_1_1_chart_data_point_collection" ],
            [ "ChartFormat", "class_aspose_1_1_words_1_1_drawing_1_1_charts_1_1_chart_format.html", "class_aspose_1_1_words_1_1_drawing_1_1_charts_1_1_chart_format" ],
            [ "ChartLegend", "class_aspose_1_1_words_1_1_drawing_1_1_charts_1_1_chart_legend.html", "class_aspose_1_1_words_1_1_drawing_1_1_charts_1_1_chart_legend" ],
            [ "ChartMarker", "class_aspose_1_1_words_1_1_drawing_1_1_charts_1_1_chart_marker.html", "class_aspose_1_1_words_1_1_drawing_1_1_charts_1_1_chart_marker" ],
            [ "ChartNumberFormat", "class_aspose_1_1_words_1_1_drawing_1_1_charts_1_1_chart_number_format.html", "class_aspose_1_1_words_1_1_drawing_1_1_charts_1_1_chart_number_format" ],
            [ "ChartSeries", "class_aspose_1_1_words_1_1_drawing_1_1_charts_1_1_chart_series.html", "class_aspose_1_1_words_1_1_drawing_1_1_charts_1_1_chart_series" ],
            [ "ChartSeriesCollection", "class_aspose_1_1_words_1_1_drawing_1_1_charts_1_1_chart_series_collection.html", "class_aspose_1_1_words_1_1_drawing_1_1_charts_1_1_chart_series_collection" ],
            [ "ChartTitle", "class_aspose_1_1_words_1_1_drawing_1_1_charts_1_1_chart_title.html", "class_aspose_1_1_words_1_1_drawing_1_1_charts_1_1_chart_title" ],
            [ "IChartDataPoint", "class_aspose_1_1_words_1_1_drawing_1_1_charts_1_1_i_chart_data_point.html", "class_aspose_1_1_words_1_1_drawing_1_1_charts_1_1_i_chart_data_point" ]
          ] ],
          [ "Fill", "class_aspose_1_1_words_1_1_drawing_1_1_fill.html", "class_aspose_1_1_words_1_1_drawing_1_1_fill" ],
          [ "GradientStop", "class_aspose_1_1_words_1_1_drawing_1_1_gradient_stop.html", "class_aspose_1_1_words_1_1_drawing_1_1_gradient_stop" ],
          [ "GradientStopCollection", "class_aspose_1_1_words_1_1_drawing_1_1_gradient_stop_collection.html", "class_aspose_1_1_words_1_1_drawing_1_1_gradient_stop_collection" ],
          [ "GroupShape", "class_aspose_1_1_words_1_1_drawing_1_1_group_shape.html", "class_aspose_1_1_words_1_1_drawing_1_1_group_shape" ],
          [ "HorizontalRuleFormat", "class_aspose_1_1_words_1_1_drawing_1_1_horizontal_rule_format.html", "class_aspose_1_1_words_1_1_drawing_1_1_horizontal_rule_format" ],
          [ "ImageData", "class_aspose_1_1_words_1_1_drawing_1_1_image_data.html", "class_aspose_1_1_words_1_1_drawing_1_1_image_data" ],
          [ "ImageSize", "class_aspose_1_1_words_1_1_drawing_1_1_image_size.html", "class_aspose_1_1_words_1_1_drawing_1_1_image_size" ],
          [ "OleFormat", "class_aspose_1_1_words_1_1_drawing_1_1_ole_format.html", "class_aspose_1_1_words_1_1_drawing_1_1_ole_format" ],
          [ "OlePackage", "class_aspose_1_1_words_1_1_drawing_1_1_ole_package.html", "class_aspose_1_1_words_1_1_drawing_1_1_ole_package" ],
          [ "Shape", "class_aspose_1_1_words_1_1_drawing_1_1_shape.html", "class_aspose_1_1_words_1_1_drawing_1_1_shape" ],
          [ "ShapeBase", "class_aspose_1_1_words_1_1_drawing_1_1_shape_base.html", "class_aspose_1_1_words_1_1_drawing_1_1_shape_base" ],
          [ "SignatureLine", "class_aspose_1_1_words_1_1_drawing_1_1_signature_line.html", "class_aspose_1_1_words_1_1_drawing_1_1_signature_line" ],
          [ "Stroke", "class_aspose_1_1_words_1_1_drawing_1_1_stroke.html", "class_aspose_1_1_words_1_1_drawing_1_1_stroke" ],
          [ "TextBox", "class_aspose_1_1_words_1_1_drawing_1_1_text_box.html", "class_aspose_1_1_words_1_1_drawing_1_1_text_box" ],
          [ "TextPath", "class_aspose_1_1_words_1_1_drawing_1_1_text_path.html", "class_aspose_1_1_words_1_1_drawing_1_1_text_path" ]
        ] ],
        [ "Fields", "namespace_aspose_1_1_words_1_1_fields.html", [
          [ "BarcodeParameters", "class_aspose_1_1_words_1_1_fields_1_1_barcode_parameters.html", "class_aspose_1_1_words_1_1_fields_1_1_barcode_parameters" ],
          [ "ComparisonEvaluationResult", "class_aspose_1_1_words_1_1_fields_1_1_comparison_evaluation_result.html", "class_aspose_1_1_words_1_1_fields_1_1_comparison_evaluation_result" ],
          [ "ComparisonExpression", "class_aspose_1_1_words_1_1_fields_1_1_comparison_expression.html", "class_aspose_1_1_words_1_1_fields_1_1_comparison_expression" ],
          [ "DropDownItemCollection", "class_aspose_1_1_words_1_1_fields_1_1_drop_down_item_collection.html", "class_aspose_1_1_words_1_1_fields_1_1_drop_down_item_collection" ],
          [ "Field", "class_aspose_1_1_words_1_1_fields_1_1_field.html", "class_aspose_1_1_words_1_1_fields_1_1_field" ],
          [ "FieldAddIn", "class_aspose_1_1_words_1_1_fields_1_1_field_add_in.html", "class_aspose_1_1_words_1_1_fields_1_1_field_add_in" ],
          [ "FieldAddressBlock", "class_aspose_1_1_words_1_1_fields_1_1_field_address_block.html", "class_aspose_1_1_words_1_1_fields_1_1_field_address_block" ],
          [ "FieldAdvance", "class_aspose_1_1_words_1_1_fields_1_1_field_advance.html", "class_aspose_1_1_words_1_1_fields_1_1_field_advance" ],
          [ "FieldArgumentBuilder", "class_aspose_1_1_words_1_1_fields_1_1_field_argument_builder.html", "class_aspose_1_1_words_1_1_fields_1_1_field_argument_builder" ],
          [ "FieldAsk", "class_aspose_1_1_words_1_1_fields_1_1_field_ask.html", "class_aspose_1_1_words_1_1_fields_1_1_field_ask" ],
          [ "FieldAuthor", "class_aspose_1_1_words_1_1_fields_1_1_field_author.html", "class_aspose_1_1_words_1_1_fields_1_1_field_author" ],
          [ "FieldAutoNum", "class_aspose_1_1_words_1_1_fields_1_1_field_auto_num.html", "class_aspose_1_1_words_1_1_fields_1_1_field_auto_num" ],
          [ "FieldAutoNumLgl", "class_aspose_1_1_words_1_1_fields_1_1_field_auto_num_lgl.html", "class_aspose_1_1_words_1_1_fields_1_1_field_auto_num_lgl" ],
          [ "FieldAutoNumOut", "class_aspose_1_1_words_1_1_fields_1_1_field_auto_num_out.html", "class_aspose_1_1_words_1_1_fields_1_1_field_auto_num_out" ],
          [ "FieldAutoText", "class_aspose_1_1_words_1_1_fields_1_1_field_auto_text.html", "class_aspose_1_1_words_1_1_fields_1_1_field_auto_text" ],
          [ "FieldAutoTextList", "class_aspose_1_1_words_1_1_fields_1_1_field_auto_text_list.html", "class_aspose_1_1_words_1_1_fields_1_1_field_auto_text_list" ],
          [ "FieldBarcode", "class_aspose_1_1_words_1_1_fields_1_1_field_barcode.html", "class_aspose_1_1_words_1_1_fields_1_1_field_barcode" ],
          [ "FieldBibliography", "class_aspose_1_1_words_1_1_fields_1_1_field_bibliography.html", "class_aspose_1_1_words_1_1_fields_1_1_field_bibliography" ],
          [ "FieldBidiOutline", "class_aspose_1_1_words_1_1_fields_1_1_field_bidi_outline.html", "class_aspose_1_1_words_1_1_fields_1_1_field_bidi_outline" ],
          [ "FieldBuilder", "class_aspose_1_1_words_1_1_fields_1_1_field_builder.html", "class_aspose_1_1_words_1_1_fields_1_1_field_builder" ],
          [ "FieldChar", "class_aspose_1_1_words_1_1_fields_1_1_field_char.html", "class_aspose_1_1_words_1_1_fields_1_1_field_char" ],
          [ "FieldCitation", "class_aspose_1_1_words_1_1_fields_1_1_field_citation.html", "class_aspose_1_1_words_1_1_fields_1_1_field_citation" ],
          [ "FieldCollection", "class_aspose_1_1_words_1_1_fields_1_1_field_collection.html", "class_aspose_1_1_words_1_1_fields_1_1_field_collection" ],
          [ "FieldComments", "class_aspose_1_1_words_1_1_fields_1_1_field_comments.html", "class_aspose_1_1_words_1_1_fields_1_1_field_comments" ],
          [ "FieldCompare", "class_aspose_1_1_words_1_1_fields_1_1_field_compare.html", "class_aspose_1_1_words_1_1_fields_1_1_field_compare" ],
          [ "FieldCreateDate", "class_aspose_1_1_words_1_1_fields_1_1_field_create_date.html", "class_aspose_1_1_words_1_1_fields_1_1_field_create_date" ],
          [ "FieldData", "class_aspose_1_1_words_1_1_fields_1_1_field_data.html", "class_aspose_1_1_words_1_1_fields_1_1_field_data" ],
          [ "FieldDatabase", "class_aspose_1_1_words_1_1_fields_1_1_field_database.html", "class_aspose_1_1_words_1_1_fields_1_1_field_database" ],
          [ "FieldDate", "class_aspose_1_1_words_1_1_fields_1_1_field_date.html", "class_aspose_1_1_words_1_1_fields_1_1_field_date" ],
          [ "FieldDde", "class_aspose_1_1_words_1_1_fields_1_1_field_dde.html", "class_aspose_1_1_words_1_1_fields_1_1_field_dde" ],
          [ "FieldDdeAuto", "class_aspose_1_1_words_1_1_fields_1_1_field_dde_auto.html", "class_aspose_1_1_words_1_1_fields_1_1_field_dde_auto" ],
          [ "FieldDisplayBarcode", "class_aspose_1_1_words_1_1_fields_1_1_field_display_barcode.html", "class_aspose_1_1_words_1_1_fields_1_1_field_display_barcode" ],
          [ "FieldDocProperty", "class_aspose_1_1_words_1_1_fields_1_1_field_doc_property.html", "class_aspose_1_1_words_1_1_fields_1_1_field_doc_property" ],
          [ "FieldDocVariable", "class_aspose_1_1_words_1_1_fields_1_1_field_doc_variable.html", "class_aspose_1_1_words_1_1_fields_1_1_field_doc_variable" ],
          [ "FieldEditTime", "class_aspose_1_1_words_1_1_fields_1_1_field_edit_time.html", "class_aspose_1_1_words_1_1_fields_1_1_field_edit_time" ],
          [ "FieldEmbed", "class_aspose_1_1_words_1_1_fields_1_1_field_embed.html", "class_aspose_1_1_words_1_1_fields_1_1_field_embed" ],
          [ "FieldEnd", "class_aspose_1_1_words_1_1_fields_1_1_field_end.html", "class_aspose_1_1_words_1_1_fields_1_1_field_end" ],
          [ "FieldEQ", "class_aspose_1_1_words_1_1_fields_1_1_field_e_q.html", "class_aspose_1_1_words_1_1_fields_1_1_field_e_q" ],
          [ "FieldFileName", "class_aspose_1_1_words_1_1_fields_1_1_field_file_name.html", "class_aspose_1_1_words_1_1_fields_1_1_field_file_name" ],
          [ "FieldFileSize", "class_aspose_1_1_words_1_1_fields_1_1_field_file_size.html", "class_aspose_1_1_words_1_1_fields_1_1_field_file_size" ],
          [ "FieldFillIn", "class_aspose_1_1_words_1_1_fields_1_1_field_fill_in.html", "class_aspose_1_1_words_1_1_fields_1_1_field_fill_in" ],
          [ "FieldFootnoteRef", "class_aspose_1_1_words_1_1_fields_1_1_field_footnote_ref.html", "class_aspose_1_1_words_1_1_fields_1_1_field_footnote_ref" ],
          [ "FieldFormat", "class_aspose_1_1_words_1_1_fields_1_1_field_format.html", "class_aspose_1_1_words_1_1_fields_1_1_field_format" ],
          [ "FieldFormCheckBox", "class_aspose_1_1_words_1_1_fields_1_1_field_form_check_box.html", "class_aspose_1_1_words_1_1_fields_1_1_field_form_check_box" ],
          [ "FieldFormDropDown", "class_aspose_1_1_words_1_1_fields_1_1_field_form_drop_down.html", "class_aspose_1_1_words_1_1_fields_1_1_field_form_drop_down" ],
          [ "FieldFormText", "class_aspose_1_1_words_1_1_fields_1_1_field_form_text.html", "class_aspose_1_1_words_1_1_fields_1_1_field_form_text" ],
          [ "FieldFormula", "class_aspose_1_1_words_1_1_fields_1_1_field_formula.html", "class_aspose_1_1_words_1_1_fields_1_1_field_formula" ],
          [ "FieldGlossary", "class_aspose_1_1_words_1_1_fields_1_1_field_glossary.html", "class_aspose_1_1_words_1_1_fields_1_1_field_glossary" ],
          [ "FieldGoToButton", "class_aspose_1_1_words_1_1_fields_1_1_field_go_to_button.html", "class_aspose_1_1_words_1_1_fields_1_1_field_go_to_button" ],
          [ "FieldGreetingLine", "class_aspose_1_1_words_1_1_fields_1_1_field_greeting_line.html", "class_aspose_1_1_words_1_1_fields_1_1_field_greeting_line" ],
          [ "FieldHyperlink", "class_aspose_1_1_words_1_1_fields_1_1_field_hyperlink.html", "class_aspose_1_1_words_1_1_fields_1_1_field_hyperlink" ],
          [ "FieldIf", "class_aspose_1_1_words_1_1_fields_1_1_field_if.html", "class_aspose_1_1_words_1_1_fields_1_1_field_if" ],
          [ "FieldImport", "class_aspose_1_1_words_1_1_fields_1_1_field_import.html", "class_aspose_1_1_words_1_1_fields_1_1_field_import" ],
          [ "FieldInclude", "class_aspose_1_1_words_1_1_fields_1_1_field_include.html", "class_aspose_1_1_words_1_1_fields_1_1_field_include" ],
          [ "FieldIncludePicture", "class_aspose_1_1_words_1_1_fields_1_1_field_include_picture.html", "class_aspose_1_1_words_1_1_fields_1_1_field_include_picture" ],
          [ "FieldIncludeText", "class_aspose_1_1_words_1_1_fields_1_1_field_include_text.html", "class_aspose_1_1_words_1_1_fields_1_1_field_include_text" ],
          [ "FieldIndex", "class_aspose_1_1_words_1_1_fields_1_1_field_index.html", "class_aspose_1_1_words_1_1_fields_1_1_field_index" ],
          [ "FieldInfo", "class_aspose_1_1_words_1_1_fields_1_1_field_info.html", "class_aspose_1_1_words_1_1_fields_1_1_field_info" ],
          [ "FieldKeywords", "class_aspose_1_1_words_1_1_fields_1_1_field_keywords.html", "class_aspose_1_1_words_1_1_fields_1_1_field_keywords" ],
          [ "FieldLastSavedBy", "class_aspose_1_1_words_1_1_fields_1_1_field_last_saved_by.html", "class_aspose_1_1_words_1_1_fields_1_1_field_last_saved_by" ],
          [ "FieldLink", "class_aspose_1_1_words_1_1_fields_1_1_field_link.html", "class_aspose_1_1_words_1_1_fields_1_1_field_link" ],
          [ "FieldListNum", "class_aspose_1_1_words_1_1_fields_1_1_field_list_num.html", "class_aspose_1_1_words_1_1_fields_1_1_field_list_num" ],
          [ "FieldMacroButton", "class_aspose_1_1_words_1_1_fields_1_1_field_macro_button.html", "class_aspose_1_1_words_1_1_fields_1_1_field_macro_button" ],
          [ "FieldMergeBarcode", "class_aspose_1_1_words_1_1_fields_1_1_field_merge_barcode.html", "class_aspose_1_1_words_1_1_fields_1_1_field_merge_barcode" ],
          [ "FieldMergeField", "class_aspose_1_1_words_1_1_fields_1_1_field_merge_field.html", "class_aspose_1_1_words_1_1_fields_1_1_field_merge_field" ],
          [ "FieldMergeRec", "class_aspose_1_1_words_1_1_fields_1_1_field_merge_rec.html", "class_aspose_1_1_words_1_1_fields_1_1_field_merge_rec" ],
          [ "FieldMergeSeq", "class_aspose_1_1_words_1_1_fields_1_1_field_merge_seq.html", "class_aspose_1_1_words_1_1_fields_1_1_field_merge_seq" ],
          [ "FieldNext", "class_aspose_1_1_words_1_1_fields_1_1_field_next.html", "class_aspose_1_1_words_1_1_fields_1_1_field_next" ],
          [ "FieldNextIf", "class_aspose_1_1_words_1_1_fields_1_1_field_next_if.html", "class_aspose_1_1_words_1_1_fields_1_1_field_next_if" ],
          [ "FieldNoteRef", "class_aspose_1_1_words_1_1_fields_1_1_field_note_ref.html", "class_aspose_1_1_words_1_1_fields_1_1_field_note_ref" ],
          [ "FieldNumChars", "class_aspose_1_1_words_1_1_fields_1_1_field_num_chars.html", "class_aspose_1_1_words_1_1_fields_1_1_field_num_chars" ],
          [ "FieldNumPages", "class_aspose_1_1_words_1_1_fields_1_1_field_num_pages.html", "class_aspose_1_1_words_1_1_fields_1_1_field_num_pages" ],
          [ "FieldNumWords", "class_aspose_1_1_words_1_1_fields_1_1_field_num_words.html", "class_aspose_1_1_words_1_1_fields_1_1_field_num_words" ],
          [ "FieldOcx", "class_aspose_1_1_words_1_1_fields_1_1_field_ocx.html", "class_aspose_1_1_words_1_1_fields_1_1_field_ocx" ],
          [ "FieldOptions", "class_aspose_1_1_words_1_1_fields_1_1_field_options.html", "class_aspose_1_1_words_1_1_fields_1_1_field_options" ],
          [ "FieldPage", "class_aspose_1_1_words_1_1_fields_1_1_field_page.html", "class_aspose_1_1_words_1_1_fields_1_1_field_page" ],
          [ "FieldPageRef", "class_aspose_1_1_words_1_1_fields_1_1_field_page_ref.html", "class_aspose_1_1_words_1_1_fields_1_1_field_page_ref" ],
          [ "FieldPrint", "class_aspose_1_1_words_1_1_fields_1_1_field_print.html", "class_aspose_1_1_words_1_1_fields_1_1_field_print" ],
          [ "FieldPrintDate", "class_aspose_1_1_words_1_1_fields_1_1_field_print_date.html", "class_aspose_1_1_words_1_1_fields_1_1_field_print_date" ],
          [ "FieldPrivate", "class_aspose_1_1_words_1_1_fields_1_1_field_private.html", "class_aspose_1_1_words_1_1_fields_1_1_field_private" ],
          [ "FieldQuote", "class_aspose_1_1_words_1_1_fields_1_1_field_quote.html", "class_aspose_1_1_words_1_1_fields_1_1_field_quote" ],
          [ "FieldRD", "class_aspose_1_1_words_1_1_fields_1_1_field_r_d.html", "class_aspose_1_1_words_1_1_fields_1_1_field_r_d" ],
          [ "FieldRef", "class_aspose_1_1_words_1_1_fields_1_1_field_ref.html", "class_aspose_1_1_words_1_1_fields_1_1_field_ref" ],
          [ "FieldRevNum", "class_aspose_1_1_words_1_1_fields_1_1_field_rev_num.html", "class_aspose_1_1_words_1_1_fields_1_1_field_rev_num" ],
          [ "FieldSaveDate", "class_aspose_1_1_words_1_1_fields_1_1_field_save_date.html", "class_aspose_1_1_words_1_1_fields_1_1_field_save_date" ],
          [ "FieldSection", "class_aspose_1_1_words_1_1_fields_1_1_field_section.html", "class_aspose_1_1_words_1_1_fields_1_1_field_section" ],
          [ "FieldSectionPages", "class_aspose_1_1_words_1_1_fields_1_1_field_section_pages.html", "class_aspose_1_1_words_1_1_fields_1_1_field_section_pages" ],
          [ "FieldSeparator", "class_aspose_1_1_words_1_1_fields_1_1_field_separator.html", "class_aspose_1_1_words_1_1_fields_1_1_field_separator" ],
          [ "FieldSeq", "class_aspose_1_1_words_1_1_fields_1_1_field_seq.html", "class_aspose_1_1_words_1_1_fields_1_1_field_seq" ],
          [ "FieldSet", "class_aspose_1_1_words_1_1_fields_1_1_field_set.html", "class_aspose_1_1_words_1_1_fields_1_1_field_set" ],
          [ "FieldShape", "class_aspose_1_1_words_1_1_fields_1_1_field_shape.html", "class_aspose_1_1_words_1_1_fields_1_1_field_shape" ],
          [ "FieldSkipIf", "class_aspose_1_1_words_1_1_fields_1_1_field_skip_if.html", "class_aspose_1_1_words_1_1_fields_1_1_field_skip_if" ],
          [ "FieldStart", "class_aspose_1_1_words_1_1_fields_1_1_field_start.html", "class_aspose_1_1_words_1_1_fields_1_1_field_start" ],
          [ "FieldStyleRef", "class_aspose_1_1_words_1_1_fields_1_1_field_style_ref.html", "class_aspose_1_1_words_1_1_fields_1_1_field_style_ref" ],
          [ "FieldSubject", "class_aspose_1_1_words_1_1_fields_1_1_field_subject.html", "class_aspose_1_1_words_1_1_fields_1_1_field_subject" ],
          [ "FieldSymbol", "class_aspose_1_1_words_1_1_fields_1_1_field_symbol.html", "class_aspose_1_1_words_1_1_fields_1_1_field_symbol" ],
          [ "FieldTA", "class_aspose_1_1_words_1_1_fields_1_1_field_t_a.html", "class_aspose_1_1_words_1_1_fields_1_1_field_t_a" ],
          [ "FieldTC", "class_aspose_1_1_words_1_1_fields_1_1_field_t_c.html", "class_aspose_1_1_words_1_1_fields_1_1_field_t_c" ],
          [ "FieldTemplate", "class_aspose_1_1_words_1_1_fields_1_1_field_template.html", "class_aspose_1_1_words_1_1_fields_1_1_field_template" ],
          [ "FieldTime", "class_aspose_1_1_words_1_1_fields_1_1_field_time.html", "class_aspose_1_1_words_1_1_fields_1_1_field_time" ],
          [ "FieldTitle", "class_aspose_1_1_words_1_1_fields_1_1_field_title.html", "class_aspose_1_1_words_1_1_fields_1_1_field_title" ],
          [ "FieldToa", "class_aspose_1_1_words_1_1_fields_1_1_field_toa.html", "class_aspose_1_1_words_1_1_fields_1_1_field_toa" ],
          [ "FieldToc", "class_aspose_1_1_words_1_1_fields_1_1_field_toc.html", "class_aspose_1_1_words_1_1_fields_1_1_field_toc" ],
          [ "FieldUnknown", "class_aspose_1_1_words_1_1_fields_1_1_field_unknown.html", "class_aspose_1_1_words_1_1_fields_1_1_field_unknown" ],
          [ "FieldUserAddress", "class_aspose_1_1_words_1_1_fields_1_1_field_user_address.html", "class_aspose_1_1_words_1_1_fields_1_1_field_user_address" ],
          [ "FieldUserInitials", "class_aspose_1_1_words_1_1_fields_1_1_field_user_initials.html", "class_aspose_1_1_words_1_1_fields_1_1_field_user_initials" ],
          [ "FieldUserName", "class_aspose_1_1_words_1_1_fields_1_1_field_user_name.html", "class_aspose_1_1_words_1_1_fields_1_1_field_user_name" ],
          [ "FieldXE", "class_aspose_1_1_words_1_1_fields_1_1_field_x_e.html", "class_aspose_1_1_words_1_1_fields_1_1_field_x_e" ],
          [ "FormField", "class_aspose_1_1_words_1_1_fields_1_1_form_field.html", "class_aspose_1_1_words_1_1_fields_1_1_form_field" ],
          [ "FormFieldCollection", "class_aspose_1_1_words_1_1_fields_1_1_form_field_collection.html", "class_aspose_1_1_words_1_1_fields_1_1_form_field_collection" ],
          [ "GeneralFormatCollection", "class_aspose_1_1_words_1_1_fields_1_1_general_format_collection.html", "class_aspose_1_1_words_1_1_fields_1_1_general_format_collection" ],
          [ "IBarcodeGenerator", "class_aspose_1_1_words_1_1_fields_1_1_i_barcode_generator.html", "class_aspose_1_1_words_1_1_fields_1_1_i_barcode_generator" ],
          [ "IComparisonExpressionEvaluator", "class_aspose_1_1_words_1_1_fields_1_1_i_comparison_expression_evaluator.html", "class_aspose_1_1_words_1_1_fields_1_1_i_comparison_expression_evaluator" ],
          [ "IFieldResultFormatter", "class_aspose_1_1_words_1_1_fields_1_1_i_field_result_formatter.html", "class_aspose_1_1_words_1_1_fields_1_1_i_field_result_formatter" ],
          [ "IFieldUpdateCultureProvider", "class_aspose_1_1_words_1_1_fields_1_1_i_field_update_culture_provider.html", "class_aspose_1_1_words_1_1_fields_1_1_i_field_update_culture_provider" ],
          [ "IFieldUpdatingCallback", "class_aspose_1_1_words_1_1_fields_1_1_i_field_updating_callback.html", "class_aspose_1_1_words_1_1_fields_1_1_i_field_updating_callback" ],
          [ "IFieldUserPromptRespondent", "class_aspose_1_1_words_1_1_fields_1_1_i_field_user_prompt_respondent.html", "class_aspose_1_1_words_1_1_fields_1_1_i_field_user_prompt_respondent" ],
          [ "MergeFieldImageDimension", "class_aspose_1_1_words_1_1_fields_1_1_merge_field_image_dimension.html", "class_aspose_1_1_words_1_1_fields_1_1_merge_field_image_dimension" ],
          [ "ToaCategories", "class_aspose_1_1_words_1_1_fields_1_1_toa_categories.html", "class_aspose_1_1_words_1_1_fields_1_1_toa_categories" ],
          [ "UserInformation", "class_aspose_1_1_words_1_1_fields_1_1_user_information.html", "class_aspose_1_1_words_1_1_fields_1_1_user_information" ]
        ] ],
        [ "Fonts", "namespace_aspose_1_1_words_1_1_fonts.html", [
          [ "DefaultFontSubstitutionRule", "class_aspose_1_1_words_1_1_fonts_1_1_default_font_substitution_rule.html", "class_aspose_1_1_words_1_1_fonts_1_1_default_font_substitution_rule" ],
          [ "FileFontSource", "class_aspose_1_1_words_1_1_fonts_1_1_file_font_source.html", "class_aspose_1_1_words_1_1_fonts_1_1_file_font_source" ],
          [ "FolderFontSource", "class_aspose_1_1_words_1_1_fonts_1_1_folder_font_source.html", "class_aspose_1_1_words_1_1_fonts_1_1_folder_font_source" ],
          [ "FontConfigSubstitutionRule", "class_aspose_1_1_words_1_1_fonts_1_1_font_config_substitution_rule.html", "class_aspose_1_1_words_1_1_fonts_1_1_font_config_substitution_rule" ],
          [ "FontFallbackSettings", "class_aspose_1_1_words_1_1_fonts_1_1_font_fallback_settings.html", "class_aspose_1_1_words_1_1_fonts_1_1_font_fallback_settings" ],
          [ "FontInfo", "class_aspose_1_1_words_1_1_fonts_1_1_font_info.html", "class_aspose_1_1_words_1_1_fonts_1_1_font_info" ],
          [ "FontInfoCollection", "class_aspose_1_1_words_1_1_fonts_1_1_font_info_collection.html", "class_aspose_1_1_words_1_1_fonts_1_1_font_info_collection" ],
          [ "FontInfoSubstitutionRule", "class_aspose_1_1_words_1_1_fonts_1_1_font_info_substitution_rule.html", "class_aspose_1_1_words_1_1_fonts_1_1_font_info_substitution_rule" ],
          [ "FontNameSubstitutionRule", "class_aspose_1_1_words_1_1_fonts_1_1_font_name_substitution_rule.html", "class_aspose_1_1_words_1_1_fonts_1_1_font_name_substitution_rule" ],
          [ "FontSettings", "class_aspose_1_1_words_1_1_fonts_1_1_font_settings.html", "class_aspose_1_1_words_1_1_fonts_1_1_font_settings" ],
          [ "FontSourceBase", "class_aspose_1_1_words_1_1_fonts_1_1_font_source_base.html", "class_aspose_1_1_words_1_1_fonts_1_1_font_source_base" ],
          [ "FontSubstitutionRule", "class_aspose_1_1_words_1_1_fonts_1_1_font_substitution_rule.html", "class_aspose_1_1_words_1_1_fonts_1_1_font_substitution_rule" ],
          [ "FontSubstitutionSettings", "class_aspose_1_1_words_1_1_fonts_1_1_font_substitution_settings.html", "class_aspose_1_1_words_1_1_fonts_1_1_font_substitution_settings" ],
          [ "MemoryFontSource", "class_aspose_1_1_words_1_1_fonts_1_1_memory_font_source.html", "class_aspose_1_1_words_1_1_fonts_1_1_memory_font_source" ],
          [ "PhysicalFontInfo", "class_aspose_1_1_words_1_1_fonts_1_1_physical_font_info.html", "class_aspose_1_1_words_1_1_fonts_1_1_physical_font_info" ],
          [ "StreamFontSource", "class_aspose_1_1_words_1_1_fonts_1_1_stream_font_source.html", "class_aspose_1_1_words_1_1_fonts_1_1_stream_font_source" ],
          [ "SystemFontSource", "class_aspose_1_1_words_1_1_fonts_1_1_system_font_source.html", "class_aspose_1_1_words_1_1_fonts_1_1_system_font_source" ],
          [ "TableSubstitutionRule", "class_aspose_1_1_words_1_1_fonts_1_1_table_substitution_rule.html", "class_aspose_1_1_words_1_1_fonts_1_1_table_substitution_rule" ]
        ] ],
        [ "Framesets", "namespace_aspose_1_1_words_1_1_framesets.html", [
          [ "Frameset", "class_aspose_1_1_words_1_1_framesets_1_1_frameset.html", "class_aspose_1_1_words_1_1_framesets_1_1_frameset" ],
          [ "FramesetCollection", "class_aspose_1_1_words_1_1_framesets_1_1_frameset_collection.html", "class_aspose_1_1_words_1_1_framesets_1_1_frameset_collection" ]
        ] ],
        [ "Layout", "namespace_aspose_1_1_words_1_1_layout.html", [
          [ "IPageLayoutCallback", "class_aspose_1_1_words_1_1_layout_1_1_i_page_layout_callback.html", "class_aspose_1_1_words_1_1_layout_1_1_i_page_layout_callback" ],
          [ "LayoutCollector", "class_aspose_1_1_words_1_1_layout_1_1_layout_collector.html", "class_aspose_1_1_words_1_1_layout_1_1_layout_collector" ],
          [ "LayoutEnumerator", "class_aspose_1_1_words_1_1_layout_1_1_layout_enumerator.html", "class_aspose_1_1_words_1_1_layout_1_1_layout_enumerator" ],
          [ "LayoutOptions", "class_aspose_1_1_words_1_1_layout_1_1_layout_options.html", "class_aspose_1_1_words_1_1_layout_1_1_layout_options" ],
          [ "PageLayoutCallbackArgs", "class_aspose_1_1_words_1_1_layout_1_1_page_layout_callback_args.html", "class_aspose_1_1_words_1_1_layout_1_1_page_layout_callback_args" ],
          [ "RevisionOptions", "class_aspose_1_1_words_1_1_layout_1_1_revision_options.html", "class_aspose_1_1_words_1_1_layout_1_1_revision_options" ]
        ] ],
        [ "Lists", "namespace_aspose_1_1_words_1_1_lists.html", [
          [ "List", "class_aspose_1_1_words_1_1_lists_1_1_list.html", "class_aspose_1_1_words_1_1_lists_1_1_list" ],
          [ "ListCollection", "class_aspose_1_1_words_1_1_lists_1_1_list_collection.html", "class_aspose_1_1_words_1_1_lists_1_1_list_collection" ],
          [ "ListFormat", "class_aspose_1_1_words_1_1_lists_1_1_list_format.html", "class_aspose_1_1_words_1_1_lists_1_1_list_format" ],
          [ "ListLabel", "class_aspose_1_1_words_1_1_lists_1_1_list_label.html", "class_aspose_1_1_words_1_1_lists_1_1_list_label" ],
          [ "ListLevel", "class_aspose_1_1_words_1_1_lists_1_1_list_level.html", "class_aspose_1_1_words_1_1_lists_1_1_list_level" ],
          [ "ListLevelCollection", "class_aspose_1_1_words_1_1_lists_1_1_list_level_collection.html", "class_aspose_1_1_words_1_1_lists_1_1_list_level_collection" ]
        ] ],
        [ "Loading", "namespace_aspose_1_1_words_1_1_loading.html", [
          [ "ChmLoadOptions", "class_aspose_1_1_words_1_1_loading_1_1_chm_load_options.html", "class_aspose_1_1_words_1_1_loading_1_1_chm_load_options" ],
          [ "DocumentLoadingArgs", "class_aspose_1_1_words_1_1_loading_1_1_document_loading_args.html", "class_aspose_1_1_words_1_1_loading_1_1_document_loading_args" ],
          [ "HtmlLoadOptions", "class_aspose_1_1_words_1_1_loading_1_1_html_load_options.html", "class_aspose_1_1_words_1_1_loading_1_1_html_load_options" ],
          [ "IDocumentLoadingCallback", "class_aspose_1_1_words_1_1_loading_1_1_i_document_loading_callback.html", "class_aspose_1_1_words_1_1_loading_1_1_i_document_loading_callback" ],
          [ "IResourceLoadingCallback", "class_aspose_1_1_words_1_1_loading_1_1_i_resource_loading_callback.html", "class_aspose_1_1_words_1_1_loading_1_1_i_resource_loading_callback" ],
          [ "LanguagePreferences", "class_aspose_1_1_words_1_1_loading_1_1_language_preferences.html", "class_aspose_1_1_words_1_1_loading_1_1_language_preferences" ],
          [ "LoadOptions", "class_aspose_1_1_words_1_1_loading_1_1_load_options.html", "class_aspose_1_1_words_1_1_loading_1_1_load_options" ],
          [ "PdfLoadOptions", "class_aspose_1_1_words_1_1_loading_1_1_pdf_load_options.html", "class_aspose_1_1_words_1_1_loading_1_1_pdf_load_options" ],
          [ "ResourceLoadingArgs", "class_aspose_1_1_words_1_1_loading_1_1_resource_loading_args.html", "class_aspose_1_1_words_1_1_loading_1_1_resource_loading_args" ],
          [ "RtfLoadOptions", "class_aspose_1_1_words_1_1_loading_1_1_rtf_load_options.html", "class_aspose_1_1_words_1_1_loading_1_1_rtf_load_options" ],
          [ "TxtLoadOptions", "class_aspose_1_1_words_1_1_loading_1_1_txt_load_options.html", "class_aspose_1_1_words_1_1_loading_1_1_txt_load_options" ]
        ] ],
        [ "MailMerging", "namespace_aspose_1_1_words_1_1_mail_merging.html", [
          [ "FieldMergingArgs", "class_aspose_1_1_words_1_1_mail_merging_1_1_field_merging_args.html", "class_aspose_1_1_words_1_1_mail_merging_1_1_field_merging_args" ],
          [ "FieldMergingArgsBase", "class_aspose_1_1_words_1_1_mail_merging_1_1_field_merging_args_base.html", "class_aspose_1_1_words_1_1_mail_merging_1_1_field_merging_args_base" ],
          [ "IFieldMergingCallback", "class_aspose_1_1_words_1_1_mail_merging_1_1_i_field_merging_callback.html", "class_aspose_1_1_words_1_1_mail_merging_1_1_i_field_merging_callback" ],
          [ "ImageFieldMergingArgs", "class_aspose_1_1_words_1_1_mail_merging_1_1_image_field_merging_args.html", "class_aspose_1_1_words_1_1_mail_merging_1_1_image_field_merging_args" ],
          [ "IMailMergeCallback", "class_aspose_1_1_words_1_1_mail_merging_1_1_i_mail_merge_callback.html", "class_aspose_1_1_words_1_1_mail_merging_1_1_i_mail_merge_callback" ],
          [ "IMailMergeDataSource", "class_aspose_1_1_words_1_1_mail_merging_1_1_i_mail_merge_data_source.html", "class_aspose_1_1_words_1_1_mail_merging_1_1_i_mail_merge_data_source" ],
          [ "IMailMergeDataSourceRoot", "class_aspose_1_1_words_1_1_mail_merging_1_1_i_mail_merge_data_source_root.html", "class_aspose_1_1_words_1_1_mail_merging_1_1_i_mail_merge_data_source_root" ],
          [ "MailMerge", "class_aspose_1_1_words_1_1_mail_merging_1_1_mail_merge.html", "class_aspose_1_1_words_1_1_mail_merging_1_1_mail_merge" ],
          [ "MailMergeRegionInfo", "class_aspose_1_1_words_1_1_mail_merging_1_1_mail_merge_region_info.html", "class_aspose_1_1_words_1_1_mail_merging_1_1_mail_merge_region_info" ],
          [ "MappedDataFieldCollection", "class_aspose_1_1_words_1_1_mail_merging_1_1_mapped_data_field_collection.html", "class_aspose_1_1_words_1_1_mail_merging_1_1_mapped_data_field_collection" ]
        ] ],
        [ "Markup", "namespace_aspose_1_1_words_1_1_markup.html", [
          [ "CustomPart", "class_aspose_1_1_words_1_1_markup_1_1_custom_part.html", "class_aspose_1_1_words_1_1_markup_1_1_custom_part" ],
          [ "CustomPartCollection", "class_aspose_1_1_words_1_1_markup_1_1_custom_part_collection.html", "class_aspose_1_1_words_1_1_markup_1_1_custom_part_collection" ],
          [ "CustomXmlPart", "class_aspose_1_1_words_1_1_markup_1_1_custom_xml_part.html", "class_aspose_1_1_words_1_1_markup_1_1_custom_xml_part" ],
          [ "CustomXmlPartCollection", "class_aspose_1_1_words_1_1_markup_1_1_custom_xml_part_collection.html", "class_aspose_1_1_words_1_1_markup_1_1_custom_xml_part_collection" ],
          [ "CustomXmlProperty", "class_aspose_1_1_words_1_1_markup_1_1_custom_xml_property.html", "class_aspose_1_1_words_1_1_markup_1_1_custom_xml_property" ],
          [ "CustomXmlPropertyCollection", "class_aspose_1_1_words_1_1_markup_1_1_custom_xml_property_collection.html", "class_aspose_1_1_words_1_1_markup_1_1_custom_xml_property_collection" ],
          [ "CustomXmlSchemaCollection", "class_aspose_1_1_words_1_1_markup_1_1_custom_xml_schema_collection.html", "class_aspose_1_1_words_1_1_markup_1_1_custom_xml_schema_collection" ],
          [ "SdtListItem", "class_aspose_1_1_words_1_1_markup_1_1_sdt_list_item.html", "class_aspose_1_1_words_1_1_markup_1_1_sdt_list_item" ],
          [ "SdtListItemCollection", "class_aspose_1_1_words_1_1_markup_1_1_sdt_list_item_collection.html", "class_aspose_1_1_words_1_1_markup_1_1_sdt_list_item_collection" ],
          [ "SmartTag", "class_aspose_1_1_words_1_1_markup_1_1_smart_tag.html", "class_aspose_1_1_words_1_1_markup_1_1_smart_tag" ],
          [ "StructuredDocumentTag", "class_aspose_1_1_words_1_1_markup_1_1_structured_document_tag.html", "class_aspose_1_1_words_1_1_markup_1_1_structured_document_tag" ],
          [ "StructuredDocumentTagRangeEnd", "class_aspose_1_1_words_1_1_markup_1_1_structured_document_tag_range_end.html", "class_aspose_1_1_words_1_1_markup_1_1_structured_document_tag_range_end" ],
          [ "StructuredDocumentTagRangeStart", "class_aspose_1_1_words_1_1_markup_1_1_structured_document_tag_range_start.html", "class_aspose_1_1_words_1_1_markup_1_1_structured_document_tag_range_start" ],
          [ "XmlMapping", "class_aspose_1_1_words_1_1_markup_1_1_xml_mapping.html", "class_aspose_1_1_words_1_1_markup_1_1_xml_mapping" ]
        ] ],
        [ "Math", "namespace_aspose_1_1_words_1_1_math.html", [
          [ "OfficeMath", "class_aspose_1_1_words_1_1_math_1_1_office_math.html", "class_aspose_1_1_words_1_1_math_1_1_office_math" ]
        ] ],
        [ "Notes", "namespace_aspose_1_1_words_1_1_notes.html", [
          [ "EndnoteOptions", "class_aspose_1_1_words_1_1_notes_1_1_endnote_options.html", "class_aspose_1_1_words_1_1_notes_1_1_endnote_options" ],
          [ "Footnote", "class_aspose_1_1_words_1_1_notes_1_1_footnote.html", "class_aspose_1_1_words_1_1_notes_1_1_footnote" ],
          [ "FootnoteOptions", "class_aspose_1_1_words_1_1_notes_1_1_footnote_options.html", "class_aspose_1_1_words_1_1_notes_1_1_footnote_options" ]
        ] ],
        [ "Properties", "namespace_aspose_1_1_words_1_1_properties.html", [
          [ "BuiltInDocumentProperties", "class_aspose_1_1_words_1_1_properties_1_1_built_in_document_properties.html", "class_aspose_1_1_words_1_1_properties_1_1_built_in_document_properties" ],
          [ "CustomDocumentProperties", "class_aspose_1_1_words_1_1_properties_1_1_custom_document_properties.html", "class_aspose_1_1_words_1_1_properties_1_1_custom_document_properties" ],
          [ "DocumentProperty", "class_aspose_1_1_words_1_1_properties_1_1_document_property.html", "class_aspose_1_1_words_1_1_properties_1_1_document_property" ],
          [ "DocumentPropertyCollection", "class_aspose_1_1_words_1_1_properties_1_1_document_property_collection.html", "class_aspose_1_1_words_1_1_properties_1_1_document_property_collection" ]
        ] ],
        [ "Rendering", "namespace_aspose_1_1_words_1_1_rendering.html", [
          [ "NodeRendererBase", "class_aspose_1_1_words_1_1_rendering_1_1_node_renderer_base.html", "class_aspose_1_1_words_1_1_rendering_1_1_node_renderer_base" ],
          [ "OfficeMathRenderer", "class_aspose_1_1_words_1_1_rendering_1_1_office_math_renderer.html", "class_aspose_1_1_words_1_1_rendering_1_1_office_math_renderer" ],
          [ "PageInfo", "class_aspose_1_1_words_1_1_rendering_1_1_page_info.html", "class_aspose_1_1_words_1_1_rendering_1_1_page_info" ],
          [ "ShapeRenderer", "class_aspose_1_1_words_1_1_rendering_1_1_shape_renderer.html", "class_aspose_1_1_words_1_1_rendering_1_1_shape_renderer" ],
          [ "ThumbnailGeneratingOptions", "class_aspose_1_1_words_1_1_rendering_1_1_thumbnail_generating_options.html", "class_aspose_1_1_words_1_1_rendering_1_1_thumbnail_generating_options" ]
        ] ],
        [ "Replacing", "namespace_aspose_1_1_words_1_1_replacing.html", [
          [ "FindReplaceOptions", "class_aspose_1_1_words_1_1_replacing_1_1_find_replace_options.html", "class_aspose_1_1_words_1_1_replacing_1_1_find_replace_options" ],
          [ "IReplacingCallback", "class_aspose_1_1_words_1_1_replacing_1_1_i_replacing_callback.html", "class_aspose_1_1_words_1_1_replacing_1_1_i_replacing_callback" ],
          [ "ReplacingArgs", "class_aspose_1_1_words_1_1_replacing_1_1_replacing_args.html", "class_aspose_1_1_words_1_1_replacing_1_1_replacing_args" ]
        ] ],
        [ "Saving", "namespace_aspose_1_1_words_1_1_saving.html", [
          [ "BookmarksOutlineLevelCollection", "class_aspose_1_1_words_1_1_saving_1_1_bookmarks_outline_level_collection.html", "class_aspose_1_1_words_1_1_saving_1_1_bookmarks_outline_level_collection" ],
          [ "CssSavingArgs", "class_aspose_1_1_words_1_1_saving_1_1_css_saving_args.html", "class_aspose_1_1_words_1_1_saving_1_1_css_saving_args" ],
          [ "DocSaveOptions", "class_aspose_1_1_words_1_1_saving_1_1_doc_save_options.html", "class_aspose_1_1_words_1_1_saving_1_1_doc_save_options" ],
          [ "DocumentPartSavingArgs", "class_aspose_1_1_words_1_1_saving_1_1_document_part_saving_args.html", "class_aspose_1_1_words_1_1_saving_1_1_document_part_saving_args" ],
          [ "DownsampleOptions", "class_aspose_1_1_words_1_1_saving_1_1_downsample_options.html", "class_aspose_1_1_words_1_1_saving_1_1_downsample_options" ],
          [ "FixedPageSaveOptions", "class_aspose_1_1_words_1_1_saving_1_1_fixed_page_save_options.html", "class_aspose_1_1_words_1_1_saving_1_1_fixed_page_save_options" ],
          [ "FontSavingArgs", "class_aspose_1_1_words_1_1_saving_1_1_font_saving_args.html", "class_aspose_1_1_words_1_1_saving_1_1_font_saving_args" ],
          [ "HtmlFixedSaveOptions", "class_aspose_1_1_words_1_1_saving_1_1_html_fixed_save_options.html", "class_aspose_1_1_words_1_1_saving_1_1_html_fixed_save_options" ],
          [ "HtmlSaveOptions", "class_aspose_1_1_words_1_1_saving_1_1_html_save_options.html", "class_aspose_1_1_words_1_1_saving_1_1_html_save_options" ],
          [ "ICssSavingCallback", "class_aspose_1_1_words_1_1_saving_1_1_i_css_saving_callback.html", "class_aspose_1_1_words_1_1_saving_1_1_i_css_saving_callback" ],
          [ "IDocumentPartSavingCallback", "class_aspose_1_1_words_1_1_saving_1_1_i_document_part_saving_callback.html", "class_aspose_1_1_words_1_1_saving_1_1_i_document_part_saving_callback" ],
          [ "IFontSavingCallback", "class_aspose_1_1_words_1_1_saving_1_1_i_font_saving_callback.html", "class_aspose_1_1_words_1_1_saving_1_1_i_font_saving_callback" ],
          [ "IImageSavingCallback", "class_aspose_1_1_words_1_1_saving_1_1_i_image_saving_callback.html", "class_aspose_1_1_words_1_1_saving_1_1_i_image_saving_callback" ],
          [ "ImageSaveOptions", "class_aspose_1_1_words_1_1_saving_1_1_image_save_options.html", "class_aspose_1_1_words_1_1_saving_1_1_image_save_options" ],
          [ "ImageSavingArgs", "class_aspose_1_1_words_1_1_saving_1_1_image_saving_args.html", "class_aspose_1_1_words_1_1_saving_1_1_image_saving_args" ],
          [ "IPageSavingCallback", "class_aspose_1_1_words_1_1_saving_1_1_i_page_saving_callback.html", "class_aspose_1_1_words_1_1_saving_1_1_i_page_saving_callback" ],
          [ "IResourceSavingCallback", "class_aspose_1_1_words_1_1_saving_1_1_i_resource_saving_callback.html", "class_aspose_1_1_words_1_1_saving_1_1_i_resource_saving_callback" ],
          [ "MarkdownSaveOptions", "class_aspose_1_1_words_1_1_saving_1_1_markdown_save_options.html", "class_aspose_1_1_words_1_1_saving_1_1_markdown_save_options" ],
          [ "MetafileRenderingOptions", "class_aspose_1_1_words_1_1_saving_1_1_metafile_rendering_options.html", "class_aspose_1_1_words_1_1_saving_1_1_metafile_rendering_options" ],
          [ "OdtSaveOptions", "class_aspose_1_1_words_1_1_saving_1_1_odt_save_options.html", "class_aspose_1_1_words_1_1_saving_1_1_odt_save_options" ],
          [ "OoxmlSaveOptions", "class_aspose_1_1_words_1_1_saving_1_1_ooxml_save_options.html", "class_aspose_1_1_words_1_1_saving_1_1_ooxml_save_options" ],
          [ "OutlineOptions", "class_aspose_1_1_words_1_1_saving_1_1_outline_options.html", "class_aspose_1_1_words_1_1_saving_1_1_outline_options" ],
          [ "PageRange", "class_aspose_1_1_words_1_1_saving_1_1_page_range.html", "class_aspose_1_1_words_1_1_saving_1_1_page_range" ],
          [ "PageSavingArgs", "class_aspose_1_1_words_1_1_saving_1_1_page_saving_args.html", "class_aspose_1_1_words_1_1_saving_1_1_page_saving_args" ],
          [ "PageSet", "class_aspose_1_1_words_1_1_saving_1_1_page_set.html", "class_aspose_1_1_words_1_1_saving_1_1_page_set" ],
          [ "PclSaveOptions", "class_aspose_1_1_words_1_1_saving_1_1_pcl_save_options.html", "class_aspose_1_1_words_1_1_saving_1_1_pcl_save_options" ],
          [ "PdfDigitalSignatureDetails", "class_aspose_1_1_words_1_1_saving_1_1_pdf_digital_signature_details.html", "class_aspose_1_1_words_1_1_saving_1_1_pdf_digital_signature_details" ],
          [ "PdfDigitalSignatureTimestampSettings", "class_aspose_1_1_words_1_1_saving_1_1_pdf_digital_signature_timestamp_settings.html", "class_aspose_1_1_words_1_1_saving_1_1_pdf_digital_signature_timestamp_settings" ],
          [ "PdfEncryptionDetails", "class_aspose_1_1_words_1_1_saving_1_1_pdf_encryption_details.html", "class_aspose_1_1_words_1_1_saving_1_1_pdf_encryption_details" ],
          [ "PdfSaveOptions", "class_aspose_1_1_words_1_1_saving_1_1_pdf_save_options.html", "class_aspose_1_1_words_1_1_saving_1_1_pdf_save_options" ],
          [ "PsSaveOptions", "class_aspose_1_1_words_1_1_saving_1_1_ps_save_options.html", "class_aspose_1_1_words_1_1_saving_1_1_ps_save_options" ],
          [ "ResourceSavingArgs", "class_aspose_1_1_words_1_1_saving_1_1_resource_saving_args.html", "class_aspose_1_1_words_1_1_saving_1_1_resource_saving_args" ],
          [ "RtfSaveOptions", "class_aspose_1_1_words_1_1_saving_1_1_rtf_save_options.html", "class_aspose_1_1_words_1_1_saving_1_1_rtf_save_options" ],
          [ "SaveOptions", "class_aspose_1_1_words_1_1_saving_1_1_save_options.html", "class_aspose_1_1_words_1_1_saving_1_1_save_options" ],
          [ "SaveOutputParameters", "class_aspose_1_1_words_1_1_saving_1_1_save_output_parameters.html", "class_aspose_1_1_words_1_1_saving_1_1_save_output_parameters" ],
          [ "SvgSaveOptions", "class_aspose_1_1_words_1_1_saving_1_1_svg_save_options.html", "class_aspose_1_1_words_1_1_saving_1_1_svg_save_options" ],
          [ "TxtListIndentation", "class_aspose_1_1_words_1_1_saving_1_1_txt_list_indentation.html", "class_aspose_1_1_words_1_1_saving_1_1_txt_list_indentation" ],
          [ "TxtSaveOptions", "class_aspose_1_1_words_1_1_saving_1_1_txt_save_options.html", "class_aspose_1_1_words_1_1_saving_1_1_txt_save_options" ],
          [ "TxtSaveOptionsBase", "class_aspose_1_1_words_1_1_saving_1_1_txt_save_options_base.html", "class_aspose_1_1_words_1_1_saving_1_1_txt_save_options_base" ],
          [ "WordML2003SaveOptions", "class_aspose_1_1_words_1_1_saving_1_1_word_m_l2003_save_options.html", "class_aspose_1_1_words_1_1_saving_1_1_word_m_l2003_save_options" ],
          [ "XamlFixedSaveOptions", "class_aspose_1_1_words_1_1_saving_1_1_xaml_fixed_save_options.html", "class_aspose_1_1_words_1_1_saving_1_1_xaml_fixed_save_options" ],
          [ "XamlFlowSaveOptions", "class_aspose_1_1_words_1_1_saving_1_1_xaml_flow_save_options.html", "class_aspose_1_1_words_1_1_saving_1_1_xaml_flow_save_options" ],
          [ "XpsSaveOptions", "class_aspose_1_1_words_1_1_saving_1_1_xps_save_options.html", "class_aspose_1_1_words_1_1_saving_1_1_xps_save_options" ]
        ] ],
        [ "Settings", "namespace_aspose_1_1_words_1_1_settings.html", [
          [ "CompatibilityOptions", "class_aspose_1_1_words_1_1_settings_1_1_compatibility_options.html", "class_aspose_1_1_words_1_1_settings_1_1_compatibility_options" ],
          [ "HyphenationOptions", "class_aspose_1_1_words_1_1_settings_1_1_hyphenation_options.html", "class_aspose_1_1_words_1_1_settings_1_1_hyphenation_options" ],
          [ "MailMergeSettings", "class_aspose_1_1_words_1_1_settings_1_1_mail_merge_settings.html", "class_aspose_1_1_words_1_1_settings_1_1_mail_merge_settings" ],
          [ "Odso", "class_aspose_1_1_words_1_1_settings_1_1_odso.html", "class_aspose_1_1_words_1_1_settings_1_1_odso" ],
          [ "OdsoFieldMapData", "class_aspose_1_1_words_1_1_settings_1_1_odso_field_map_data.html", "class_aspose_1_1_words_1_1_settings_1_1_odso_field_map_data" ],
          [ "OdsoFieldMapDataCollection", "class_aspose_1_1_words_1_1_settings_1_1_odso_field_map_data_collection.html", "class_aspose_1_1_words_1_1_settings_1_1_odso_field_map_data_collection" ],
          [ "OdsoRecipientData", "class_aspose_1_1_words_1_1_settings_1_1_odso_recipient_data.html", "class_aspose_1_1_words_1_1_settings_1_1_odso_recipient_data" ],
          [ "OdsoRecipientDataCollection", "class_aspose_1_1_words_1_1_settings_1_1_odso_recipient_data_collection.html", "class_aspose_1_1_words_1_1_settings_1_1_odso_recipient_data_collection" ],
          [ "ViewOptions", "class_aspose_1_1_words_1_1_settings_1_1_view_options.html", "class_aspose_1_1_words_1_1_settings_1_1_view_options" ],
          [ "WriteProtection", "class_aspose_1_1_words_1_1_settings_1_1_write_protection.html", "class_aspose_1_1_words_1_1_settings_1_1_write_protection" ]
        ] ],
        [ "Tables", "namespace_aspose_1_1_words_1_1_tables.html", [
          [ "Cell", "class_aspose_1_1_words_1_1_tables_1_1_cell.html", "class_aspose_1_1_words_1_1_tables_1_1_cell" ],
          [ "CellCollection", "class_aspose_1_1_words_1_1_tables_1_1_cell_collection.html", "class_aspose_1_1_words_1_1_tables_1_1_cell_collection" ],
          [ "CellFormat", "class_aspose_1_1_words_1_1_tables_1_1_cell_format.html", "class_aspose_1_1_words_1_1_tables_1_1_cell_format" ],
          [ "PreferredWidth", "class_aspose_1_1_words_1_1_tables_1_1_preferred_width.html", "class_aspose_1_1_words_1_1_tables_1_1_preferred_width" ],
          [ "Row", "class_aspose_1_1_words_1_1_tables_1_1_row.html", "class_aspose_1_1_words_1_1_tables_1_1_row" ],
          [ "RowCollection", "class_aspose_1_1_words_1_1_tables_1_1_row_collection.html", "class_aspose_1_1_words_1_1_tables_1_1_row_collection" ],
          [ "RowFormat", "class_aspose_1_1_words_1_1_tables_1_1_row_format.html", "class_aspose_1_1_words_1_1_tables_1_1_row_format" ],
          [ "Table", "class_aspose_1_1_words_1_1_tables_1_1_table.html", "class_aspose_1_1_words_1_1_tables_1_1_table" ],
          [ "TableCollection", "class_aspose_1_1_words_1_1_tables_1_1_table_collection.html", "class_aspose_1_1_words_1_1_tables_1_1_table_collection" ]
        ] ],
        [ "Themes", "namespace_aspose_1_1_words_1_1_themes.html", [
          [ "Theme", "class_aspose_1_1_words_1_1_themes_1_1_theme.html", "class_aspose_1_1_words_1_1_themes_1_1_theme" ],
          [ "ThemeColors", "class_aspose_1_1_words_1_1_themes_1_1_theme_colors.html", "class_aspose_1_1_words_1_1_themes_1_1_theme_colors" ],
          [ "ThemeFonts", "class_aspose_1_1_words_1_1_themes_1_1_theme_fonts.html", "class_aspose_1_1_words_1_1_themes_1_1_theme_fonts" ]
        ] ],
        [ "Vba", "namespace_aspose_1_1_words_1_1_vba.html", [
          [ "VbaModule", "class_aspose_1_1_words_1_1_vba_1_1_vba_module.html", "class_aspose_1_1_words_1_1_vba_1_1_vba_module" ],
          [ "VbaModuleCollection", "class_aspose_1_1_words_1_1_vba_1_1_vba_module_collection.html", "class_aspose_1_1_words_1_1_vba_1_1_vba_module_collection" ],
          [ "VbaProject", "class_aspose_1_1_words_1_1_vba_1_1_vba_project.html", "class_aspose_1_1_words_1_1_vba_1_1_vba_project" ],
          [ "VbaReference", "class_aspose_1_1_words_1_1_vba_1_1_vba_reference.html", "class_aspose_1_1_words_1_1_vba_1_1_vba_reference" ],
          [ "VbaReferenceCollection", "class_aspose_1_1_words_1_1_vba_1_1_vba_reference_collection.html", "class_aspose_1_1_words_1_1_vba_1_1_vba_reference_collection" ]
        ] ],
        [ "WebExtensions", "namespace_aspose_1_1_words_1_1_web_extensions.html", [
          [ "BaseWebExtensionCollection", "class_aspose_1_1_words_1_1_web_extensions_1_1_base_web_extension_collection.html", "class_aspose_1_1_words_1_1_web_extensions_1_1_base_web_extension_collection" ],
          [ "TaskPane", "class_aspose_1_1_words_1_1_web_extensions_1_1_task_pane.html", "class_aspose_1_1_words_1_1_web_extensions_1_1_task_pane" ],
          [ "TaskPaneCollection", "class_aspose_1_1_words_1_1_web_extensions_1_1_task_pane_collection.html", "class_aspose_1_1_words_1_1_web_extensions_1_1_task_pane_collection" ],
          [ "WebExtension", "class_aspose_1_1_words_1_1_web_extensions_1_1_web_extension.html", "class_aspose_1_1_words_1_1_web_extensions_1_1_web_extension" ],
          [ "WebExtensionBinding", "class_aspose_1_1_words_1_1_web_extensions_1_1_web_extension_binding.html", "class_aspose_1_1_words_1_1_web_extensions_1_1_web_extension_binding" ],
          [ "WebExtensionBindingCollection", "class_aspose_1_1_words_1_1_web_extensions_1_1_web_extension_binding_collection.html", "class_aspose_1_1_words_1_1_web_extensions_1_1_web_extension_binding_collection" ],
          [ "WebExtensionProperty", "class_aspose_1_1_words_1_1_web_extensions_1_1_web_extension_property.html", "class_aspose_1_1_words_1_1_web_extensions_1_1_web_extension_property" ],
          [ "WebExtensionPropertyCollection", "class_aspose_1_1_words_1_1_web_extensions_1_1_web_extension_property_collection.html", "class_aspose_1_1_words_1_1_web_extensions_1_1_web_extension_property_collection" ],
          [ "WebExtensionReference", "class_aspose_1_1_words_1_1_web_extensions_1_1_web_extension_reference.html", "class_aspose_1_1_words_1_1_web_extensions_1_1_web_extension_reference" ],
          [ "WebExtensionReferenceCollection", "class_aspose_1_1_words_1_1_web_extensions_1_1_web_extension_reference_collection.html", "class_aspose_1_1_words_1_1_web_extensions_1_1_web_extension_reference_collection" ]
        ] ],
        [ "AbsolutePositionTab", "class_aspose_1_1_words_1_1_absolute_position_tab.html", "class_aspose_1_1_words_1_1_absolute_position_tab" ],
        [ "Body", "class_aspose_1_1_words_1_1_body.html", "class_aspose_1_1_words_1_1_body" ],
        [ "Bookmark", "class_aspose_1_1_words_1_1_bookmark.html", "class_aspose_1_1_words_1_1_bookmark" ],
        [ "BookmarkCollection", "class_aspose_1_1_words_1_1_bookmark_collection.html", "class_aspose_1_1_words_1_1_bookmark_collection" ],
        [ "BookmarkEnd", "class_aspose_1_1_words_1_1_bookmark_end.html", "class_aspose_1_1_words_1_1_bookmark_end" ],
        [ "BookmarkStart", "class_aspose_1_1_words_1_1_bookmark_start.html", "class_aspose_1_1_words_1_1_bookmark_start" ],
        [ "Border", "class_aspose_1_1_words_1_1_border.html", "class_aspose_1_1_words_1_1_border" ],
        [ "BorderCollection", "class_aspose_1_1_words_1_1_border_collection.html", "class_aspose_1_1_words_1_1_border_collection" ],
        [ "BuildVersionInfo", "class_aspose_1_1_words_1_1_build_version_info.html", "class_aspose_1_1_words_1_1_build_version_info" ],
        [ "CleanupOptions", "class_aspose_1_1_words_1_1_cleanup_options.html", "class_aspose_1_1_words_1_1_cleanup_options" ],
        [ "Comment", "class_aspose_1_1_words_1_1_comment.html", "class_aspose_1_1_words_1_1_comment" ],
        [ "CommentCollection", "class_aspose_1_1_words_1_1_comment_collection.html", "class_aspose_1_1_words_1_1_comment_collection" ],
        [ "CommentRangeEnd", "class_aspose_1_1_words_1_1_comment_range_end.html", "class_aspose_1_1_words_1_1_comment_range_end" ],
        [ "CommentRangeStart", "class_aspose_1_1_words_1_1_comment_range_start.html", "class_aspose_1_1_words_1_1_comment_range_start" ],
        [ "CompositeNode", "class_aspose_1_1_words_1_1_composite_node.html", "class_aspose_1_1_words_1_1_composite_node" ],
        [ "ConditionalStyle", "class_aspose_1_1_words_1_1_conditional_style.html", "class_aspose_1_1_words_1_1_conditional_style" ],
        [ "ConditionalStyleCollection", "class_aspose_1_1_words_1_1_conditional_style_collection.html", "class_aspose_1_1_words_1_1_conditional_style_collection" ],
        [ "ControlChar", "class_aspose_1_1_words_1_1_control_char.html", "class_aspose_1_1_words_1_1_control_char" ],
        [ "ConvertUtil", "class_aspose_1_1_words_1_1_convert_util.html", "class_aspose_1_1_words_1_1_convert_util" ],
        [ "Document", "class_aspose_1_1_words_1_1_document.html", "class_aspose_1_1_words_1_1_document" ],
        [ "DocumentBase", "class_aspose_1_1_words_1_1_document_base.html", "class_aspose_1_1_words_1_1_document_base" ],
        [ "DocumentBuilder", "class_aspose_1_1_words_1_1_document_builder.html", "class_aspose_1_1_words_1_1_document_builder" ],
        [ "DocumentVisitor", "class_aspose_1_1_words_1_1_document_visitor.html", "class_aspose_1_1_words_1_1_document_visitor" ],
        [ "EditableRange", "class_aspose_1_1_words_1_1_editable_range.html", "class_aspose_1_1_words_1_1_editable_range" ],
        [ "EditableRangeEnd", "class_aspose_1_1_words_1_1_editable_range_end.html", "class_aspose_1_1_words_1_1_editable_range_end" ],
        [ "EditableRangeStart", "class_aspose_1_1_words_1_1_editable_range_start.html", "class_aspose_1_1_words_1_1_editable_range_start" ],
        [ "FileFormatInfo", "class_aspose_1_1_words_1_1_file_format_info.html", "class_aspose_1_1_words_1_1_file_format_info" ],
        [ "FileFormatUtil", "class_aspose_1_1_words_1_1_file_format_util.html", "class_aspose_1_1_words_1_1_file_format_util" ],
        [ "Font", "class_aspose_1_1_words_1_1_font.html", "class_aspose_1_1_words_1_1_font" ],
        [ "FrameFormat", "class_aspose_1_1_words_1_1_frame_format.html", "class_aspose_1_1_words_1_1_frame_format" ],
        [ "HeaderFooter", "class_aspose_1_1_words_1_1_header_footer.html", "class_aspose_1_1_words_1_1_header_footer" ],
        [ "HeaderFooterCollection", "class_aspose_1_1_words_1_1_header_footer_collection.html", "class_aspose_1_1_words_1_1_header_footer_collection" ],
        [ "Hyphenation", "class_aspose_1_1_words_1_1_hyphenation.html", "class_aspose_1_1_words_1_1_hyphenation" ],
        [ "IDocumentReaderPlugin", "class_aspose_1_1_words_1_1_i_document_reader_plugin.html", "class_aspose_1_1_words_1_1_i_document_reader_plugin" ],
        [ "IHyphenationCallback", "class_aspose_1_1_words_1_1_i_hyphenation_callback.html", "class_aspose_1_1_words_1_1_i_hyphenation_callback" ],
        [ "ImageWatermarkOptions", "class_aspose_1_1_words_1_1_image_watermark_options.html", "class_aspose_1_1_words_1_1_image_watermark_options" ],
        [ "ImportFormatOptions", "class_aspose_1_1_words_1_1_import_format_options.html", "class_aspose_1_1_words_1_1_import_format_options" ],
        [ "Inline", "class_aspose_1_1_words_1_1_inline.html", "class_aspose_1_1_words_1_1_inline" ],
        [ "InlineStory", "class_aspose_1_1_words_1_1_inline_story.html", "class_aspose_1_1_words_1_1_inline_story" ],
        [ "INodeChangingCallback", "class_aspose_1_1_words_1_1_i_node_changing_callback.html", "class_aspose_1_1_words_1_1_i_node_changing_callback" ],
        [ "InternableComplexAttr", "class_aspose_1_1_words_1_1_internable_complex_attr.html", "class_aspose_1_1_words_1_1_internable_complex_attr" ],
        [ "IWarningCallback", "class_aspose_1_1_words_1_1_i_warning_callback.html", "class_aspose_1_1_words_1_1_i_warning_callback" ],
        [ "License", "class_aspose_1_1_words_1_1_license.html", "class_aspose_1_1_words_1_1_license" ],
        [ "Node", "class_aspose_1_1_words_1_1_node.html", "class_aspose_1_1_words_1_1_node" ],
        [ "NodeChangingArgs", "class_aspose_1_1_words_1_1_node_changing_args.html", "class_aspose_1_1_words_1_1_node_changing_args" ],
        [ "NodeCollection", "class_aspose_1_1_words_1_1_node_collection.html", "class_aspose_1_1_words_1_1_node_collection" ],
        [ "NodeImporter", "class_aspose_1_1_words_1_1_node_importer.html", "class_aspose_1_1_words_1_1_node_importer" ],
        [ "NodeList", "class_aspose_1_1_words_1_1_node_list.html", "class_aspose_1_1_words_1_1_node_list" ],
        [ "PageSetup", "class_aspose_1_1_words_1_1_page_setup.html", "class_aspose_1_1_words_1_1_page_setup" ],
        [ "Paragraph", "class_aspose_1_1_words_1_1_paragraph.html", "class_aspose_1_1_words_1_1_paragraph" ],
        [ "ParagraphCollection", "class_aspose_1_1_words_1_1_paragraph_collection.html", "class_aspose_1_1_words_1_1_paragraph_collection" ],
        [ "ParagraphFormat", "class_aspose_1_1_words_1_1_paragraph_format.html", "class_aspose_1_1_words_1_1_paragraph_format" ],
        [ "PlainTextDocument", "class_aspose_1_1_words_1_1_plain_text_document.html", "class_aspose_1_1_words_1_1_plain_text_document" ],
        [ "Range", "class_aspose_1_1_words_1_1_range.html", "class_aspose_1_1_words_1_1_range" ],
        [ "Revision", "class_aspose_1_1_words_1_1_revision.html", "class_aspose_1_1_words_1_1_revision" ],
        [ "RevisionCollection", "class_aspose_1_1_words_1_1_revision_collection.html", "class_aspose_1_1_words_1_1_revision_collection" ],
        [ "RevisionGroup", "class_aspose_1_1_words_1_1_revision_group.html", "class_aspose_1_1_words_1_1_revision_group" ],
        [ "RevisionGroupCollection", "class_aspose_1_1_words_1_1_revision_group_collection.html", "class_aspose_1_1_words_1_1_revision_group_collection" ],
        [ "Run", "class_aspose_1_1_words_1_1_run.html", "class_aspose_1_1_words_1_1_run" ],
        [ "RunCollection", "class_aspose_1_1_words_1_1_run_collection.html", "class_aspose_1_1_words_1_1_run_collection" ],
        [ "Section", "class_aspose_1_1_words_1_1_section.html", "class_aspose_1_1_words_1_1_section" ],
        [ "SectionCollection", "class_aspose_1_1_words_1_1_section_collection.html", "class_aspose_1_1_words_1_1_section_collection" ],
        [ "Shading", "class_aspose_1_1_words_1_1_shading.html", "class_aspose_1_1_words_1_1_shading" ],
        [ "SignatureLineOptions", "class_aspose_1_1_words_1_1_signature_line_options.html", "class_aspose_1_1_words_1_1_signature_line_options" ],
        [ "SpecialChar", "class_aspose_1_1_words_1_1_special_char.html", "class_aspose_1_1_words_1_1_special_char" ],
        [ "Story", "class_aspose_1_1_words_1_1_story.html", "class_aspose_1_1_words_1_1_story" ],
        [ "Style", "class_aspose_1_1_words_1_1_style.html", "class_aspose_1_1_words_1_1_style" ],
        [ "StyleCollection", "class_aspose_1_1_words_1_1_style_collection.html", "class_aspose_1_1_words_1_1_style_collection" ],
        [ "SubDocument", "class_aspose_1_1_words_1_1_sub_document.html", "class_aspose_1_1_words_1_1_sub_document" ],
        [ "TableStyle", "class_aspose_1_1_words_1_1_table_style.html", "class_aspose_1_1_words_1_1_table_style" ],
        [ "TabStop", "class_aspose_1_1_words_1_1_tab_stop.html", "class_aspose_1_1_words_1_1_tab_stop" ],
        [ "TabStopCollection", "class_aspose_1_1_words_1_1_tab_stop_collection.html", "class_aspose_1_1_words_1_1_tab_stop_collection" ],
        [ "TextColumn", "class_aspose_1_1_words_1_1_text_column.html", "class_aspose_1_1_words_1_1_text_column" ],
        [ "TextColumnCollection", "class_aspose_1_1_words_1_1_text_column_collection.html", "class_aspose_1_1_words_1_1_text_column_collection" ],
        [ "TextWatermarkOptions", "class_aspose_1_1_words_1_1_text_watermark_options.html", "class_aspose_1_1_words_1_1_text_watermark_options" ],
        [ "VariableCollection", "class_aspose_1_1_words_1_1_variable_collection.html", "class_aspose_1_1_words_1_1_variable_collection" ],
        [ "WarningInfo", "class_aspose_1_1_words_1_1_warning_info.html", "class_aspose_1_1_words_1_1_warning_info" ],
        [ "WarningInfoCollection", "class_aspose_1_1_words_1_1_warning_info_collection.html", "class_aspose_1_1_words_1_1_warning_info_collection" ],
        [ "Watermark", "class_aspose_1_1_words_1_1_watermark.html", "class_aspose_1_1_words_1_1_watermark" ]
      ] ]
    ] ]
];