var class_aspose_1_1_words_1_1_tables_1_1_cell_format =
[
    [ "ClearFormatting", "class_aspose_1_1_words_1_1_tables_1_1_cell_format.html#clearformatting", null ],
    [ "get_Borders", "class_aspose_1_1_words_1_1_tables_1_1_cell_format.html#get_borders", null ],
    [ "get_BottomPadding", "class_aspose_1_1_words_1_1_tables_1_1_cell_format.html#get_bottompadding", null ],
    [ "get_FitText", "class_aspose_1_1_words_1_1_tables_1_1_cell_format.html#get_fittext", null ],
    [ "get_HorizontalMerge", "class_aspose_1_1_words_1_1_tables_1_1_cell_format.html#get_horizontalmerge", null ],
    [ "get_LeftPadding", "class_aspose_1_1_words_1_1_tables_1_1_cell_format.html#get_leftpadding", null ],
    [ "get_Orientation", "class_aspose_1_1_words_1_1_tables_1_1_cell_format.html#get_orientation", null ],
    [ "get_PreferredWidth", "class_aspose_1_1_words_1_1_tables_1_1_cell_format.html#get_preferredwidth", null ],
    [ "get_RightPadding", "class_aspose_1_1_words_1_1_tables_1_1_cell_format.html#get_rightpadding", null ],
    [ "get_Shading", "class_aspose_1_1_words_1_1_tables_1_1_cell_format.html#get_shading", null ],
    [ "get_TopPadding", "class_aspose_1_1_words_1_1_tables_1_1_cell_format.html#get_toppadding", null ],
    [ "get_VerticalAlignment", "class_aspose_1_1_words_1_1_tables_1_1_cell_format.html#get_verticalalignment", null ],
    [ "get_VerticalMerge", "class_aspose_1_1_words_1_1_tables_1_1_cell_format.html#get_verticalmerge", null ],
    [ "get_Width", "class_aspose_1_1_words_1_1_tables_1_1_cell_format.html#get_width", null ],
    [ "get_WrapText", "class_aspose_1_1_words_1_1_tables_1_1_cell_format.html#get_wraptext", null ],
    [ "GetType", "class_aspose_1_1_words_1_1_tables_1_1_cell_format.html#gettype_const", null ],
    [ "Is", "class_aspose_1_1_words_1_1_tables_1_1_cell_format.html#is_typeinfo_const", null ],
    [ "set_BottomPadding", "class_aspose_1_1_words_1_1_tables_1_1_cell_format.html#set_bottompadding", null ],
    [ "set_FitText", "class_aspose_1_1_words_1_1_tables_1_1_cell_format.html#set_fittext", null ],
    [ "set_HorizontalMerge", "class_aspose_1_1_words_1_1_tables_1_1_cell_format.html#set_horizontalmerge", null ],
    [ "set_LeftPadding", "class_aspose_1_1_words_1_1_tables_1_1_cell_format.html#set_leftpadding", null ],
    [ "set_Orientation", "class_aspose_1_1_words_1_1_tables_1_1_cell_format.html#set_orientation", null ],
    [ "set_PreferredWidth", "class_aspose_1_1_words_1_1_tables_1_1_cell_format.html#set_preferredwidth", null ],
    [ "set_RightPadding", "class_aspose_1_1_words_1_1_tables_1_1_cell_format.html#set_rightpadding", null ],
    [ "set_TopPadding", "class_aspose_1_1_words_1_1_tables_1_1_cell_format.html#set_toppadding", null ],
    [ "set_VerticalAlignment", "class_aspose_1_1_words_1_1_tables_1_1_cell_format.html#set_verticalalignment", null ],
    [ "set_VerticalMerge", "class_aspose_1_1_words_1_1_tables_1_1_cell_format.html#set_verticalmerge", null ],
    [ "set_Width", "class_aspose_1_1_words_1_1_tables_1_1_cell_format.html#set_width", null ],
    [ "set_WrapText", "class_aspose_1_1_words_1_1_tables_1_1_cell_format.html#set_wraptext", null ],
    [ "SetPaddings", "class_aspose_1_1_words_1_1_tables_1_1_cell_format.html#setpaddings_double_double_double_double", null ],
    [ "Type", "class_aspose_1_1_words_1_1_tables_1_1_cell_format.html#type", null ]
];