var class_aspose_1_1_words_1_1_replacing_1_1_find_replace_options =
[
    [ "FindReplaceOptions", "class_aspose_1_1_words_1_1_replacing_1_1_find_replace_options.html#findreplaceoptions", null ],
    [ "FindReplaceOptions", "class_aspose_1_1_words_1_1_replacing_1_1_find_replace_options.html#findreplaceoptions_findreplacedirection", null ],
    [ "FindReplaceOptions", "class_aspose_1_1_words_1_1_replacing_1_1_find_replace_options.html#findreplaceoptions_ireplacingcallback", null ],
    [ "FindReplaceOptions", "class_aspose_1_1_words_1_1_replacing_1_1_find_replace_options.html#findreplaceoptions_findreplacedirection_ireplacingcallback", null ],
    [ "get_ApplyFont", "class_aspose_1_1_words_1_1_replacing_1_1_find_replace_options.html#get_applyfont_const", null ],
    [ "get_ApplyParagraphFormat", "class_aspose_1_1_words_1_1_replacing_1_1_find_replace_options.html#get_applyparagraphformat_const", null ],
    [ "get_Direction", "class_aspose_1_1_words_1_1_replacing_1_1_find_replace_options.html#get_direction_const", null ],
    [ "get_FindWholeWordsOnly", "class_aspose_1_1_words_1_1_replacing_1_1_find_replace_options.html#get_findwholewordsonly_const", null ],
    [ "get_IgnoreDeleted", "class_aspose_1_1_words_1_1_replacing_1_1_find_replace_options.html#get_ignoredeleted_const", null ],
    [ "get_IgnoreFieldCodes", "class_aspose_1_1_words_1_1_replacing_1_1_find_replace_options.html#get_ignorefieldcodes_const", null ],
    [ "get_IgnoreFields", "class_aspose_1_1_words_1_1_replacing_1_1_find_replace_options.html#get_ignorefields_const", null ],
    [ "get_IgnoreFootnotes", "class_aspose_1_1_words_1_1_replacing_1_1_find_replace_options.html#get_ignorefootnotes_const", null ],
    [ "get_IgnoreInserted", "class_aspose_1_1_words_1_1_replacing_1_1_find_replace_options.html#get_ignoreinserted_const", null ],
    [ "get_LegacyMode", "class_aspose_1_1_words_1_1_replacing_1_1_find_replace_options.html#get_legacymode_const", null ],
    [ "get_MatchCase", "class_aspose_1_1_words_1_1_replacing_1_1_find_replace_options.html#get_matchcase_const", null ],
    [ "get_ReplacingCallback", "class_aspose_1_1_words_1_1_replacing_1_1_find_replace_options.html#get_replacingcallback_const", null ],
    [ "get_SmartParagraphBreakReplacement", "class_aspose_1_1_words_1_1_replacing_1_1_find_replace_options.html#get_smartparagraphbreakreplacement_const", null ],
    [ "get_UseLegacyOrder", "class_aspose_1_1_words_1_1_replacing_1_1_find_replace_options.html#get_uselegacyorder_const", null ],
    [ "get_UseSubstitutions", "class_aspose_1_1_words_1_1_replacing_1_1_find_replace_options.html#get_usesubstitutions_const", null ],
    [ "GetType", "class_aspose_1_1_words_1_1_replacing_1_1_find_replace_options.html#gettype_const", null ],
    [ "Is", "class_aspose_1_1_words_1_1_replacing_1_1_find_replace_options.html#is_typeinfo_const", null ],
    [ "set_Direction", "class_aspose_1_1_words_1_1_replacing_1_1_find_replace_options.html#set_direction", null ],
    [ "set_FindWholeWordsOnly", "class_aspose_1_1_words_1_1_replacing_1_1_find_replace_options.html#set_findwholewordsonly", null ],
    [ "set_IgnoreDeleted", "class_aspose_1_1_words_1_1_replacing_1_1_find_replace_options.html#set_ignoredeleted", null ],
    [ "set_IgnoreFieldCodes", "class_aspose_1_1_words_1_1_replacing_1_1_find_replace_options.html#set_ignorefieldcodes", null ],
    [ "set_IgnoreFields", "class_aspose_1_1_words_1_1_replacing_1_1_find_replace_options.html#set_ignorefields", null ],
    [ "set_IgnoreFootnotes", "class_aspose_1_1_words_1_1_replacing_1_1_find_replace_options.html#set_ignorefootnotes", null ],
    [ "set_IgnoreInserted", "class_aspose_1_1_words_1_1_replacing_1_1_find_replace_options.html#set_ignoreinserted", null ],
    [ "set_LegacyMode", "class_aspose_1_1_words_1_1_replacing_1_1_find_replace_options.html#set_legacymode", null ],
    [ "set_MatchCase", "class_aspose_1_1_words_1_1_replacing_1_1_find_replace_options.html#set_matchcase", null ],
    [ "set_ReplacingCallback", "class_aspose_1_1_words_1_1_replacing_1_1_find_replace_options.html#set_replacingcallback", null ],
    [ "set_SmartParagraphBreakReplacement", "class_aspose_1_1_words_1_1_replacing_1_1_find_replace_options.html#set_smartparagraphbreakreplacement", null ],
    [ "set_UseLegacyOrder", "class_aspose_1_1_words_1_1_replacing_1_1_find_replace_options.html#set_uselegacyorder", null ],
    [ "set_UseSubstitutions", "class_aspose_1_1_words_1_1_replacing_1_1_find_replace_options.html#set_usesubstitutions", null ],
    [ "Type", "class_aspose_1_1_words_1_1_replacing_1_1_find_replace_options.html#type", null ]
];