var class_aspose_1_1_words_1_1_drawing_1_1_shape =
[
    [ "Shape", "class_aspose_1_1_words_1_1_drawing_1_1_shape.html#shape_documentbase_shapetype", null ],
    [ "Accept", "class_aspose_1_1_words_1_1_drawing_1_1_shape.html#accept_documentvisitor", null ],
    [ "get_Chart", "class_aspose_1_1_words_1_1_drawing_1_1_shape.html#get_chart", null ],
    [ "get_ExtrusionEnabled", "class_aspose_1_1_words_1_1_drawing_1_1_shape.html#get_extrusionenabled", null ],
    [ "get_FillColor", "class_aspose_1_1_words_1_1_drawing_1_1_shape.html#get_fillcolor", null ],
    [ "get_Filled", "class_aspose_1_1_words_1_1_drawing_1_1_shape.html#get_filled", null ],
    [ "get_FirstParagraph", "class_aspose_1_1_words_1_1_drawing_1_1_shape.html#get_firstparagraph", null ],
    [ "get_HasChart", "class_aspose_1_1_words_1_1_drawing_1_1_shape.html#get_haschart", null ],
    [ "get_HasImage", "class_aspose_1_1_words_1_1_drawing_1_1_shape.html#get_hasimage", null ],
    [ "get_HasSmartArt", "class_aspose_1_1_words_1_1_drawing_1_1_shape.html#get_hassmartart", null ],
    [ "get_HorizontalRuleFormat", "class_aspose_1_1_words_1_1_drawing_1_1_shape.html#get_horizontalruleformat", null ],
    [ "get_ImageData", "class_aspose_1_1_words_1_1_drawing_1_1_shape.html#get_imagedata", null ],
    [ "get_LastParagraph", "class_aspose_1_1_words_1_1_drawing_1_1_shape.html#get_lastparagraph", null ],
    [ "get_NodeType", "class_aspose_1_1_words_1_1_drawing_1_1_shape.html#get_nodetype_const", null ],
    [ "get_OleFormat", "class_aspose_1_1_words_1_1_drawing_1_1_shape.html#get_oleformat", null ],
    [ "get_ShadowEnabled", "class_aspose_1_1_words_1_1_drawing_1_1_shape.html#get_shadowenabled", null ],
    [ "get_SignatureLine", "class_aspose_1_1_words_1_1_drawing_1_1_shape.html#get_signatureline", null ],
    [ "get_StoryType", "class_aspose_1_1_words_1_1_drawing_1_1_shape.html#get_storytype", null ],
    [ "get_Stroke", "class_aspose_1_1_words_1_1_drawing_1_1_shape.html#get_stroke", null ],
    [ "get_StrokeColor", "class_aspose_1_1_words_1_1_drawing_1_1_shape.html#get_strokecolor", null ],
    [ "get_Stroked", "class_aspose_1_1_words_1_1_drawing_1_1_shape.html#get_stroked", null ],
    [ "get_StrokeWeight", "class_aspose_1_1_words_1_1_drawing_1_1_shape.html#get_strokeweight", null ],
    [ "get_TextBox", "class_aspose_1_1_words_1_1_drawing_1_1_shape.html#get_textbox", null ],
    [ "get_TextPath", "class_aspose_1_1_words_1_1_drawing_1_1_shape.html#get_textpath", null ],
    [ "GetType", "class_aspose_1_1_words_1_1_drawing_1_1_shape.html#gettype_const", null ],
    [ "Is", "class_aspose_1_1_words_1_1_drawing_1_1_shape.html#is_typeinfo_const", null ],
    [ "set_FillColor", "class_aspose_1_1_words_1_1_drawing_1_1_shape.html#set_fillcolor", null ],
    [ "set_Filled", "class_aspose_1_1_words_1_1_drawing_1_1_shape.html#set_filled", null ],
    [ "set_StrokeColor", "class_aspose_1_1_words_1_1_drawing_1_1_shape.html#set_strokecolor", null ],
    [ "set_Stroked", "class_aspose_1_1_words_1_1_drawing_1_1_shape.html#set_stroked", null ],
    [ "set_StrokeWeight", "class_aspose_1_1_words_1_1_drawing_1_1_shape.html#set_strokeweight", null ],
    [ "Type", "class_aspose_1_1_words_1_1_drawing_1_1_shape.html#type", null ],
    [ "UpdateSmartArtDrawing", "class_aspose_1_1_words_1_1_drawing_1_1_shape.html#updatesmartartdrawing", null ]
];