var class_aspose_1_1_words_1_1_node =
[
    [ "Accept", "class_aspose_1_1_words_1_1_node.html#accept_documentvisitor", null ],
    [ "Clone", "class_aspose_1_1_words_1_1_node.html#clone_bool", null ],
    [ "get_CustomNodeId", "class_aspose_1_1_words_1_1_node.html#get_customnodeid_const", null ],
    [ "get_Document", "class_aspose_1_1_words_1_1_node.html#get_document_const", null ],
    [ "get_IsComposite", "class_aspose_1_1_words_1_1_node.html#get_iscomposite", null ],
    [ "get_NextSibling", "class_aspose_1_1_words_1_1_node.html#get_nextsibling", null ],
    [ "get_NodeType", "class_aspose_1_1_words_1_1_node.html#get_nodetype_const", null ],
    [ "get_ParentNode", "class_aspose_1_1_words_1_1_node.html#get_parentnode", null ],
    [ "get_PreviousSibling", "class_aspose_1_1_words_1_1_node.html#get_previoussibling", null ],
    [ "get_Range", "class_aspose_1_1_words_1_1_node.html#get_range", null ],
    [ "GetAncestor", "class_aspose_1_1_words_1_1_node.html#getancestor_nodetype", null ],
    [ "GetAncestorOf", "class_aspose_1_1_words_1_1_node.html#getancestorof", null ],
    [ "GetText", "class_aspose_1_1_words_1_1_node.html#gettext", null ],
    [ "GetType", "class_aspose_1_1_words_1_1_node.html#gettype_const", null ],
    [ "Is", "class_aspose_1_1_words_1_1_node.html#is_typeinfo_const", null ],
    [ "NextPreOrder", "class_aspose_1_1_words_1_1_node.html#nextpreorder_node", null ],
    [ "NodeTypeToString", "class_aspose_1_1_words_1_1_node.html#nodetypetostring_nodetype", null ],
    [ "PreviousPreOrder", "class_aspose_1_1_words_1_1_node.html#previouspreorder_node", null ],
    [ "Remove", "class_aspose_1_1_words_1_1_node.html#remove", null ],
    [ "set_CustomNodeId", "class_aspose_1_1_words_1_1_node.html#set_customnodeid", null ],
    [ "ToString", "class_aspose_1_1_words_1_1_node.html#tostring_saveformat", null ],
    [ "ToString", "class_aspose_1_1_words_1_1_node.html#tostring_saveoptions", null ],
    [ "Type", "class_aspose_1_1_words_1_1_node.html#type", null ]
];