var class_aspose_1_1_words_1_1_drawing_1_1_ole_format =
[
    [ "get_AutoUpdate", "class_aspose_1_1_words_1_1_drawing_1_1_ole_format.html#get_autoupdate", null ],
    [ "get_Clsid", "class_aspose_1_1_words_1_1_drawing_1_1_ole_format.html#get_clsid", null ],
    [ "get_IconCaption", "class_aspose_1_1_words_1_1_drawing_1_1_ole_format.html#get_iconcaption", null ],
    [ "get_IsLink", "class_aspose_1_1_words_1_1_drawing_1_1_ole_format.html#get_islink", null ],
    [ "get_IsLocked", "class_aspose_1_1_words_1_1_drawing_1_1_ole_format.html#get_islocked", null ],
    [ "get_OleControl", "class_aspose_1_1_words_1_1_drawing_1_1_ole_format.html#get_olecontrol", null ],
    [ "get_OleIcon", "class_aspose_1_1_words_1_1_drawing_1_1_ole_format.html#get_oleicon", null ],
    [ "get_OlePackage", "class_aspose_1_1_words_1_1_drawing_1_1_ole_format.html#get_olepackage", null ],
    [ "get_ProgId", "class_aspose_1_1_words_1_1_drawing_1_1_ole_format.html#get_progid", null ],
    [ "get_SourceFullName", "class_aspose_1_1_words_1_1_drawing_1_1_ole_format.html#get_sourcefullname", null ],
    [ "get_SourceItem", "class_aspose_1_1_words_1_1_drawing_1_1_ole_format.html#get_sourceitem", null ],
    [ "get_SuggestedExtension", "class_aspose_1_1_words_1_1_drawing_1_1_ole_format.html#get_suggestedextension", null ],
    [ "get_SuggestedFileName", "class_aspose_1_1_words_1_1_drawing_1_1_ole_format.html#get_suggestedfilename", null ],
    [ "GetOleEntry", "class_aspose_1_1_words_1_1_drawing_1_1_ole_format.html#getoleentry_string", null ],
    [ "GetRawData", "class_aspose_1_1_words_1_1_drawing_1_1_ole_format.html#getrawdata", null ],
    [ "GetType", "class_aspose_1_1_words_1_1_drawing_1_1_ole_format.html#gettype_const", null ],
    [ "Is", "class_aspose_1_1_words_1_1_drawing_1_1_ole_format.html#is_typeinfo_const", null ],
    [ "Save", "class_aspose_1_1_words_1_1_drawing_1_1_ole_format.html#save_stream", null ],
    [ "Save", "class_aspose_1_1_words_1_1_drawing_1_1_ole_format.html#save_string", null ],
    [ "Save", "class_aspose_1_1_words_1_1_drawing_1_1_ole_format.html#save_stdbasicostream", null ],
    [ "set_AutoUpdate", "class_aspose_1_1_words_1_1_drawing_1_1_ole_format.html#set_autoupdate", null ],
    [ "set_IsLocked", "class_aspose_1_1_words_1_1_drawing_1_1_ole_format.html#set_islocked", null ],
    [ "set_ProgId", "class_aspose_1_1_words_1_1_drawing_1_1_ole_format.html#set_progid", null ],
    [ "set_SourceFullName", "class_aspose_1_1_words_1_1_drawing_1_1_ole_format.html#set_sourcefullname", null ],
    [ "set_SourceItem", "class_aspose_1_1_words_1_1_drawing_1_1_ole_format.html#set_sourceitem", null ],
    [ "Type", "class_aspose_1_1_words_1_1_drawing_1_1_ole_format.html#type", null ]
];