var class_aspose_1_1_words_1_1_lists_1_1_list_level =
[
    [ "CreatePictureBullet", "class_aspose_1_1_words_1_1_lists_1_1_list_level.html#createpicturebullet", null ],
    [ "DeletePictureBullet", "class_aspose_1_1_words_1_1_lists_1_1_list_level.html#deletepicturebullet", null ],
    [ "Equals", "class_aspose_1_1_words_1_1_lists_1_1_list_level.html#equals_listlevel", null ],
    [ "get_Alignment", "class_aspose_1_1_words_1_1_lists_1_1_list_level.html#get_alignment_const", null ],
    [ "get_CustomNumberStyleFormat", "class_aspose_1_1_words_1_1_lists_1_1_list_level.html#get_customnumberstyleformat", null ],
    [ "get_Font", "class_aspose_1_1_words_1_1_lists_1_1_list_level.html#get_font", null ],
    [ "get_ImageData", "class_aspose_1_1_words_1_1_lists_1_1_list_level.html#get_imagedata", null ],
    [ "get_IsLegal", "class_aspose_1_1_words_1_1_lists_1_1_list_level.html#get_islegal_const", null ],
    [ "get_LinkedStyle", "class_aspose_1_1_words_1_1_lists_1_1_list_level.html#get_linkedstyle", null ],
    [ "get_NumberFormat", "class_aspose_1_1_words_1_1_lists_1_1_list_level.html#get_numberformat_const", null ],
    [ "get_NumberPosition", "class_aspose_1_1_words_1_1_lists_1_1_list_level.html#get_numberposition_const", null ],
    [ "get_NumberStyle", "class_aspose_1_1_words_1_1_lists_1_1_list_level.html#get_numberstyle_const", null ],
    [ "get_RestartAfterLevel", "class_aspose_1_1_words_1_1_lists_1_1_list_level.html#get_restartafterlevel_const", null ],
    [ "get_StartAt", "class_aspose_1_1_words_1_1_lists_1_1_list_level.html#get_startat", null ],
    [ "get_TabPosition", "class_aspose_1_1_words_1_1_lists_1_1_list_level.html#get_tabposition_const", null ],
    [ "get_TextPosition", "class_aspose_1_1_words_1_1_lists_1_1_list_level.html#get_textposition_const", null ],
    [ "get_TrailingCharacter", "class_aspose_1_1_words_1_1_lists_1_1_list_level.html#get_trailingcharacter_const", null ],
    [ "GetEffectiveValue", "class_aspose_1_1_words_1_1_lists_1_1_list_level.html#geteffectivevalue_int_numberstyle_string", null ],
    [ "GetHashCode", "class_aspose_1_1_words_1_1_lists_1_1_list_level.html#gethashcode_const", null ],
    [ "GetType", "class_aspose_1_1_words_1_1_lists_1_1_list_level.html#gettype_const", null ],
    [ "Is", "class_aspose_1_1_words_1_1_lists_1_1_list_level.html#is_typeinfo_const", null ],
    [ "set_Alignment", "class_aspose_1_1_words_1_1_lists_1_1_list_level.html#set_alignment", null ],
    [ "set_IsLegal", "class_aspose_1_1_words_1_1_lists_1_1_list_level.html#set_islegal", null ],
    [ "set_LinkedStyle", "class_aspose_1_1_words_1_1_lists_1_1_list_level.html#set_linkedstyle", null ],
    [ "set_NumberFormat", "class_aspose_1_1_words_1_1_lists_1_1_list_level.html#set_numberformat", null ],
    [ "set_NumberPosition", "class_aspose_1_1_words_1_1_lists_1_1_list_level.html#set_numberposition", null ],
    [ "set_NumberStyle", "class_aspose_1_1_words_1_1_lists_1_1_list_level.html#set_numberstyle", null ],
    [ "set_RestartAfterLevel", "class_aspose_1_1_words_1_1_lists_1_1_list_level.html#set_restartafterlevel", null ],
    [ "set_StartAt", "class_aspose_1_1_words_1_1_lists_1_1_list_level.html#set_startat", null ],
    [ "set_TabPosition", "class_aspose_1_1_words_1_1_lists_1_1_list_level.html#set_tabposition", null ],
    [ "set_TextPosition", "class_aspose_1_1_words_1_1_lists_1_1_list_level.html#set_textposition", null ],
    [ "set_TrailingCharacter", "class_aspose_1_1_words_1_1_lists_1_1_list_level.html#set_trailingcharacter", null ],
    [ "Type", "class_aspose_1_1_words_1_1_lists_1_1_list_level.html#type", null ]
];