var class_aspose_1_1_words_1_1_comparing_1_1_compare_options =
[
    [ "CompareOptions", "class_aspose_1_1_words_1_1_comparing_1_1_compare_options.html#compareoptions", null ],
    [ "get_Granularity", "class_aspose_1_1_words_1_1_comparing_1_1_compare_options.html#get_granularity_const", null ],
    [ "get_IgnoreCaseChanges", "class_aspose_1_1_words_1_1_comparing_1_1_compare_options.html#get_ignorecasechanges_const", null ],
    [ "get_IgnoreComments", "class_aspose_1_1_words_1_1_comparing_1_1_compare_options.html#get_ignorecomments_const", null ],
    [ "get_IgnoreDmlUniqueId", "class_aspose_1_1_words_1_1_comparing_1_1_compare_options.html#get_ignoredmluniqueid_const", null ],
    [ "get_IgnoreFields", "class_aspose_1_1_words_1_1_comparing_1_1_compare_options.html#get_ignorefields_const", null ],
    [ "get_IgnoreFootnotes", "class_aspose_1_1_words_1_1_comparing_1_1_compare_options.html#get_ignorefootnotes_const", null ],
    [ "get_IgnoreFormatting", "class_aspose_1_1_words_1_1_comparing_1_1_compare_options.html#get_ignoreformatting_const", null ],
    [ "get_IgnoreHeadersAndFooters", "class_aspose_1_1_words_1_1_comparing_1_1_compare_options.html#get_ignoreheadersandfooters_const", null ],
    [ "get_IgnoreTables", "class_aspose_1_1_words_1_1_comparing_1_1_compare_options.html#get_ignoretables_const", null ],
    [ "get_IgnoreTextboxes", "class_aspose_1_1_words_1_1_comparing_1_1_compare_options.html#get_ignoretextboxes_const", null ],
    [ "get_Target", "class_aspose_1_1_words_1_1_comparing_1_1_compare_options.html#get_target_const", null ],
    [ "GetType", "class_aspose_1_1_words_1_1_comparing_1_1_compare_options.html#gettype_const", null ],
    [ "Is", "class_aspose_1_1_words_1_1_comparing_1_1_compare_options.html#is_typeinfo_const", null ],
    [ "set_Granularity", "class_aspose_1_1_words_1_1_comparing_1_1_compare_options.html#set_granularity", null ],
    [ "set_IgnoreCaseChanges", "class_aspose_1_1_words_1_1_comparing_1_1_compare_options.html#set_ignorecasechanges", null ],
    [ "set_IgnoreComments", "class_aspose_1_1_words_1_1_comparing_1_1_compare_options.html#set_ignorecomments", null ],
    [ "set_IgnoreDmlUniqueId", "class_aspose_1_1_words_1_1_comparing_1_1_compare_options.html#set_ignoredmluniqueid", null ],
    [ "set_IgnoreFields", "class_aspose_1_1_words_1_1_comparing_1_1_compare_options.html#set_ignorefields", null ],
    [ "set_IgnoreFootnotes", "class_aspose_1_1_words_1_1_comparing_1_1_compare_options.html#set_ignorefootnotes", null ],
    [ "set_IgnoreFormatting", "class_aspose_1_1_words_1_1_comparing_1_1_compare_options.html#set_ignoreformatting", null ],
    [ "set_IgnoreHeadersAndFooters", "class_aspose_1_1_words_1_1_comparing_1_1_compare_options.html#set_ignoreheadersandfooters", null ],
    [ "set_IgnoreTables", "class_aspose_1_1_words_1_1_comparing_1_1_compare_options.html#set_ignoretables", null ],
    [ "set_IgnoreTextboxes", "class_aspose_1_1_words_1_1_comparing_1_1_compare_options.html#set_ignoretextboxes", null ],
    [ "set_Target", "class_aspose_1_1_words_1_1_comparing_1_1_compare_options.html#set_target", null ],
    [ "Type", "class_aspose_1_1_words_1_1_comparing_1_1_compare_options.html#type", null ]
];