var class_aspose_1_1_words_1_1_drawing_1_1_signature_line =
[
    [ "get_AllowComments", "class_aspose_1_1_words_1_1_drawing_1_1_signature_line.html#get_allowcomments", null ],
    [ "get_DefaultInstructions", "class_aspose_1_1_words_1_1_drawing_1_1_signature_line.html#get_defaultinstructions", null ],
    [ "get_Email", "class_aspose_1_1_words_1_1_drawing_1_1_signature_line.html#get_email", null ],
    [ "get_Id", "class_aspose_1_1_words_1_1_drawing_1_1_signature_line.html#get_id", null ],
    [ "get_Instructions", "class_aspose_1_1_words_1_1_drawing_1_1_signature_line.html#get_instructions", null ],
    [ "get_IsSigned", "class_aspose_1_1_words_1_1_drawing_1_1_signature_line.html#get_issigned", null ],
    [ "get_IsValid", "class_aspose_1_1_words_1_1_drawing_1_1_signature_line.html#get_isvalid", null ],
    [ "get_ProviderId", "class_aspose_1_1_words_1_1_drawing_1_1_signature_line.html#get_providerid", null ],
    [ "get_ShowDate", "class_aspose_1_1_words_1_1_drawing_1_1_signature_line.html#get_showdate", null ],
    [ "get_Signer", "class_aspose_1_1_words_1_1_drawing_1_1_signature_line.html#get_signer", null ],
    [ "get_SignerTitle", "class_aspose_1_1_words_1_1_drawing_1_1_signature_line.html#get_signertitle", null ],
    [ "GetType", "class_aspose_1_1_words_1_1_drawing_1_1_signature_line.html#gettype_const", null ],
    [ "Is", "class_aspose_1_1_words_1_1_drawing_1_1_signature_line.html#is_typeinfo_const", null ],
    [ "set_AllowComments", "class_aspose_1_1_words_1_1_drawing_1_1_signature_line.html#set_allowcomments", null ],
    [ "set_DefaultInstructions", "class_aspose_1_1_words_1_1_drawing_1_1_signature_line.html#set_defaultinstructions", null ],
    [ "set_Email", "class_aspose_1_1_words_1_1_drawing_1_1_signature_line.html#set_email", null ],
    [ "set_Id", "class_aspose_1_1_words_1_1_drawing_1_1_signature_line.html#set_id", null ],
    [ "set_Instructions", "class_aspose_1_1_words_1_1_drawing_1_1_signature_line.html#set_instructions", null ],
    [ "set_ProviderId", "class_aspose_1_1_words_1_1_drawing_1_1_signature_line.html#set_providerid", null ],
    [ "set_ShowDate", "class_aspose_1_1_words_1_1_drawing_1_1_signature_line.html#set_showdate", null ],
    [ "set_Signer", "class_aspose_1_1_words_1_1_drawing_1_1_signature_line.html#set_signer", null ],
    [ "set_SignerTitle", "class_aspose_1_1_words_1_1_drawing_1_1_signature_line.html#set_signertitle", null ],
    [ "Type", "class_aspose_1_1_words_1_1_drawing_1_1_signature_line.html#type", null ]
];