var class_aspose_1_1_words_1_1_table_style =
[
    [ "get_Alignment", "class_aspose_1_1_words_1_1_table_style.html#get_alignment", null ],
    [ "get_AllowBreakAcrossPages", "class_aspose_1_1_words_1_1_table_style.html#get_allowbreakacrosspages", null ],
    [ "get_Bidi", "class_aspose_1_1_words_1_1_table_style.html#get_bidi", null ],
    [ "get_Borders", "class_aspose_1_1_words_1_1_table_style.html#get_borders", null ],
    [ "get_BottomPadding", "class_aspose_1_1_words_1_1_table_style.html#get_bottompadding", null ],
    [ "get_CellSpacing", "class_aspose_1_1_words_1_1_table_style.html#get_cellspacing", null ],
    [ "get_ColumnStripe", "class_aspose_1_1_words_1_1_table_style.html#get_columnstripe", null ],
    [ "get_ConditionalStyles", "class_aspose_1_1_words_1_1_table_style.html#get_conditionalstyles", null ],
    [ "get_LeftIndent", "class_aspose_1_1_words_1_1_table_style.html#get_leftindent", null ],
    [ "get_LeftPadding", "class_aspose_1_1_words_1_1_table_style.html#get_leftpadding", null ],
    [ "get_RightPadding", "class_aspose_1_1_words_1_1_table_style.html#get_rightpadding", null ],
    [ "get_RowStripe", "class_aspose_1_1_words_1_1_table_style.html#get_rowstripe", null ],
    [ "get_Shading", "class_aspose_1_1_words_1_1_table_style.html#get_shading", null ],
    [ "get_TopPadding", "class_aspose_1_1_words_1_1_table_style.html#get_toppadding", null ],
    [ "get_VerticalAlignment", "class_aspose_1_1_words_1_1_table_style.html#get_verticalalignment", null ],
    [ "GetType", "class_aspose_1_1_words_1_1_table_style.html#gettype_const", null ],
    [ "Is", "class_aspose_1_1_words_1_1_table_style.html#is_typeinfo_const", null ],
    [ "set_Alignment", "class_aspose_1_1_words_1_1_table_style.html#set_alignment", null ],
    [ "set_AllowBreakAcrossPages", "class_aspose_1_1_words_1_1_table_style.html#set_allowbreakacrosspages", null ],
    [ "set_Bidi", "class_aspose_1_1_words_1_1_table_style.html#set_bidi", null ],
    [ "set_BottomPadding", "class_aspose_1_1_words_1_1_table_style.html#set_bottompadding", null ],
    [ "set_CellSpacing", "class_aspose_1_1_words_1_1_table_style.html#set_cellspacing", null ],
    [ "set_ColumnStripe", "class_aspose_1_1_words_1_1_table_style.html#set_columnstripe", null ],
    [ "set_LeftIndent", "class_aspose_1_1_words_1_1_table_style.html#set_leftindent", null ],
    [ "set_LeftPadding", "class_aspose_1_1_words_1_1_table_style.html#set_leftpadding", null ],
    [ "set_RightPadding", "class_aspose_1_1_words_1_1_table_style.html#set_rightpadding", null ],
    [ "set_RowStripe", "class_aspose_1_1_words_1_1_table_style.html#set_rowstripe", null ],
    [ "set_TopPadding", "class_aspose_1_1_words_1_1_table_style.html#set_toppadding", null ],
    [ "set_VerticalAlignment", "class_aspose_1_1_words_1_1_table_style.html#set_verticalalignment", null ],
    [ "Type", "class_aspose_1_1_words_1_1_table_style.html#type", null ]
];