var class_aspose_1_1_words_1_1_themes_1_1_theme_colors =
[
    [ "get_Accent1", "class_aspose_1_1_words_1_1_themes_1_1_theme_colors.html#get_accent1", null ],
    [ "get_Accent2", "class_aspose_1_1_words_1_1_themes_1_1_theme_colors.html#get_accent2", null ],
    [ "get_Accent3", "class_aspose_1_1_words_1_1_themes_1_1_theme_colors.html#get_accent3", null ],
    [ "get_Accent4", "class_aspose_1_1_words_1_1_themes_1_1_theme_colors.html#get_accent4", null ],
    [ "get_Accent5", "class_aspose_1_1_words_1_1_themes_1_1_theme_colors.html#get_accent5", null ],
    [ "get_Accent6", "class_aspose_1_1_words_1_1_themes_1_1_theme_colors.html#get_accent6", null ],
    [ "get_Dark1", "class_aspose_1_1_words_1_1_themes_1_1_theme_colors.html#get_dark1", null ],
    [ "get_Dark2", "class_aspose_1_1_words_1_1_themes_1_1_theme_colors.html#get_dark2", null ],
    [ "get_FollowedHyperlink", "class_aspose_1_1_words_1_1_themes_1_1_theme_colors.html#get_followedhyperlink", null ],
    [ "get_Hyperlink", "class_aspose_1_1_words_1_1_themes_1_1_theme_colors.html#get_hyperlink", null ],
    [ "get_Light1", "class_aspose_1_1_words_1_1_themes_1_1_theme_colors.html#get_light1", null ],
    [ "get_Light2", "class_aspose_1_1_words_1_1_themes_1_1_theme_colors.html#get_light2", null ],
    [ "GetType", "class_aspose_1_1_words_1_1_themes_1_1_theme_colors.html#gettype_const", null ],
    [ "Is", "class_aspose_1_1_words_1_1_themes_1_1_theme_colors.html#is_typeinfo_const", null ],
    [ "set_Accent1", "class_aspose_1_1_words_1_1_themes_1_1_theme_colors.html#set_accent1", null ],
    [ "set_Accent2", "class_aspose_1_1_words_1_1_themes_1_1_theme_colors.html#set_accent2", null ],
    [ "set_Accent3", "class_aspose_1_1_words_1_1_themes_1_1_theme_colors.html#set_accent3", null ],
    [ "set_Accent4", "class_aspose_1_1_words_1_1_themes_1_1_theme_colors.html#set_accent4", null ],
    [ "set_Accent5", "class_aspose_1_1_words_1_1_themes_1_1_theme_colors.html#set_accent5", null ],
    [ "set_Accent6", "class_aspose_1_1_words_1_1_themes_1_1_theme_colors.html#set_accent6", null ],
    [ "set_Dark1", "class_aspose_1_1_words_1_1_themes_1_1_theme_colors.html#set_dark1", null ],
    [ "set_Dark2", "class_aspose_1_1_words_1_1_themes_1_1_theme_colors.html#set_dark2", null ],
    [ "set_FollowedHyperlink", "class_aspose_1_1_words_1_1_themes_1_1_theme_colors.html#set_followedhyperlink", null ],
    [ "set_Hyperlink", "class_aspose_1_1_words_1_1_themes_1_1_theme_colors.html#set_hyperlink", null ],
    [ "set_Light1", "class_aspose_1_1_words_1_1_themes_1_1_theme_colors.html#set_light1", null ],
    [ "set_Light2", "class_aspose_1_1_words_1_1_themes_1_1_theme_colors.html#set_light2", null ],
    [ "Type", "class_aspose_1_1_words_1_1_themes_1_1_theme_colors.html#type", null ]
];