var class_aspose_1_1_words_1_1_border_collection =
[
    [ "ClearFormatting", "class_aspose_1_1_words_1_1_border_collection.html#clearformatting", null ],
    [ "Equals", "class_aspose_1_1_words_1_1_border_collection.html#equals_bordercollection", null ],
    [ "get_Bottom", "class_aspose_1_1_words_1_1_border_collection.html#get_bottom", null ],
    [ "get_Color", "class_aspose_1_1_words_1_1_border_collection.html#get_color", null ],
    [ "get_Count", "class_aspose_1_1_words_1_1_border_collection.html#get_count", null ],
    [ "get_DistanceFromText", "class_aspose_1_1_words_1_1_border_collection.html#get_distancefromtext", null ],
    [ "get_Horizontal", "class_aspose_1_1_words_1_1_border_collection.html#get_horizontal", null ],
    [ "get_Left", "class_aspose_1_1_words_1_1_border_collection.html#get_left", null ],
    [ "get_LineStyle", "class_aspose_1_1_words_1_1_border_collection.html#get_linestyle", null ],
    [ "get_LineWidth", "class_aspose_1_1_words_1_1_border_collection.html#get_linewidth", null ],
    [ "get_Right", "class_aspose_1_1_words_1_1_border_collection.html#get_right", null ],
    [ "get_Shadow", "class_aspose_1_1_words_1_1_border_collection.html#get_shadow", null ],
    [ "get_Top", "class_aspose_1_1_words_1_1_border_collection.html#get_top", null ],
    [ "get_Vertical", "class_aspose_1_1_words_1_1_border_collection.html#get_vertical", null ],
    [ "GetEnumerator", "class_aspose_1_1_words_1_1_border_collection.html#getenumerator", null ],
    [ "GetType", "class_aspose_1_1_words_1_1_border_collection.html#gettype_const", null ],
    [ "idx_get", "class_aspose_1_1_words_1_1_border_collection.html#idx_get_bordertype", null ],
    [ "idx_get", "class_aspose_1_1_words_1_1_border_collection.html#idx_get_int", null ],
    [ "Is", "class_aspose_1_1_words_1_1_border_collection.html#is_typeinfo_const", null ],
    [ "set_Color", "class_aspose_1_1_words_1_1_border_collection.html#set_color", null ],
    [ "set_DistanceFromText", "class_aspose_1_1_words_1_1_border_collection.html#set_distancefromtext", null ],
    [ "set_LineStyle", "class_aspose_1_1_words_1_1_border_collection.html#set_linestyle", null ],
    [ "set_LineWidth", "class_aspose_1_1_words_1_1_border_collection.html#set_linewidth", null ],
    [ "set_Shadow", "class_aspose_1_1_words_1_1_border_collection.html#set_shadow", null ],
    [ "Type", "class_aspose_1_1_words_1_1_border_collection.html#type", null ]
];