var class_aspose_1_1_words_1_1_control_char =
[
    [ "ControlChar", "class_aspose_1_1_words_1_1_control_char.html#controlchar", null ],
    [ "Cell", "class_aspose_1_1_words_1_1_control_char.html#cell", null ],
    [ "ColumnBreak", "class_aspose_1_1_words_1_1_control_char.html#columnbreak", null ],
    [ "Cr", "class_aspose_1_1_words_1_1_control_char.html#cr", null ],
    [ "CrLf", "class_aspose_1_1_words_1_1_control_char.html#crlf", null ],
    [ "Lf", "class_aspose_1_1_words_1_1_control_char.html#lf", null ],
    [ "LineBreak", "class_aspose_1_1_words_1_1_control_char.html#linebreak", null ],
    [ "LineFeed", "class_aspose_1_1_words_1_1_control_char.html#linefeed", null ],
    [ "NonBreakingSpace", "class_aspose_1_1_words_1_1_control_char.html#nonbreakingspace", null ],
    [ "PageBreak", "class_aspose_1_1_words_1_1_control_char.html#pagebreak", null ],
    [ "ParagraphBreak", "class_aspose_1_1_words_1_1_control_char.html#paragraphbreak", null ],
    [ "SectionBreak", "class_aspose_1_1_words_1_1_control_char.html#sectionbreak", null ],
    [ "Tab", "class_aspose_1_1_words_1_1_control_char.html#tab", null ],
    [ "CellChar", "class_aspose_1_1_words_1_1_control_char.html#cellchar", null ],
    [ "ColumnBreakChar", "class_aspose_1_1_words_1_1_control_char.html#columnbreakchar", null ],
    [ "DefaultTextInputChar", "class_aspose_1_1_words_1_1_control_char.html#defaulttextinputchar", null ],
    [ "FieldEndChar", "class_aspose_1_1_words_1_1_control_char.html#fieldendchar", null ],
    [ "FieldSeparatorChar", "class_aspose_1_1_words_1_1_control_char.html#fieldseparatorchar", null ],
    [ "FieldStartChar", "class_aspose_1_1_words_1_1_control_char.html#fieldstartchar", null ],
    [ "LineBreakChar", "class_aspose_1_1_words_1_1_control_char.html#linebreakchar", null ],
    [ "LineFeedChar", "class_aspose_1_1_words_1_1_control_char.html#linefeedchar", null ],
    [ "NonBreakingHyphenChar", "class_aspose_1_1_words_1_1_control_char.html#nonbreakinghyphenchar", null ],
    [ "NonBreakingSpaceChar", "class_aspose_1_1_words_1_1_control_char.html#nonbreakingspacechar", null ],
    [ "OptionalHyphenChar", "class_aspose_1_1_words_1_1_control_char.html#optionalhyphenchar", null ],
    [ "PageBreakChar", "class_aspose_1_1_words_1_1_control_char.html#pagebreakchar", null ],
    [ "ParagraphBreakChar", "class_aspose_1_1_words_1_1_control_char.html#paragraphbreakchar", null ],
    [ "SectionBreakChar", "class_aspose_1_1_words_1_1_control_char.html#sectionbreakchar", null ],
    [ "SpaceChar", "class_aspose_1_1_words_1_1_control_char.html#spacechar", null ],
    [ "TabChar", "class_aspose_1_1_words_1_1_control_char.html#tabchar", null ]
];