var namespace_aspose_1_1_words_1_1_settings =
[
    [ "CompatibilityOptions", "class_aspose_1_1_words_1_1_settings_1_1_compatibility_options.html", "class_aspose_1_1_words_1_1_settings_1_1_compatibility_options" ],
    [ "HyphenationOptions", "class_aspose_1_1_words_1_1_settings_1_1_hyphenation_options.html", "class_aspose_1_1_words_1_1_settings_1_1_hyphenation_options" ],
    [ "MailMergeSettings", "class_aspose_1_1_words_1_1_settings_1_1_mail_merge_settings.html", "class_aspose_1_1_words_1_1_settings_1_1_mail_merge_settings" ],
    [ "Odso", "class_aspose_1_1_words_1_1_settings_1_1_odso.html", "class_aspose_1_1_words_1_1_settings_1_1_odso" ],
    [ "OdsoFieldMapData", "class_aspose_1_1_words_1_1_settings_1_1_odso_field_map_data.html", "class_aspose_1_1_words_1_1_settings_1_1_odso_field_map_data" ],
    [ "OdsoFieldMapDataCollection", "class_aspose_1_1_words_1_1_settings_1_1_odso_field_map_data_collection.html", "class_aspose_1_1_words_1_1_settings_1_1_odso_field_map_data_collection" ],
    [ "OdsoRecipientData", "class_aspose_1_1_words_1_1_settings_1_1_odso_recipient_data.html", "class_aspose_1_1_words_1_1_settings_1_1_odso_recipient_data" ],
    [ "OdsoRecipientDataCollection", "class_aspose_1_1_words_1_1_settings_1_1_odso_recipient_data_collection.html", "class_aspose_1_1_words_1_1_settings_1_1_odso_recipient_data_collection" ],
    [ "ViewOptions", "class_aspose_1_1_words_1_1_settings_1_1_view_options.html", "class_aspose_1_1_words_1_1_settings_1_1_view_options" ],
    [ "WriteProtection", "class_aspose_1_1_words_1_1_settings_1_1_write_protection.html", "class_aspose_1_1_words_1_1_settings_1_1_write_protection" ],
    [ "Compatibility", "namespace_aspose_1_1_words_1_1_settings.html#compatibility", [
      [ "NoTabHangInd", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_notabhangind", null ],
      [ "NoSpaceRaiseLower", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_nospaceraiselower", null ],
      [ "SuppressSpBfAfterPgBrk", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_suppressspbfafterpgbrk", null ],
      [ "WrapTrailSpaces", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_wraptrailspaces", null ],
      [ "PrintColBlack", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_printcolblack", null ],
      [ "NoColumnBalance", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_nocolumnbalance", null ],
      [ "ConvMailMergeEsc", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_convmailmergeesc", null ],
      [ "SuppressTopSpacing", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_suppresstopspacing", null ],
      [ "UseSingleBorderforContiguousCells", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_usesingleborderforcontiguouscells", null ],
      [ "TransparentMetafiles", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_transparentmetafiles", null ],
      [ "ShowBreaksInFrames", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_showbreaksinframes", null ],
      [ "SwapBordersOddFacingPgs", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_swapbordersoddfacingpgs", null ],
      [ "DoNotLeaveBackslashAlone", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_donotleavebackslashalone", null ],
      [ "DoNotExpandOnShiftReturn", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_donotexpandonshiftreturn", null ],
      [ "UlTrailSpace", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_ultrailspace", null ],
      [ "BalanceSingleByteDoubleByteWidth", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_balancesinglebytedoublebytewidth", null ],
      [ "SuppressTopSpacingAtTopOfPage", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_suppresstopspacingattopofpage", null ],
      [ "SpacingInWholePoints", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_spacinginwholepoints", null ],
      [ "PrintBodyTextBeforeHeader", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_printbodytextbeforeheader", null ],
      [ "NoLeading", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_noleading", null ],
      [ "SpaceForUL", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_spaceforul", null ],
      [ "MWSmallCaps", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_mwsmallcaps", null ],
      [ "SuppressTopLineSpacingWP", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_suppresstoplinespacingwp", null ],
      [ "TruncateFontHeightLikeWP6", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_truncatefontheightlikewp6", null ],
      [ "SubFontBySize", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_subfontbysize", null ],
      [ "LineWrapLikeWord6", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_linewraplikeword6", null ],
      [ "DoNotSuppressParagraphBorder", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_donotsuppressparagraphborder", null ],
      [ "NoExtraLineSpacing", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_noextralinespacing", null ],
      [ "SuppressBottomSpacing", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_suppressbottomspacing", null ],
      [ "WPSpaceWidth", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_wpspacewidth", null ],
      [ "WPJustification", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_wpjustification", null ],
      [ "UsePrinterMetrics", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_useprintermetrics", null ],
      [ "ShapeLayoutLikeWW8", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_shapelayoutlikeww8", null ],
      [ "FootnoteLayoutLikeWW8", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_footnotelayoutlikeww8", null ],
      [ "DoNotUseHtmlParagraphAutoSpacing", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_donotusehtmlparagraphautospacing", null ],
      [ "AdjustLineHeightInTable", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_adjustlineheightintable", null ],
      [ "ForgetLastTabAlignment", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_forgetlasttabalignment", null ],
      [ "AutoSpaceLikeWord95", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_autospacelikeword95", null ],
      [ "AlignTableRowByRow", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_aligntablerowbyrow", null ],
      [ "LayoutRawTableWidth", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_layoutrawtablewidth", null ],
      [ "LayoutTableRowsApart", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_layouttablerowsapart", null ],
      [ "UseWord97LineBreakRules", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_useword97linebreakrules", null ],
      [ "DoNotBreakWrappedTables", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_donotbreakwrappedtables", null ],
      [ "doNotSnapToGridInCell", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_donotsnaptogridincell", null ],
      [ "SelectFldWithFirstOrLastChar", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_selectfldwithfirstorlastchar", null ],
      [ "ApplyBreakingRules", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_applybreakingrules", null ],
      [ "DoNotWrapTextWithPunct", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_donotwraptextwithpunct", null ],
      [ "DoNotUseEastAsianBreakRules", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_donotuseeastasianbreakrules", null ],
      [ "UseWord2002TableStyleRules", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_useword2002tablestylerules", null ],
      [ "GrowAutofit", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_growautofit", null ],
      [ "UseNormalStyleForList", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_usenormalstyleforlist", null ],
      [ "DoNotUseIndentAsNumberingTabStop", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_donotuseindentasnumberingtabstop", null ],
      [ "UseAltKinsokuLineBreakRules", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_usealtkinsokulinebreakrules", null ],
      [ "AllowSpaceOfSameStyleInTable", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_allowspaceofsamestyleintable", null ],
      [ "DoNotSuppressIndentation", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_donotsuppressindentation", null ],
      [ "DoNotAutofitConstrainedTables", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_donotautofitconstrainedtables", null ],
      [ "AutofitToFirstFixedWidthCell", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_autofittofirstfixedwidthcell", null ],
      [ "UnderlineTabInNumList", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_underlinetabinnumlist", null ],
      [ "DisplayHangulFixedWidth", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_displayhangulfixedwidth", null ],
      [ "SplitPgBreakAndParaMark", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_splitpgbreakandparamark", null ],
      [ "DoNotVertAlignCellWithSp", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_donotvertaligncellwithsp", null ],
      [ "DoNotBreakConstrainedForcedTable", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_donotbreakconstrainedforcedtable", null ],
      [ "DoNotVertAlignInTxbx", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_donotvertalignintxbx", null ],
      [ "UseAnsiKerningPairs", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_useansikerningpairs", null ],
      [ "CachedColBalance", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_cachedcolbalance", null ],
      [ "UseFELayout", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_usefelayout", null ],
      [ "UICompat97To2003", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_uicompat97to2003", null ],
      [ "OverrideTableStyleFontSizeAndJustification", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_overridetablestylefontsizeandjustification", null ],
      [ "DisableOpenTypeFontFormattingFeatures", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_disableopentypefontformattingfeatures", null ],
      [ "SwapInsideAndOutsideForMirrorIndentsAndRelativePositioning", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_swapinsideandoutsideformirrorindentsandrelativepositioning", null ],
      [ "UseWord2010TableStyleRules", "namespace_aspose_1_1_words_1_1_settings.html#compatibility_useword2010tablestylerules", null ]
    ] ],
    [ "MailMergeCheckErrors", "namespace_aspose_1_1_words_1_1_settings.html#mailmergecheckerrors", [
      [ "Simulate", "namespace_aspose_1_1_words_1_1_settings.html#mailmergecheckerrors_simulate", null ],
      [ "PauseOnError", "namespace_aspose_1_1_words_1_1_settings.html#mailmergecheckerrors_pauseonerror", null ],
      [ "CollectErrors", "namespace_aspose_1_1_words_1_1_settings.html#mailmergecheckerrors_collecterrors", null ],
      [ "Default", "namespace_aspose_1_1_words_1_1_settings.html#mailmergecheckerrors_default", null ]
    ] ],
    [ "MailMergeDataType", "namespace_aspose_1_1_words_1_1_settings.html#mailmergedatatype", [
      [ "None", "namespace_aspose_1_1_words_1_1_settings.html#mailmergedatatype_none", null ],
      [ "TextFile", "namespace_aspose_1_1_words_1_1_settings.html#mailmergedatatype_textfile", null ],
      [ "Database", "namespace_aspose_1_1_words_1_1_settings.html#mailmergedatatype_database", null ],
      [ "Spreadsheet", "namespace_aspose_1_1_words_1_1_settings.html#mailmergedatatype_spreadsheet", null ],
      [ "Query", "namespace_aspose_1_1_words_1_1_settings.html#mailmergedatatype_query", null ],
      [ "Odbc", "namespace_aspose_1_1_words_1_1_settings.html#mailmergedatatype_odbc", null ],
      [ "Native", "namespace_aspose_1_1_words_1_1_settings.html#mailmergedatatype_native", null ],
      [ "Default", "namespace_aspose_1_1_words_1_1_settings.html#mailmergedatatype_default", null ]
    ] ],
    [ "MailMergeDestination", "namespace_aspose_1_1_words_1_1_settings.html#mailmergedestination", [
      [ "NewDocument", "namespace_aspose_1_1_words_1_1_settings.html#mailmergedestination_newdocument", null ],
      [ "Printer", "namespace_aspose_1_1_words_1_1_settings.html#mailmergedestination_printer", null ],
      [ "Email", "namespace_aspose_1_1_words_1_1_settings.html#mailmergedestination_email", null ],
      [ "Fax", "namespace_aspose_1_1_words_1_1_settings.html#mailmergedestination_fax", null ],
      [ "Default", "namespace_aspose_1_1_words_1_1_settings.html#mailmergedestination_default", null ]
    ] ],
    [ "MailMergeMainDocumentType", "namespace_aspose_1_1_words_1_1_settings.html#mailmergemaindocumenttype", [
      [ "NotAMergeDocument", "namespace_aspose_1_1_words_1_1_settings.html#mailmergemaindocumenttype_notamergedocument", null ],
      [ "FormLetters", "namespace_aspose_1_1_words_1_1_settings.html#mailmergemaindocumenttype_formletters", null ],
      [ "MailingLabels", "namespace_aspose_1_1_words_1_1_settings.html#mailmergemaindocumenttype_mailinglabels", null ],
      [ "Envelopes", "namespace_aspose_1_1_words_1_1_settings.html#mailmergemaindocumenttype_envelopes", null ],
      [ "Catalog", "namespace_aspose_1_1_words_1_1_settings.html#mailmergemaindocumenttype_catalog", null ],
      [ "Email", "namespace_aspose_1_1_words_1_1_settings.html#mailmergemaindocumenttype_email", null ],
      [ "Fax", "namespace_aspose_1_1_words_1_1_settings.html#mailmergemaindocumenttype_fax", null ],
      [ "Default", "namespace_aspose_1_1_words_1_1_settings.html#mailmergemaindocumenttype_default", null ]
    ] ],
    [ "MsWordVersion", "namespace_aspose_1_1_words_1_1_settings.html#mswordversion", [
      [ "Word2000", "namespace_aspose_1_1_words_1_1_settings.html#mswordversion_word2000", null ],
      [ "Word2002", "namespace_aspose_1_1_words_1_1_settings.html#mswordversion_word2002", null ],
      [ "Word2003", "namespace_aspose_1_1_words_1_1_settings.html#mswordversion_word2003", null ],
      [ "Word2007", "namespace_aspose_1_1_words_1_1_settings.html#mswordversion_word2007", null ],
      [ "Word2010", "namespace_aspose_1_1_words_1_1_settings.html#mswordversion_word2010", null ],
      [ "Word2013", "namespace_aspose_1_1_words_1_1_settings.html#mswordversion_word2013", null ],
      [ "Word2016", "namespace_aspose_1_1_words_1_1_settings.html#mswordversion_word2016", null ],
      [ "Word2019", "namespace_aspose_1_1_words_1_1_settings.html#mswordversion_word2019", null ]
    ] ],
    [ "MultiplePagesType", "namespace_aspose_1_1_words_1_1_settings.html#multiplepagestype", [
      [ "Normal", "namespace_aspose_1_1_words_1_1_settings.html#multiplepagestype_normal", null ],
      [ "MirrorMargins", "namespace_aspose_1_1_words_1_1_settings.html#multiplepagestype_mirrormargins", null ],
      [ "TwoPagesPerSheet", "namespace_aspose_1_1_words_1_1_settings.html#multiplepagestype_twopagespersheet", null ],
      [ "BookFoldPrinting", "namespace_aspose_1_1_words_1_1_settings.html#multiplepagestype_bookfoldprinting", null ],
      [ "BookFoldPrintingReverse", "namespace_aspose_1_1_words_1_1_settings.html#multiplepagestype_bookfoldprintingreverse", null ],
      [ "Default", "namespace_aspose_1_1_words_1_1_settings.html#multiplepagestype_default", null ]
    ] ],
    [ "OdsoDataSourceType", "namespace_aspose_1_1_words_1_1_settings.html#odsodatasourcetype", [
      [ "Text", "namespace_aspose_1_1_words_1_1_settings.html#odsodatasourcetype_text", null ],
      [ "Database", "namespace_aspose_1_1_words_1_1_settings.html#odsodatasourcetype_database", null ],
      [ "AddressBook", "namespace_aspose_1_1_words_1_1_settings.html#odsodatasourcetype_addressbook", null ],
      [ "Document1", "namespace_aspose_1_1_words_1_1_settings.html#odsodatasourcetype_document1", null ],
      [ "Document2", "namespace_aspose_1_1_words_1_1_settings.html#odsodatasourcetype_document2", null ],
      [ "Native", "namespace_aspose_1_1_words_1_1_settings.html#odsodatasourcetype_native", null ],
      [ "Email", "namespace_aspose_1_1_words_1_1_settings.html#odsodatasourcetype_email", null ],
      [ "None", "namespace_aspose_1_1_words_1_1_settings.html#odsodatasourcetype_none", null ],
      [ "Legacy", "namespace_aspose_1_1_words_1_1_settings.html#odsodatasourcetype_legacy", null ],
      [ "Master", "namespace_aspose_1_1_words_1_1_settings.html#odsodatasourcetype_master", null ],
      [ "Default", "namespace_aspose_1_1_words_1_1_settings.html#odsodatasourcetype_default", null ]
    ] ],
    [ "OdsoFieldMappingType", "namespace_aspose_1_1_words_1_1_settings.html#odsofieldmappingtype", [
      [ "Column", "namespace_aspose_1_1_words_1_1_settings.html#odsofieldmappingtype_column", null ],
      [ "Null", "namespace_aspose_1_1_words_1_1_settings.html#odsofieldmappingtype_null", null ],
      [ "Default", "namespace_aspose_1_1_words_1_1_settings.html#odsofieldmappingtype_default", null ]
    ] ],
    [ "ViewType", "namespace_aspose_1_1_words_1_1_settings.html#viewtype", [
      [ "None", "namespace_aspose_1_1_words_1_1_settings.html#viewtype_none", null ],
      [ "Reading", "namespace_aspose_1_1_words_1_1_settings.html#viewtype_reading", null ],
      [ "PageLayout", "namespace_aspose_1_1_words_1_1_settings.html#viewtype_pagelayout", null ],
      [ "Outline", "namespace_aspose_1_1_words_1_1_settings.html#viewtype_outline", null ],
      [ "Normal", "namespace_aspose_1_1_words_1_1_settings.html#viewtype_normal", null ],
      [ "Web", "namespace_aspose_1_1_words_1_1_settings.html#viewtype_web", null ]
    ] ],
    [ "ZoomType", "namespace_aspose_1_1_words_1_1_settings.html#zoomtype", [
      [ "Custom", "namespace_aspose_1_1_words_1_1_settings.html#zoomtype_custom", null ],
      [ "None", "namespace_aspose_1_1_words_1_1_settings.html#zoomtype_none", null ],
      [ "FullPage", "namespace_aspose_1_1_words_1_1_settings.html#zoomtype_fullpage", null ],
      [ "PageWidth", "namespace_aspose_1_1_words_1_1_settings.html#zoomtype_pagewidth", null ],
      [ "TextFit", "namespace_aspose_1_1_words_1_1_settings.html#zoomtype_textfit", null ]
    ] ]
];