var namespace_aspose_1_1_words_1_1_building_blocks =
[
    [ "BuildingBlock", "class_aspose_1_1_words_1_1_building_blocks_1_1_building_block.html", "class_aspose_1_1_words_1_1_building_blocks_1_1_building_block" ],
    [ "BuildingBlockCollection", "class_aspose_1_1_words_1_1_building_blocks_1_1_building_block_collection.html", "class_aspose_1_1_words_1_1_building_blocks_1_1_building_block_collection" ],
    [ "GlossaryDocument", "class_aspose_1_1_words_1_1_building_blocks_1_1_glossary_document.html", "class_aspose_1_1_words_1_1_building_blocks_1_1_glossary_document" ],
    [ "BuildingBlockBehavior", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockbehavior", [
      [ "Content", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockbehavior_content", null ],
      [ "Paragraph", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockbehavior_paragraph", null ],
      [ "Page", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockbehavior_page", null ],
      [ "Default", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockbehavior_default", null ]
    ] ],
    [ "BuildingBlockGallery", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockgallery", [
      [ "All", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockgallery_all", null ],
      [ "AutoText", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockgallery_autotext", null ],
      [ "Bibliography", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockgallery_bibliography", null ],
      [ "CoverPage", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockgallery_coverpage", null ],
      [ "CustomAutoText", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockgallery_customautotext", null ],
      [ "CustomBibliography", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockgallery_custombibliography", null ],
      [ "CustomCoverPage", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockgallery_customcoverpage", null ],
      [ "CustomEquations", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockgallery_customequations", null ],
      [ "CustomFooters", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockgallery_customfooters", null ],
      [ "CustomHeaders", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockgallery_customheaders", null ],
      [ "Custom1", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockgallery_custom1", null ],
      [ "Custom2", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockgallery_custom2", null ],
      [ "Custom3", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockgallery_custom3", null ],
      [ "Custom4", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockgallery_custom4", null ],
      [ "Custom5", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockgallery_custom5", null ],
      [ "CustomPageNumber", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockgallery_custompagenumber", null ],
      [ "CustomPageNumberAtBottom", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockgallery_custompagenumberatbottom", null ],
      [ "CustomPageNumberAtMargin", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockgallery_custompagenumberatmargin", null ],
      [ "CustomPageNumberAtTop", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockgallery_custompagenumberattop", null ],
      [ "CustomQuickParts", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockgallery_customquickparts", null ],
      [ "CustomTableOfContents", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockgallery_customtableofcontents", null ],
      [ "CustomTables", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockgallery_customtables", null ],
      [ "CustomTextBox", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockgallery_customtextbox", null ],
      [ "CustomWatermarks", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockgallery_customwatermarks", null ],
      [ "NoGallery", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockgallery_nogallery", null ],
      [ "QuickParts", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockgallery_quickparts", null ],
      [ "Equations", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockgallery_equations", null ],
      [ "Footers", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockgallery_footers", null ],
      [ "Headers", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockgallery_headers", null ],
      [ "PageNumber", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockgallery_pagenumber", null ],
      [ "PageNumberAtBottom", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockgallery_pagenumberatbottom", null ],
      [ "PageNumberAtMargin", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockgallery_pagenumberatmargin", null ],
      [ "PageNumberAtTop", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockgallery_pagenumberattop", null ],
      [ "StructuredDocumentTagPlaceholderText", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockgallery_structureddocumenttagplaceholdertext", null ],
      [ "TableOfContents", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockgallery_tableofcontents", null ],
      [ "Tables", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockgallery_tables", null ],
      [ "TextBox", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockgallery_textbox", null ],
      [ "Watermarks", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockgallery_watermarks", null ],
      [ "Default", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblockgallery_default", null ]
    ] ],
    [ "BuildingBlockType", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblocktype", [
      [ "None", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblocktype_none", null ],
      [ "AutomaticallyReplaceNameWithContent", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblocktype_automaticallyreplacenamewithcontent", null ],
      [ "StructuredDocumentTagPlaceholderText", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblocktype_structureddocumenttagplaceholdertext", null ],
      [ "FormFieldHelpText", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblocktype_formfieldhelptext", null ],
      [ "Normal", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblocktype_normal", null ],
      [ "AutoCorrect", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblocktype_autocorrect", null ],
      [ "AutoText", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblocktype_autotext", null ],
      [ "All", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblocktype_all", null ],
      [ "Default", "namespace_aspose_1_1_words_1_1_building_blocks.html#buildingblocktype_default", null ]
    ] ]
];