var namespace_aspose_1_1_words_1_1_drawing =
[
    [ "Charts", "namespace_aspose_1_1_words_1_1_drawing_1_1_charts.html", "namespace_aspose_1_1_words_1_1_drawing_1_1_charts" ],
    [ "Core", "namespace_aspose_1_1_words_1_1_drawing_1_1_core.html", null ],
    [ "Fill", "class_aspose_1_1_words_1_1_drawing_1_1_fill.html", "class_aspose_1_1_words_1_1_drawing_1_1_fill" ],
    [ "GradientStop", "class_aspose_1_1_words_1_1_drawing_1_1_gradient_stop.html", "class_aspose_1_1_words_1_1_drawing_1_1_gradient_stop" ],
    [ "GradientStopCollection", "class_aspose_1_1_words_1_1_drawing_1_1_gradient_stop_collection.html", "class_aspose_1_1_words_1_1_drawing_1_1_gradient_stop_collection" ],
    [ "GroupShape", "class_aspose_1_1_words_1_1_drawing_1_1_group_shape.html", "class_aspose_1_1_words_1_1_drawing_1_1_group_shape" ],
    [ "HorizontalRuleFormat", "class_aspose_1_1_words_1_1_drawing_1_1_horizontal_rule_format.html", "class_aspose_1_1_words_1_1_drawing_1_1_horizontal_rule_format" ],
    [ "ImageData", "class_aspose_1_1_words_1_1_drawing_1_1_image_data.html", "class_aspose_1_1_words_1_1_drawing_1_1_image_data" ],
    [ "ImageSize", "class_aspose_1_1_words_1_1_drawing_1_1_image_size.html", "class_aspose_1_1_words_1_1_drawing_1_1_image_size" ],
    [ "OleFormat", "class_aspose_1_1_words_1_1_drawing_1_1_ole_format.html", "class_aspose_1_1_words_1_1_drawing_1_1_ole_format" ],
    [ "OlePackage", "class_aspose_1_1_words_1_1_drawing_1_1_ole_package.html", "class_aspose_1_1_words_1_1_drawing_1_1_ole_package" ],
    [ "Shape", "class_aspose_1_1_words_1_1_drawing_1_1_shape.html", "class_aspose_1_1_words_1_1_drawing_1_1_shape" ],
    [ "ShapeBase", "class_aspose_1_1_words_1_1_drawing_1_1_shape_base.html", "class_aspose_1_1_words_1_1_drawing_1_1_shape_base" ],
    [ "SignatureLine", "class_aspose_1_1_words_1_1_drawing_1_1_signature_line.html", "class_aspose_1_1_words_1_1_drawing_1_1_signature_line" ],
    [ "Stroke", "class_aspose_1_1_words_1_1_drawing_1_1_stroke.html", "class_aspose_1_1_words_1_1_drawing_1_1_stroke" ],
    [ "TextBox", "class_aspose_1_1_words_1_1_drawing_1_1_text_box.html", "class_aspose_1_1_words_1_1_drawing_1_1_text_box" ],
    [ "TextPath", "class_aspose_1_1_words_1_1_drawing_1_1_text_path.html", "class_aspose_1_1_words_1_1_drawing_1_1_text_path" ],
    [ "ArrowLength", "namespace_aspose_1_1_words_1_1_drawing.html#arrowlength", [
      [ "Short", "namespace_aspose_1_1_words_1_1_drawing.html#arrowlength_short", null ],
      [ "Medium", "namespace_aspose_1_1_words_1_1_drawing.html#arrowlength_medium", null ],
      [ "Long", "namespace_aspose_1_1_words_1_1_drawing.html#arrowlength_long", null ],
      [ "Default", "namespace_aspose_1_1_words_1_1_drawing.html#arrowlength_default", null ]
    ] ],
    [ "ArrowType", "namespace_aspose_1_1_words_1_1_drawing.html#arrowtype", [
      [ "None", "namespace_aspose_1_1_words_1_1_drawing.html#arrowtype_none", null ],
      [ "Arrow", "namespace_aspose_1_1_words_1_1_drawing.html#arrowtype_arrow", null ],
      [ "Stealth", "namespace_aspose_1_1_words_1_1_drawing.html#arrowtype_stealth", null ],
      [ "Diamond", "namespace_aspose_1_1_words_1_1_drawing.html#arrowtype_diamond", null ],
      [ "Oval", "namespace_aspose_1_1_words_1_1_drawing.html#arrowtype_oval", null ],
      [ "Open", "namespace_aspose_1_1_words_1_1_drawing.html#arrowtype_open", null ],
      [ "Default", "namespace_aspose_1_1_words_1_1_drawing.html#arrowtype_default", null ]
    ] ],
    [ "ArrowWidth", "namespace_aspose_1_1_words_1_1_drawing.html#arrowwidth", [
      [ "Narrow", "namespace_aspose_1_1_words_1_1_drawing.html#arrowwidth_narrow", null ],
      [ "Medium", "namespace_aspose_1_1_words_1_1_drawing.html#arrowwidth_medium", null ],
      [ "Wide", "namespace_aspose_1_1_words_1_1_drawing.html#arrowwidth_wide", null ],
      [ "Default", "namespace_aspose_1_1_words_1_1_drawing.html#arrowwidth_default", null ]
    ] ],
    [ "DashStyle", "namespace_aspose_1_1_words_1_1_drawing.html#dashstyle", [
      [ "Solid", "namespace_aspose_1_1_words_1_1_drawing.html#dashstyle_solid", null ],
      [ "ShortDash", "namespace_aspose_1_1_words_1_1_drawing.html#dashstyle_shortdash", null ],
      [ "ShortDot", "namespace_aspose_1_1_words_1_1_drawing.html#dashstyle_shortdot", null ],
      [ "ShortDashDot", "namespace_aspose_1_1_words_1_1_drawing.html#dashstyle_shortdashdot", null ],
      [ "ShortDashDotDot", "namespace_aspose_1_1_words_1_1_drawing.html#dashstyle_shortdashdotdot", null ],
      [ "Dot", "namespace_aspose_1_1_words_1_1_drawing.html#dashstyle_dot", null ],
      [ "Dash", "namespace_aspose_1_1_words_1_1_drawing.html#dashstyle_dash", null ],
      [ "LongDash", "namespace_aspose_1_1_words_1_1_drawing.html#dashstyle_longdash", null ],
      [ "DashDot", "namespace_aspose_1_1_words_1_1_drawing.html#dashstyle_dashdot", null ],
      [ "LongDashDot", "namespace_aspose_1_1_words_1_1_drawing.html#dashstyle_longdashdot", null ],
      [ "LongDashDotDot", "namespace_aspose_1_1_words_1_1_drawing.html#dashstyle_longdashdotdot", null ],
      [ "Default", "namespace_aspose_1_1_words_1_1_drawing.html#dashstyle_default", null ]
    ] ],
    [ "EndCap", "namespace_aspose_1_1_words_1_1_drawing.html#endcap", [
      [ "Round", "namespace_aspose_1_1_words_1_1_drawing.html#endcap_round", null ],
      [ "Square", "namespace_aspose_1_1_words_1_1_drawing.html#endcap_square", null ],
      [ "Flat", "namespace_aspose_1_1_words_1_1_drawing.html#endcap_flat", null ],
      [ "Default", "namespace_aspose_1_1_words_1_1_drawing.html#endcap_default", null ]
    ] ],
    [ "FillType", "namespace_aspose_1_1_words_1_1_drawing.html#filltype", [
      [ "Solid", "namespace_aspose_1_1_words_1_1_drawing.html#filltype_solid", null ],
      [ "Patterned", "namespace_aspose_1_1_words_1_1_drawing.html#filltype_patterned", null ],
      [ "Gradient", "namespace_aspose_1_1_words_1_1_drawing.html#filltype_gradient", null ],
      [ "Textured", "namespace_aspose_1_1_words_1_1_drawing.html#filltype_textured", null ],
      [ "Background", "namespace_aspose_1_1_words_1_1_drawing.html#filltype_background", null ],
      [ "Picture", "namespace_aspose_1_1_words_1_1_drawing.html#filltype_picture", null ]
    ] ],
    [ "FlipOrientation", "namespace_aspose_1_1_words_1_1_drawing.html#fliporientation", [
      [ "None", "namespace_aspose_1_1_words_1_1_drawing.html#fliporientation_none", null ],
      [ "Horizontal", "namespace_aspose_1_1_words_1_1_drawing.html#fliporientation_horizontal", null ],
      [ "Vertical", "namespace_aspose_1_1_words_1_1_drawing.html#fliporientation_vertical", null ],
      [ "Both", "namespace_aspose_1_1_words_1_1_drawing.html#fliporientation_both", null ]
    ] ],
    [ "GradientStyle", "namespace_aspose_1_1_words_1_1_drawing.html#gradientstyle", [
      [ "None", "namespace_aspose_1_1_words_1_1_drawing.html#gradientstyle_none", null ],
      [ "Horizontal", "namespace_aspose_1_1_words_1_1_drawing.html#gradientstyle_horizontal", null ],
      [ "Vertical", "namespace_aspose_1_1_words_1_1_drawing.html#gradientstyle_vertical", null ],
      [ "DiagonalUp", "namespace_aspose_1_1_words_1_1_drawing.html#gradientstyle_diagonalup", null ],
      [ "DiagonalDown", "namespace_aspose_1_1_words_1_1_drawing.html#gradientstyle_diagonaldown", null ],
      [ "FromCorner", "namespace_aspose_1_1_words_1_1_drawing.html#gradientstyle_fromcorner", null ],
      [ "FromCenter", "namespace_aspose_1_1_words_1_1_drawing.html#gradientstyle_fromcenter", null ]
    ] ],
    [ "GradientVariant", "namespace_aspose_1_1_words_1_1_drawing.html#gradientvariant", [
      [ "None", "namespace_aspose_1_1_words_1_1_drawing.html#gradientvariant_none", null ],
      [ "Variant1", "namespace_aspose_1_1_words_1_1_drawing.html#gradientvariant_variant1", null ],
      [ "Variant2", "namespace_aspose_1_1_words_1_1_drawing.html#gradientvariant_variant2", null ],
      [ "Variant3", "namespace_aspose_1_1_words_1_1_drawing.html#gradientvariant_variant3", null ],
      [ "Variant4", "namespace_aspose_1_1_words_1_1_drawing.html#gradientvariant_variant4", null ]
    ] ],
    [ "HorizontalAlignment", "namespace_aspose_1_1_words_1_1_drawing.html#horizontalalignment", [
      [ "None", "namespace_aspose_1_1_words_1_1_drawing.html#horizontalalignment_none", null ],
      [ "Default", "namespace_aspose_1_1_words_1_1_drawing.html#horizontalalignment_default", null ],
      [ "Left", "namespace_aspose_1_1_words_1_1_drawing.html#horizontalalignment_left", null ],
      [ "Center", "namespace_aspose_1_1_words_1_1_drawing.html#horizontalalignment_center", null ],
      [ "Right", "namespace_aspose_1_1_words_1_1_drawing.html#horizontalalignment_right", null ],
      [ "Inside", "namespace_aspose_1_1_words_1_1_drawing.html#horizontalalignment_inside", null ],
      [ "Outside", "namespace_aspose_1_1_words_1_1_drawing.html#horizontalalignment_outside", null ]
    ] ],
    [ "HorizontalRuleAlignment", "namespace_aspose_1_1_words_1_1_drawing.html#horizontalrulealignment", [
      [ "Left", "namespace_aspose_1_1_words_1_1_drawing.html#horizontalrulealignment_left", null ],
      [ "Center", "namespace_aspose_1_1_words_1_1_drawing.html#horizontalrulealignment_center", null ],
      [ "Right", "namespace_aspose_1_1_words_1_1_drawing.html#horizontalrulealignment_right", null ]
    ] ],
    [ "ImageType", "namespace_aspose_1_1_words_1_1_drawing.html#imagetype", [
      [ "NoImage", "namespace_aspose_1_1_words_1_1_drawing.html#imagetype_noimage", null ],
      [ "Unknown", "namespace_aspose_1_1_words_1_1_drawing.html#imagetype_unknown", null ],
      [ "Emf", "namespace_aspose_1_1_words_1_1_drawing.html#imagetype_emf", null ],
      [ "Wmf", "namespace_aspose_1_1_words_1_1_drawing.html#imagetype_wmf", null ],
      [ "Pict", "namespace_aspose_1_1_words_1_1_drawing.html#imagetype_pict", null ],
      [ "Jpeg", "namespace_aspose_1_1_words_1_1_drawing.html#imagetype_jpeg", null ],
      [ "Png", "namespace_aspose_1_1_words_1_1_drawing.html#imagetype_png", null ],
      [ "Bmp", "namespace_aspose_1_1_words_1_1_drawing.html#imagetype_bmp", null ]
    ] ],
    [ "JoinStyle", "namespace_aspose_1_1_words_1_1_drawing.html#joinstyle", [
      [ "Bevel", "namespace_aspose_1_1_words_1_1_drawing.html#joinstyle_bevel", null ],
      [ "Miter", "namespace_aspose_1_1_words_1_1_drawing.html#joinstyle_miter", null ],
      [ "Round", "namespace_aspose_1_1_words_1_1_drawing.html#joinstyle_round", null ]
    ] ],
    [ "LayoutFlow", "namespace_aspose_1_1_words_1_1_drawing.html#layoutflow", [
      [ "Horizontal", "namespace_aspose_1_1_words_1_1_drawing.html#layoutflow_horizontal", null ],
      [ "TopToBottomIdeographic", "namespace_aspose_1_1_words_1_1_drawing.html#layoutflow_toptobottomideographic", null ],
      [ "BottomToTop", "namespace_aspose_1_1_words_1_1_drawing.html#layoutflow_bottomtotop", null ],
      [ "TopToBottom", "namespace_aspose_1_1_words_1_1_drawing.html#layoutflow_toptobottom", null ],
      [ "HorizontalIdeographic", "namespace_aspose_1_1_words_1_1_drawing.html#layoutflow_horizontalideographic", null ],
      [ "Vertical", "namespace_aspose_1_1_words_1_1_drawing.html#layoutflow_vertical", null ]
    ] ],
    [ "PatternType", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype", [
      [ "None", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_none", null ],
      [ "Percent10", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_percent10", null ],
      [ "Percent20", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_percent20", null ],
      [ "Percent25", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_percent25", null ],
      [ "Percent30", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_percent30", null ],
      [ "Percent40", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_percent40", null ],
      [ "Percent50", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_percent50", null ],
      [ "Percent5", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_percent5", null ],
      [ "Percent60", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_percent60", null ],
      [ "Percent70", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_percent70", null ],
      [ "Percent75", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_percent75", null ],
      [ "Percent80", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_percent80", null ],
      [ "Percent90", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_percent90", null ],
      [ "Cross", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_cross", null ],
      [ "DarkDownwardDiagonal", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_darkdownwarddiagonal", null ],
      [ "DarkHorizontal", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_darkhorizontal", null ],
      [ "DarkUpwardDiagonal", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_darkupwarddiagonal", null ],
      [ "DarkVertical", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_darkvertical", null ],
      [ "DashedDownwardDiagonal", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_dasheddownwarddiagonal", null ],
      [ "DashedHorizontal", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_dashedhorizontal", null ],
      [ "DashedUpwardDiagonal", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_dashedupwarddiagonal", null ],
      [ "DashedVertical", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_dashedvertical", null ],
      [ "DiagonalBrick", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_diagonalbrick", null ],
      [ "DiagonalCross", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_diagonalcross", null ],
      [ "Divot", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_divot", null ],
      [ "DottedDiamond", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_dotteddiamond", null ],
      [ "DottedGrid", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_dottedgrid", null ],
      [ "DownwardDiagonal", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_downwarddiagonal", null ],
      [ "Horizontal", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_horizontal", null ],
      [ "HorizontalBrick", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_horizontalbrick", null ],
      [ "LargeCheckerBoard", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_largecheckerboard", null ],
      [ "LargeConfetti", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_largeconfetti", null ],
      [ "LargeGrid", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_largegrid", null ],
      [ "LightDownwardDiagonal", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_lightdownwarddiagonal", null ],
      [ "LightHorizontal", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_lighthorizontal", null ],
      [ "LightUpwardDiagonal", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_lightupwarddiagonal", null ],
      [ "LightVertical", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_lightvertical", null ],
      [ "NarrowHorizontal", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_narrowhorizontal", null ],
      [ "NarrowVertical", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_narrowvertical", null ],
      [ "OutlinedDiamond", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_outlineddiamond", null ],
      [ "Plaid", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_plaid", null ],
      [ "Shingle", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_shingle", null ],
      [ "SmallCheckerBoard", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_smallcheckerboard", null ],
      [ "SmallConfetti", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_smallconfetti", null ],
      [ "SmallGrid", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_smallgrid", null ],
      [ "SolidDiamond", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_soliddiamond", null ],
      [ "Sphere", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_sphere", null ],
      [ "Trellis", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_trellis", null ],
      [ "UpwardDiagonal", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_upwarddiagonal", null ],
      [ "Vertical", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_vertical", null ],
      [ "Wave", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_wave", null ],
      [ "Weave", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_weave", null ],
      [ "WideDownwardDiagonal", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_widedownwarddiagonal", null ],
      [ "WideUpwardDiagonal", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_wideupwarddiagonal", null ],
      [ "ZigZag", "namespace_aspose_1_1_words_1_1_drawing.html#patterntype_zigzag", null ]
    ] ],
    [ "PresetTexture", "namespace_aspose_1_1_words_1_1_drawing.html#presettexture", [
      [ "None", "namespace_aspose_1_1_words_1_1_drawing.html#presettexture_none", null ],
      [ "BlueTissuePaper", "namespace_aspose_1_1_words_1_1_drawing.html#presettexture_bluetissuepaper", null ],
      [ "Bouquet", "namespace_aspose_1_1_words_1_1_drawing.html#presettexture_bouquet", null ],
      [ "BrownMarble", "namespace_aspose_1_1_words_1_1_drawing.html#presettexture_brownmarble", null ],
      [ "Canvas", "namespace_aspose_1_1_words_1_1_drawing.html#presettexture_canvas", null ],
      [ "Cork", "namespace_aspose_1_1_words_1_1_drawing.html#presettexture_cork", null ],
      [ "Denim", "namespace_aspose_1_1_words_1_1_drawing.html#presettexture_denim", null ],
      [ "FishFossil", "namespace_aspose_1_1_words_1_1_drawing.html#presettexture_fishfossil", null ],
      [ "Granite", "namespace_aspose_1_1_words_1_1_drawing.html#presettexture_granite", null ],
      [ "GreenMarble", "namespace_aspose_1_1_words_1_1_drawing.html#presettexture_greenmarble", null ],
      [ "MediumWood", "namespace_aspose_1_1_words_1_1_drawing.html#presettexture_mediumwood", null ],
      [ "Newsprint", "namespace_aspose_1_1_words_1_1_drawing.html#presettexture_newsprint", null ],
      [ "Oak", "namespace_aspose_1_1_words_1_1_drawing.html#presettexture_oak", null ],
      [ "PaperBag", "namespace_aspose_1_1_words_1_1_drawing.html#presettexture_paperbag", null ],
      [ "Papyrus", "namespace_aspose_1_1_words_1_1_drawing.html#presettexture_papyrus", null ],
      [ "Parchment", "namespace_aspose_1_1_words_1_1_drawing.html#presettexture_parchment", null ],
      [ "PinkTissuePaper", "namespace_aspose_1_1_words_1_1_drawing.html#presettexture_pinktissuepaper", null ],
      [ "PurpleMesh", "namespace_aspose_1_1_words_1_1_drawing.html#presettexture_purplemesh", null ],
      [ "RecycledPaper", "namespace_aspose_1_1_words_1_1_drawing.html#presettexture_recycledpaper", null ],
      [ "Sand", "namespace_aspose_1_1_words_1_1_drawing.html#presettexture_sand", null ],
      [ "Stationery", "namespace_aspose_1_1_words_1_1_drawing.html#presettexture_stationery", null ],
      [ "Walnut", "namespace_aspose_1_1_words_1_1_drawing.html#presettexture_walnut", null ],
      [ "WaterDroplets", "namespace_aspose_1_1_words_1_1_drawing.html#presettexture_waterdroplets", null ],
      [ "WhiteMarble", "namespace_aspose_1_1_words_1_1_drawing.html#presettexture_whitemarble", null ],
      [ "WovenMat", "namespace_aspose_1_1_words_1_1_drawing.html#presettexture_wovenmat", null ]
    ] ],
    [ "RelativeHorizontalPosition", "namespace_aspose_1_1_words_1_1_drawing.html#relativehorizontalposition", [
      [ "Margin", "namespace_aspose_1_1_words_1_1_drawing.html#relativehorizontalposition_margin", null ],
      [ "Page", "namespace_aspose_1_1_words_1_1_drawing.html#relativehorizontalposition_page", null ],
      [ "Column", "namespace_aspose_1_1_words_1_1_drawing.html#relativehorizontalposition_column", null ],
      [ "Character", "namespace_aspose_1_1_words_1_1_drawing.html#relativehorizontalposition_character", null ],
      [ "LeftMargin", "namespace_aspose_1_1_words_1_1_drawing.html#relativehorizontalposition_leftmargin", null ],
      [ "RightMargin", "namespace_aspose_1_1_words_1_1_drawing.html#relativehorizontalposition_rightmargin", null ],
      [ "InsideMargin", "namespace_aspose_1_1_words_1_1_drawing.html#relativehorizontalposition_insidemargin", null ],
      [ "OutsideMargin", "namespace_aspose_1_1_words_1_1_drawing.html#relativehorizontalposition_outsidemargin", null ],
      [ "Default", "namespace_aspose_1_1_words_1_1_drawing.html#relativehorizontalposition_default", null ]
    ] ],
    [ "RelativeVerticalPosition", "namespace_aspose_1_1_words_1_1_drawing.html#relativeverticalposition", [
      [ "Margin", "namespace_aspose_1_1_words_1_1_drawing.html#relativeverticalposition_margin", null ],
      [ "Page", "namespace_aspose_1_1_words_1_1_drawing.html#relativeverticalposition_page", null ],
      [ "Paragraph", "namespace_aspose_1_1_words_1_1_drawing.html#relativeverticalposition_paragraph", null ],
      [ "Line", "namespace_aspose_1_1_words_1_1_drawing.html#relativeverticalposition_line", null ],
      [ "TopMargin", "namespace_aspose_1_1_words_1_1_drawing.html#relativeverticalposition_topmargin", null ],
      [ "BottomMargin", "namespace_aspose_1_1_words_1_1_drawing.html#relativeverticalposition_bottommargin", null ],
      [ "InsideMargin", "namespace_aspose_1_1_words_1_1_drawing.html#relativeverticalposition_insidemargin", null ],
      [ "OutsideMargin", "namespace_aspose_1_1_words_1_1_drawing.html#relativeverticalposition_outsidemargin", null ],
      [ "TableDefault", "namespace_aspose_1_1_words_1_1_drawing.html#relativeverticalposition_tabledefault", null ],
      [ "TextFrameDefault", "namespace_aspose_1_1_words_1_1_drawing.html#relativeverticalposition_textframedefault", null ]
    ] ],
    [ "ShapeLineStyle", "namespace_aspose_1_1_words_1_1_drawing.html#shapelinestyle", [
      [ "Single", "namespace_aspose_1_1_words_1_1_drawing.html#shapelinestyle_single", null ],
      [ "Double", "namespace_aspose_1_1_words_1_1_drawing.html#shapelinestyle_double", null ],
      [ "ThickThin", "namespace_aspose_1_1_words_1_1_drawing.html#shapelinestyle_thickthin", null ],
      [ "ThinThick", "namespace_aspose_1_1_words_1_1_drawing.html#shapelinestyle_thinthick", null ],
      [ "Triple", "namespace_aspose_1_1_words_1_1_drawing.html#shapelinestyle_triple", null ],
      [ "Default", "namespace_aspose_1_1_words_1_1_drawing.html#shapelinestyle_default", null ]
    ] ],
    [ "ShapeMarkupLanguage", "namespace_aspose_1_1_words_1_1_drawing.html#shapemarkuplanguage", [
      [ "Dml", "namespace_aspose_1_1_words_1_1_drawing.html#shapemarkuplanguage_dml", null ],
      [ "Vml", "namespace_aspose_1_1_words_1_1_drawing.html#shapemarkuplanguage_vml", null ]
    ] ],
    [ "ShapeType", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype", [
      [ "Image", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_image", null ],
      [ "TextBox", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textbox", null ],
      [ "Group", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_group", null ],
      [ "OleObject", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_oleobject", null ],
      [ "OleControl", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_olecontrol", null ],
      [ "NonPrimitive", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_nonprimitive", null ],
      [ "Rectangle", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_rectangle", null ],
      [ "RoundRectangle", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_roundrectangle", null ],
      [ "Ellipse", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_ellipse", null ],
      [ "Diamond", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_diamond", null ],
      [ "Triangle", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_triangle", null ],
      [ "RightTriangle", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_righttriangle", null ],
      [ "Parallelogram", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_parallelogram", null ],
      [ "Trapezoid", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_trapezoid", null ],
      [ "Hexagon", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_hexagon", null ],
      [ "Octagon", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_octagon", null ],
      [ "Plus", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_plus", null ],
      [ "Star", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_star", null ],
      [ "Arrow", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_arrow", null ],
      [ "ThickArrow", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_thickarrow", null ],
      [ "HomePlate", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_homeplate", null ],
      [ "Cube", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_cube", null ],
      [ "Balloon", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_balloon", null ],
      [ "Seal", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_seal", null ],
      [ "Arc", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_arc", null ],
      [ "Line", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_line", null ],
      [ "Plaque", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_plaque", null ],
      [ "Can", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_can", null ],
      [ "Donut", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_donut", null ],
      [ "TextSimple", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textsimple", null ],
      [ "TextOctagon", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textoctagon", null ],
      [ "TextHexagon", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_texthexagon", null ],
      [ "TextCurve", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textcurve", null ],
      [ "TextWave", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textwave", null ],
      [ "TextRing", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textring", null ],
      [ "TextOnCurve", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textoncurve", null ],
      [ "TextOnRing", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textonring", null ],
      [ "StraightConnector1", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_straightconnector1", null ],
      [ "BentConnector2", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_bentconnector2", null ],
      [ "BentConnector3", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_bentconnector3", null ],
      [ "BentConnector4", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_bentconnector4", null ],
      [ "BentConnector5", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_bentconnector5", null ],
      [ "CurvedConnector2", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_curvedconnector2", null ],
      [ "CurvedConnector3", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_curvedconnector3", null ],
      [ "CurvedConnector4", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_curvedconnector4", null ],
      [ "CurvedConnector5", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_curvedconnector5", null ],
      [ "Callout1", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_callout1", null ],
      [ "Callout2", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_callout2", null ],
      [ "Callout3", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_callout3", null ],
      [ "AccentCallout1", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_accentcallout1", null ],
      [ "AccentCallout2", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_accentcallout2", null ],
      [ "AccentCallout3", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_accentcallout3", null ],
      [ "BorderCallout1", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_bordercallout1", null ],
      [ "BorderCallout2", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_bordercallout2", null ],
      [ "BorderCallout3", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_bordercallout3", null ],
      [ "AccentBorderCallout1", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_accentbordercallout1", null ],
      [ "AccentBorderCallout2", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_accentbordercallout2", null ],
      [ "AccentBorderCallout3", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_accentbordercallout3", null ],
      [ "Ribbon", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_ribbon", null ],
      [ "Ribbon2", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_ribbon2", null ],
      [ "Chevron", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_chevron", null ],
      [ "Pentagon", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_pentagon", null ],
      [ "NoSmoking", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_nosmoking", null ],
      [ "Seal8", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_seal8", null ],
      [ "Seal16", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_seal16", null ],
      [ "Seal32", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_seal32", null ],
      [ "WedgeRectCallout", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_wedgerectcallout", null ],
      [ "WedgeRRectCallout", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_wedgerrectcallout", null ],
      [ "WedgeEllipseCallout", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_wedgeellipsecallout", null ],
      [ "Wave", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_wave", null ],
      [ "FoldedCorner", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_foldedcorner", null ],
      [ "LeftArrow", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_leftarrow", null ],
      [ "DownArrow", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_downarrow", null ],
      [ "UpArrow", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_uparrow", null ],
      [ "LeftRightArrow", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_leftrightarrow", null ],
      [ "UpDownArrow", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_updownarrow", null ],
      [ "IrregularSeal1", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_irregularseal1", null ],
      [ "IrregularSeal2", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_irregularseal2", null ],
      [ "LightningBolt", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_lightningbolt", null ],
      [ "Heart", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_heart", null ],
      [ "QuadArrow", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_quadarrow", null ],
      [ "LeftArrowCallout", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_leftarrowcallout", null ],
      [ "RightArrowCallout", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_rightarrowcallout", null ],
      [ "UpArrowCallout", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_uparrowcallout", null ],
      [ "DownArrowCallout", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_downarrowcallout", null ],
      [ "LeftRightArrowCallout", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_leftrightarrowcallout", null ],
      [ "UpDownArrowCallout", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_updownarrowcallout", null ],
      [ "QuadArrowCallout", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_quadarrowcallout", null ],
      [ "Bevel", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_bevel", null ],
      [ "LeftBracket", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_leftbracket", null ],
      [ "RightBracket", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_rightbracket", null ],
      [ "LeftBrace", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_leftbrace", null ],
      [ "RightBrace", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_rightbrace", null ],
      [ "LeftUpArrow", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_leftuparrow", null ],
      [ "BentUpArrow", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_bentuparrow", null ],
      [ "BentArrow", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_bentarrow", null ],
      [ "Seal24", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_seal24", null ],
      [ "StripedRightArrow", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_stripedrightarrow", null ],
      [ "NotchedRightArrow", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_notchedrightarrow", null ],
      [ "BlockArc", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_blockarc", null ],
      [ "SmileyFace", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_smileyface", null ],
      [ "VerticalScroll", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_verticalscroll", null ],
      [ "HorizontalScroll", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_horizontalscroll", null ],
      [ "CircularArrow", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_circulararrow", null ],
      [ "CustomShape", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_customshape", null ],
      [ "UturnArrow", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_uturnarrow", null ],
      [ "CurvedRightArrow", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_curvedrightarrow", null ],
      [ "CurvedLeftArrow", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_curvedleftarrow", null ],
      [ "CurvedUpArrow", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_curveduparrow", null ],
      [ "CurvedDownArrow", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_curveddownarrow", null ],
      [ "CloudCallout", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_cloudcallout", null ],
      [ "EllipseRibbon", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_ellipseribbon", null ],
      [ "EllipseRibbon2", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_ellipseribbon2", null ],
      [ "FlowChartProcess", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_flowchartprocess", null ],
      [ "FlowChartDecision", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_flowchartdecision", null ],
      [ "FlowChartInputOutput", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_flowchartinputoutput", null ],
      [ "FlowChartPredefinedProcess", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_flowchartpredefinedprocess", null ],
      [ "FlowChartInternalStorage", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_flowchartinternalstorage", null ],
      [ "FlowChartDocument", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_flowchartdocument", null ],
      [ "FlowChartMultidocument", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_flowchartmultidocument", null ],
      [ "FlowChartTerminator", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_flowchartterminator", null ],
      [ "FlowChartPreparation", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_flowchartpreparation", null ],
      [ "FlowChartManualInput", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_flowchartmanualinput", null ],
      [ "FlowChartManualOperation", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_flowchartmanualoperation", null ],
      [ "FlowChartConnector", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_flowchartconnector", null ],
      [ "FlowChartPunchedCard", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_flowchartpunchedcard", null ],
      [ "FlowChartPunchedTape", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_flowchartpunchedtape", null ],
      [ "FlowChartSummingJunction", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_flowchartsummingjunction", null ],
      [ "FlowChartOr", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_flowchartor", null ],
      [ "FlowChartCollate", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_flowchartcollate", null ],
      [ "FlowChartSort", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_flowchartsort", null ],
      [ "FlowChartExtract", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_flowchartextract", null ],
      [ "FlowChartMerge", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_flowchartmerge", null ],
      [ "FlowChartOfflineStorage", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_flowchartofflinestorage", null ],
      [ "FlowChartOnlineStorage", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_flowchartonlinestorage", null ],
      [ "FlowChartMagneticTape", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_flowchartmagnetictape", null ],
      [ "FlowChartMagneticDisk", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_flowchartmagneticdisk", null ],
      [ "FlowChartMagneticDrum", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_flowchartmagneticdrum", null ],
      [ "FlowChartDisplay", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_flowchartdisplay", null ],
      [ "FlowChartDelay", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_flowchartdelay", null ],
      [ "TextPlainText", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textplaintext", null ],
      [ "TextStop", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textstop", null ],
      [ "TextTriangle", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_texttriangle", null ],
      [ "TextTriangleInverted", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_texttriangleinverted", null ],
      [ "TextChevron", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textchevron", null ],
      [ "TextChevronInverted", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textchevroninverted", null ],
      [ "TextRingInside", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textringinside", null ],
      [ "TextRingOutside", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textringoutside", null ],
      [ "TextArchUpCurve", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textarchupcurve", null ],
      [ "TextArchDownCurve", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textarchdowncurve", null ],
      [ "TextCircleCurve", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textcirclecurve", null ],
      [ "TextButtonCurve", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textbuttoncurve", null ],
      [ "TextArchUpPour", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textarchuppour", null ],
      [ "TextArchDownPour", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textarchdownpour", null ],
      [ "TextCirclePour", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textcirclepour", null ],
      [ "TextButtonPour", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textbuttonpour", null ],
      [ "TextCurveUp", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textcurveup", null ],
      [ "TextCurveDown", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textcurvedown", null ],
      [ "TextCascadeUp", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textcascadeup", null ],
      [ "TextCascadeDown", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textcascadedown", null ],
      [ "TextWave1", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textwave1", null ],
      [ "TextWave2", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textwave2", null ],
      [ "TextWave3", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textwave3", null ],
      [ "TextWave4", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textwave4", null ],
      [ "TextInflate", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textinflate", null ],
      [ "TextDeflate", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textdeflate", null ],
      [ "TextInflateBottom", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textinflatebottom", null ],
      [ "TextDeflateBottom", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textdeflatebottom", null ],
      [ "TextInflateTop", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textinflatetop", null ],
      [ "TextDeflateTop", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textdeflatetop", null ],
      [ "TextDeflateInflate", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textdeflateinflate", null ],
      [ "TextDeflateInflateDeflate", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textdeflateinflatedeflate", null ],
      [ "TextFadeRight", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textfaderight", null ],
      [ "TextFadeLeft", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textfadeleft", null ],
      [ "TextFadeUp", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textfadeup", null ],
      [ "TextFadeDown", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textfadedown", null ],
      [ "TextSlantUp", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textslantup", null ],
      [ "TextSlantDown", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textslantdown", null ],
      [ "TextCanUp", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textcanup", null ],
      [ "TextCanDown", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_textcandown", null ],
      [ "FlowChartAlternateProcess", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_flowchartalternateprocess", null ],
      [ "FlowChartOffpageConnector", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_flowchartoffpageconnector", null ],
      [ "Callout90", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_callout90", null ],
      [ "AccentCallout90", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_accentcallout90", null ],
      [ "BorderCallout90", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_bordercallout90", null ],
      [ "AccentBorderCallout90", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_accentbordercallout90", null ],
      [ "LeftRightUpArrow", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_leftrightuparrow", null ],
      [ "Sun", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_sun", null ],
      [ "Moon", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_moon", null ],
      [ "BracketPair", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_bracketpair", null ],
      [ "BracePair", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_bracepair", null ],
      [ "Seal4", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_seal4", null ],
      [ "DoubleWave", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_doublewave", null ],
      [ "ActionButtonBlank", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_actionbuttonblank", null ],
      [ "ActionButtonHome", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_actionbuttonhome", null ],
      [ "ActionButtonHelp", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_actionbuttonhelp", null ],
      [ "ActionButtonInformation", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_actionbuttoninformation", null ],
      [ "ActionButtonForwardNext", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_actionbuttonforwardnext", null ],
      [ "ActionButtonBackPrevious", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_actionbuttonbackprevious", null ],
      [ "ActionButtonEnd", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_actionbuttonend", null ],
      [ "ActionButtonBeginning", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_actionbuttonbeginning", null ],
      [ "ActionButtonReturn", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_actionbuttonreturn", null ],
      [ "ActionButtonDocument", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_actionbuttondocument", null ],
      [ "ActionButtonSound", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_actionbuttonsound", null ],
      [ "ActionButtonMovie", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_actionbuttonmovie", null ],
      [ "SingleCornerSnipped", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_singlecornersnipped", null ],
      [ "TopCornersSnipped", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_topcornerssnipped", null ],
      [ "DiagonalCornersSnipped", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_diagonalcornerssnipped", null ],
      [ "TopCornersOneRoundedOneSnipped", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_topcornersoneroundedonesnipped", null ],
      [ "SingleCornerRounded", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_singlecornerrounded", null ],
      [ "TopCornersRounded", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_topcornersrounded", null ],
      [ "DiagonalCornersRounded", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_diagonalcornersrounded", null ],
      [ "Heptagon", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_heptagon", null ],
      [ "Cloud", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_cloud", null ],
      [ "Seal6", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_seal6", null ],
      [ "Seal7", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_seal7", null ],
      [ "Seal10", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_seal10", null ],
      [ "Seal12", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_seal12", null ],
      [ "SwooshArrow", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_swoosharrow", null ],
      [ "Teardrop", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_teardrop", null ],
      [ "SquareTabs", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_squaretabs", null ],
      [ "PlaqueTabs", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_plaquetabs", null ],
      [ "Pie", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_pie", null ],
      [ "WedgePie", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_wedgepie", null ],
      [ "InverseLine", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_inverseline", null ],
      [ "MathPlus", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_mathplus", null ],
      [ "MathMinus", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_mathminus", null ],
      [ "MathMultiply", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_mathmultiply", null ],
      [ "MathDivide", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_mathdivide", null ],
      [ "MathEqual", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_mathequal", null ],
      [ "MathNotEqual", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_mathnotequal", null ],
      [ "NonIsoscelesTrapezoid", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_nonisoscelestrapezoid", null ],
      [ "LeftRightCircularArrow", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_leftrightcirculararrow", null ],
      [ "LeftRightRibbon", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_leftrightribbon", null ],
      [ "LeftCircularArrow", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_leftcirculararrow", null ],
      [ "Frame", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_frame", null ],
      [ "HalfFrame", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_halfframe", null ],
      [ "Funnel", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_funnel", null ],
      [ "Gear6", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_gear6", null ],
      [ "Gear9", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_gear9", null ],
      [ "Decagon", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_decagon", null ],
      [ "Dodecagon", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_dodecagon", null ],
      [ "DiagonalStripe", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_diagonalstripe", null ],
      [ "Corner", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_corner", null ],
      [ "CornerTabs", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_cornertabs", null ],
      [ "Chord", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_chord", null ],
      [ "ChartPlus", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_chartplus", null ],
      [ "ChartStar", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_chartstar", null ],
      [ "ChartX", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_chartx", null ],
      [ "MinValue", "namespace_aspose_1_1_words_1_1_drawing.html#shapetype_minvalue", null ]
    ] ],
    [ "TextBoxAnchor", "namespace_aspose_1_1_words_1_1_drawing.html#textboxanchor", [
      [ "Top", "namespace_aspose_1_1_words_1_1_drawing.html#textboxanchor_top", null ],
      [ "Middle", "namespace_aspose_1_1_words_1_1_drawing.html#textboxanchor_middle", null ],
      [ "Bottom", "namespace_aspose_1_1_words_1_1_drawing.html#textboxanchor_bottom", null ],
      [ "TopCentered", "namespace_aspose_1_1_words_1_1_drawing.html#textboxanchor_topcentered", null ],
      [ "MiddleCentered", "namespace_aspose_1_1_words_1_1_drawing.html#textboxanchor_middlecentered", null ],
      [ "BottomCentered", "namespace_aspose_1_1_words_1_1_drawing.html#textboxanchor_bottomcentered", null ],
      [ "TopBaseline", "namespace_aspose_1_1_words_1_1_drawing.html#textboxanchor_topbaseline", null ],
      [ "BottomBaseline", "namespace_aspose_1_1_words_1_1_drawing.html#textboxanchor_bottombaseline", null ],
      [ "TopCenteredBaseline", "namespace_aspose_1_1_words_1_1_drawing.html#textboxanchor_topcenteredbaseline", null ],
      [ "BottomCenteredBaseline", "namespace_aspose_1_1_words_1_1_drawing.html#textboxanchor_bottomcenteredbaseline", null ]
    ] ],
    [ "TextBoxWrapMode", "namespace_aspose_1_1_words_1_1_drawing.html#textboxwrapmode", [
      [ "Square", "namespace_aspose_1_1_words_1_1_drawing.html#textboxwrapmode_square", null ],
      [ "None", "namespace_aspose_1_1_words_1_1_drawing.html#textboxwrapmode_none", null ]
    ] ],
    [ "TextPathAlignment", "namespace_aspose_1_1_words_1_1_drawing.html#textpathalignment", [
      [ "Stretch", "namespace_aspose_1_1_words_1_1_drawing.html#textpathalignment_stretch", null ],
      [ "Center", "namespace_aspose_1_1_words_1_1_drawing.html#textpathalignment_center", null ],
      [ "Left", "namespace_aspose_1_1_words_1_1_drawing.html#textpathalignment_left", null ],
      [ "Right", "namespace_aspose_1_1_words_1_1_drawing.html#textpathalignment_right", null ],
      [ "LetterJustify", "namespace_aspose_1_1_words_1_1_drawing.html#textpathalignment_letterjustify", null ],
      [ "WordJustify", "namespace_aspose_1_1_words_1_1_drawing.html#textpathalignment_wordjustify", null ]
    ] ],
    [ "TextureAlignment", "namespace_aspose_1_1_words_1_1_drawing.html#texturealignment", [
      [ "TopLeft", "namespace_aspose_1_1_words_1_1_drawing.html#texturealignment_topleft", null ],
      [ "Top", "namespace_aspose_1_1_words_1_1_drawing.html#texturealignment_top", null ],
      [ "TopRight", "namespace_aspose_1_1_words_1_1_drawing.html#texturealignment_topright", null ],
      [ "Left", "namespace_aspose_1_1_words_1_1_drawing.html#texturealignment_left", null ],
      [ "Center", "namespace_aspose_1_1_words_1_1_drawing.html#texturealignment_center", null ],
      [ "Right", "namespace_aspose_1_1_words_1_1_drawing.html#texturealignment_right", null ],
      [ "BottomLeft", "namespace_aspose_1_1_words_1_1_drawing.html#texturealignment_bottomleft", null ],
      [ "Bottom", "namespace_aspose_1_1_words_1_1_drawing.html#texturealignment_bottom", null ],
      [ "BottomRight", "namespace_aspose_1_1_words_1_1_drawing.html#texturealignment_bottomright", null ],
      [ "None", "namespace_aspose_1_1_words_1_1_drawing.html#texturealignment_none", null ]
    ] ],
    [ "VerticalAlignment", "namespace_aspose_1_1_words_1_1_drawing.html#verticalalignment", [
      [ "None", "namespace_aspose_1_1_words_1_1_drawing.html#verticalalignment_none", null ],
      [ "Top", "namespace_aspose_1_1_words_1_1_drawing.html#verticalalignment_top", null ],
      [ "Center", "namespace_aspose_1_1_words_1_1_drawing.html#verticalalignment_center", null ],
      [ "Bottom", "namespace_aspose_1_1_words_1_1_drawing.html#verticalalignment_bottom", null ],
      [ "Inside", "namespace_aspose_1_1_words_1_1_drawing.html#verticalalignment_inside", null ],
      [ "Outside", "namespace_aspose_1_1_words_1_1_drawing.html#verticalalignment_outside", null ],
      [ "Inline", "namespace_aspose_1_1_words_1_1_drawing.html#verticalalignment_inline", null ],
      [ "Default", "namespace_aspose_1_1_words_1_1_drawing.html#verticalalignment_default", null ]
    ] ],
    [ "WrapSide", "namespace_aspose_1_1_words_1_1_drawing.html#wrapside", [
      [ "Both", "namespace_aspose_1_1_words_1_1_drawing.html#wrapside_both", null ],
      [ "Left", "namespace_aspose_1_1_words_1_1_drawing.html#wrapside_left", null ],
      [ "Right", "namespace_aspose_1_1_words_1_1_drawing.html#wrapside_right", null ],
      [ "Largest", "namespace_aspose_1_1_words_1_1_drawing.html#wrapside_largest", null ],
      [ "Default", "namespace_aspose_1_1_words_1_1_drawing.html#wrapside_default", null ]
    ] ],
    [ "WrapType", "namespace_aspose_1_1_words_1_1_drawing.html#wraptype", [
      [ "None", "namespace_aspose_1_1_words_1_1_drawing.html#wraptype_none", null ],
      [ "Inline", "namespace_aspose_1_1_words_1_1_drawing.html#wraptype_inline", null ],
      [ "TopBottom", "namespace_aspose_1_1_words_1_1_drawing.html#wraptype_topbottom", null ],
      [ "Square", "namespace_aspose_1_1_words_1_1_drawing.html#wraptype_square", null ],
      [ "Tight", "namespace_aspose_1_1_words_1_1_drawing.html#wraptype_tight", null ],
      [ "Through", "namespace_aspose_1_1_words_1_1_drawing.html#wraptype_through", null ]
    ] ]
];