var namespace_system =
[
    [ "Collections", "namespace_system_1_1_collections.html", "namespace_system_1_1_collections" ],
    [ "ComponentModel", "namespace_system_1_1_component_model.html", "namespace_system_1_1_component_model" ],
    [ "Constraints", "namespace_system_1_1_constraints.html", "namespace_system_1_1_constraints" ],
    [ "Data", "namespace_system_1_1_data.html", "namespace_system_1_1_data" ],
    [ "Diagnostics", "namespace_system_1_1_diagnostics.html", "namespace_system_1_1_diagnostics" ],
    [ "Drawing", "namespace_system_1_1_drawing.html", "namespace_system_1_1_drawing" ],
    [ "Globalization", "namespace_system_1_1_globalization.html", "namespace_system_1_1_globalization" ],
    [ "IO", "namespace_system_1_1_i_o.html", "namespace_system_1_1_i_o" ],
    [ "Linq", "namespace_system_1_1_linq.html", "namespace_system_1_1_linq" ],
    [ "Net", "namespace_system_1_1_net.html", "namespace_system_1_1_net" ],
    [ "Reflection", "namespace_system_1_1_reflection.html", "namespace_system_1_1_reflection" ],
    [ "Resources", "namespace_system_1_1_resources.html", "namespace_system_1_1_resources" ],
    [ "Runtime", "namespace_system_1_1_runtime.html", "namespace_system_1_1_runtime" ],
    [ "Security", "namespace_system_1_1_security.html", "namespace_system_1_1_security" ],
    [ "TestPredicates", "namespace_system_1_1_test_predicates.html", "namespace_system_1_1_test_predicates" ],
    [ "Text", "namespace_system_1_1_text.html", "namespace_system_1_1_text" ],
    [ "Threading", "namespace_system_1_1_threading.html", "namespace_system_1_1_threading" ],
    [ "Timers", "namespace_system_1_1_timers.html", "namespace_system_1_1_timers" ],
    [ "Web", "namespace_system_1_1_web.html", "namespace_system_1_1_web" ],
    [ "Windows", "namespace_system_1_1_windows.html", "namespace_system_1_1_windows" ],
    [ "Xml", "namespace_system_1_1_xml.html", "namespace_system_1_1_xml" ],
    [ "AnyTypesMatch", "struct_system_1_1_any_types_match.html", null ],
    [ "AnyTypesMatch< FirstType, SecondType, OtherTypes... >", "struct_system_1_1_any_types_match_3_01_first_type_00_01_second_type_00_01_other_types_8_8_8_01_4.html", null ],
    [ "AnyTypesMatch< LastType >", "struct_system_1_1_any_types_match_3_01_last_type_01_4.html", null ],
    [ "Array", "class_system_1_1_array.html", "class_system_1_1_array" ],
    [ "ArraySegment", "class_system_1_1_array_segment.html", "class_system_1_1_array_segment" ],
    [ "Attribute", "class_system_1_1_attribute.html", null ],
    [ "BasePointerType", "struct_system_1_1_base_pointer_type.html", "struct_system_1_1_base_pointer_type" ],
    [ "BasePointerType< WeakPtr< T > >", "struct_system_1_1_base_pointer_type_3_01_weak_ptr_3_01_t_01_4_01_4.html", "struct_system_1_1_base_pointer_type_3_01_weak_ptr_3_01_t_01_4_01_4" ],
    [ "BaseTypesInfo", "class_system_1_1_base_types_info.html", null ],
    [ "BaseTypesInfo< FirstType, BaseTypes... >", "class_system_1_1_base_types_info_3_01_first_type_00_01_base_types_8_8_8_01_4.html", "class_system_1_1_base_types_info_3_01_first_type_00_01_base_types_8_8_8_01_4" ],
    [ "BaseTypesInfo<>", "class_system_1_1_base_types_info_3_4.html", null ],
    [ "BitConverter", "class_system_1_1_bit_converter.html", null ],
    [ "Boolean", "class_system_1_1_boolean.html", null ],
    [ "BoxedEnum", "class_system_1_1_boxed_enum.html", "class_system_1_1_boxed_enum" ],
    [ "BoxedValue", "class_system_1_1_boxed_value.html", "class_system_1_1_boxed_value" ],
    [ "BoxedValue< System::Collections::Generic::KeyValuePair< TKey, TValue > >", "class_system_1_1_boxed_value_3_01_system_1_1_collections_1_1_generic_1_1_key_value_pair_3_01_t_key_00_01_t_value_01_4_01_4.html", "class_system_1_1_boxed_value_3_01_system_1_1_collections_1_1_generic_1_1_key_value_pair_3_01_t_key_00_01_t_value_01_4_01_4" ],
    [ "BoxedValue< System::Drawing::Color >", "class_system_1_1_boxed_value_3_01_system_1_1_drawing_1_1_color_01_4.html", "class_system_1_1_boxed_value_3_01_system_1_1_drawing_1_1_color_01_4" ],
    [ "BoxedValue< System::Drawing::Point >", "class_system_1_1_boxed_value_3_01_system_1_1_drawing_1_1_point_01_4.html", "class_system_1_1_boxed_value_3_01_system_1_1_drawing_1_1_point_01_4" ],
    [ "BoxedValue< System::Drawing::PointF >", "class_system_1_1_boxed_value_3_01_system_1_1_drawing_1_1_point_f_01_4.html", "class_system_1_1_boxed_value_3_01_system_1_1_drawing_1_1_point_f_01_4" ],
    [ "BoxedValue< System::Drawing::Rectangle >", "class_system_1_1_boxed_value_3_01_system_1_1_drawing_1_1_rectangle_01_4.html", "class_system_1_1_boxed_value_3_01_system_1_1_drawing_1_1_rectangle_01_4" ],
    [ "BoxedValue< System::Drawing::RectangleF >", "class_system_1_1_boxed_value_3_01_system_1_1_drawing_1_1_rectangle_f_01_4.html", "class_system_1_1_boxed_value_3_01_system_1_1_drawing_1_1_rectangle_f_01_4" ],
    [ "BoxedValue< System::Drawing::Size >", "class_system_1_1_boxed_value_3_01_system_1_1_drawing_1_1_size_01_4.html", "class_system_1_1_boxed_value_3_01_system_1_1_drawing_1_1_size_01_4" ],
    [ "BoxedValue< System::Drawing::SizeF >", "class_system_1_1_boxed_value_3_01_system_1_1_drawing_1_1_size_f_01_4.html", "class_system_1_1_boxed_value_3_01_system_1_1_drawing_1_1_size_f_01_4" ],
    [ "BoxedValueBase", "class_system_1_1_boxed_value_base.html", "class_system_1_1_boxed_value_base" ],
    [ "Buffer", "class_system_1_1_buffer.html", null ],
    [ "Byte", "class_system_1_1_byte.html", null ],
    [ "CastResult", "struct_system_1_1_cast_result.html", "struct_system_1_1_cast_result" ],
    [ "CastResult< Array< TTo > >", "struct_system_1_1_cast_result_3_01_array_3_01_t_to_01_4_01_4.html", "struct_system_1_1_cast_result_3_01_array_3_01_t_to_01_4_01_4" ],
    [ "CastResult< MulticastDelegate< T > >", "struct_system_1_1_cast_result_3_01_multicast_delegate_3_01_t_01_4_01_4.html", "struct_system_1_1_cast_result_3_01_multicast_delegate_3_01_t_01_4_01_4" ],
    [ "CastResult< String >", "struct_system_1_1_cast_result_3_01_string_01_4.html", "struct_system_1_1_cast_result_3_01_string_01_4" ],
    [ "Char", "class_system_1_1_char.html", null ],
    [ "CollectionAssertHelper", "struct_system_1_1_collection_assert_helper.html", null ],
    [ "Comparison", "class_system_1_1_comparison.html", "class_system_1_1_comparison" ],
    [ "Console", "class_system_1_1_console.html", null ],
    [ "ConsoleOutput", "class_system_1_1_console_output.html", "class_system_1_1_console_output" ],
    [ "Convert", "struct_system_1_1_convert.html", null ],
    [ "DateTime", "class_system_1_1_date_time.html", "class_system_1_1_date_time" ],
    [ "DateTimeOffset", "class_system_1_1_date_time_offset.html", "class_system_1_1_date_time_offset" ],
    [ "DBNull", "class_system_1_1_d_b_null.html", null ],
    [ "Decimal", "class_system_1_1_decimal.html", "class_system_1_1_decimal" ],
    [ "DefaultBoxedValue", "class_system_1_1_default_boxed_value.html", "class_system_1_1_default_boxed_value" ],
    [ "Delegate", "class_system_1_1_delegate.html", null ],
    [ "Delegate< ReturnType(ArgumentTypes...)>", "class_system_1_1_delegate_3_01_return_type_07_argument_types_8_8_8_08_4.html", "class_system_1_1_delegate_3_01_return_type_07_argument_types_8_8_8_08_4" ],
    [ "Double", "struct_system_1_1_double.html", null ],
    [ "DynamicWeakPtr", "class_system_1_1_dynamic_weak_ptr.html", "class_system_1_1_dynamic_weak_ptr" ],
    [ "EmptyArrayInitializer", "struct_system_1_1_empty_array_initializer.html", null ],
    [ "Enum", "struct_system_1_1_enum.html", "struct_system_1_1_enum" ],
    [ "EnumGetNameHelper", "struct_system_1_1_enum_get_name_helper.html", null ],
    [ "EnumParseHelper", "struct_system_1_1_enum_parse_helper.html", null ],
    [ "EnumValues", "class_system_1_1_enum_values.html", "class_system_1_1_enum_values" ],
    [ "EnumValuesBase", "class_system_1_1_enum_values_base.html", "class_system_1_1_enum_values_base" ],
    [ "Environment", "struct_system_1_1_environment.html", "struct_system_1_1_environment" ],
    [ "EventArgs", "class_system_1_1_event_args.html", "class_system_1_1_event_args" ],
    [ "EventHandler", "class_system_1_1_event_handler.html", "class_system_1_1_event_handler" ],
    [ "ExceptionWrapper", "class_system_1_1_exception_wrapper.html", "class_system_1_1_exception_wrapper" ],
    [ "ExceptionWrapperBase", "class_system_1_1_exception_wrapper_base.html", "class_system_1_1_exception_wrapper_base" ],
    [ "ExceptionWrapperHelper", "class_system_1_1_exception_wrapper_helper.html", "class_system_1_1_exception_wrapper_helper" ],
    [ "ExceptionWrapperType", "struct_system_1_1_exception_wrapper_type.html", null ],
    [ "Func", "class_system_1_1_func.html", "class_system_1_1_func" ],
    [ "Guid", "class_system_1_1_guid.html", "class_system_1_1_guid" ],
    [ "IAsyncResult", "class_system_1_1_i_async_result.html", "class_system_1_1_i_async_result" ],
    [ "ICloneable", "class_system_1_1_i_cloneable.html", "class_system_1_1_i_cloneable" ],
    [ "IComparable", "class_system_1_1_i_comparable.html", "class_system_1_1_i_comparable" ],
    [ "IConvertible", "class_system_1_1_i_convertible.html", "class_system_1_1_i_convertible" ],
    [ "ICustomFormatter", "class_system_1_1_i_custom_formatter.html", "class_system_1_1_i_custom_formatter" ],
    [ "IDisposable", "class_system_1_1_i_disposable.html", "class_system_1_1_i_disposable" ],
    [ "IEnumerableAdapter", "class_system_1_1_i_enumerable_adapter.html", "class_system_1_1_i_enumerable_adapter" ],
    [ "IEnumerableDefaultAdapter", "class_system_1_1_i_enumerable_default_adapter.html", "class_system_1_1_i_enumerable_default_adapter" ],
    [ "IEnumerableTupleAdapter", "class_system_1_1_i_enumerable_tuple_adapter.html", "class_system_1_1_i_enumerable_tuple_adapter" ],
    [ "IEnumeratorIterator", "class_system_1_1_i_enumerator_iterator.html", "class_system_1_1_i_enumerator_iterator" ],
    [ "IEquatable", "class_system_1_1_i_equatable.html", "class_system_1_1_i_equatable" ],
    [ "IFormatProvider", "class_system_1_1_i_format_provider.html", "class_system_1_1_i_format_provider" ],
    [ "IFormattable", "class_system_1_1_i_formattable.html", "class_system_1_1_i_formattable" ],
    [ "Int16", "class_system_1_1_int16.html", null ],
    [ "Int32", "class_system_1_1_int32.html", null ],
    [ "Int64", "class_system_1_1_int64.html", null ],
    [ "IsBoxable", "struct_system_1_1_is_boxable.html", null ],
    [ "IsBoxable< Collections::Generic::KeyValuePair< TKey, TValue > >", "struct_system_1_1_is_boxable_3_01_collections_1_1_generic_1_1_key_value_pair_3_01_t_key_00_01_t_value_01_4_01_4.html", null ],
    [ "IsBoxable< DateTime >", "struct_system_1_1_is_boxable_3_01_date_time_01_4.html", null ],
    [ "IsBoxable< DateTimeOffset >", "struct_system_1_1_is_boxable_3_01_date_time_offset_01_4.html", null ],
    [ "IsBoxable< Decimal >", "struct_system_1_1_is_boxable_3_01_decimal_01_4.html", null ],
    [ "IsBoxable< Drawing::Color >", "struct_system_1_1_is_boxable_3_01_drawing_1_1_color_01_4.html", null ],
    [ "IsBoxable< Drawing::Point >", "struct_system_1_1_is_boxable_3_01_drawing_1_1_point_01_4.html", null ],
    [ "IsBoxable< Drawing::PointF >", "struct_system_1_1_is_boxable_3_01_drawing_1_1_point_f_01_4.html", null ],
    [ "IsBoxable< Drawing::Rectangle >", "struct_system_1_1_is_boxable_3_01_drawing_1_1_rectangle_01_4.html", null ],
    [ "IsBoxable< Drawing::RectangleF >", "struct_system_1_1_is_boxable_3_01_drawing_1_1_rectangle_f_01_4.html", null ],
    [ "IsBoxable< Drawing::Size >", "struct_system_1_1_is_boxable_3_01_drawing_1_1_size_01_4.html", null ],
    [ "IsBoxable< Drawing::SizeF >", "struct_system_1_1_is_boxable_3_01_drawing_1_1_size_f_01_4.html", null ],
    [ "IsBoxable< Guid >", "struct_system_1_1_is_boxable_3_01_guid_01_4.html", null ],
    [ "IsBoxable< Nullable< T > >", "struct_system_1_1_is_boxable_3_01_nullable_3_01_t_01_4_01_4.html", null ],
    [ "IsBoxable< String >", "struct_system_1_1_is_boxable_3_01_string_01_4.html", null ],
    [ "IsBoxable< System::Security::Cryptography::HashAlgorithmName >", "struct_system_1_1_is_boxable_3_01_system_1_1_security_1_1_cryptography_1_1_hash_algorithm_name_01_4.html", null ],
    [ "IsBoxable< TimeSpan >", "struct_system_1_1_is_boxable_3_01_time_span_01_4.html", null ],
    [ "IsBoxable< ValueType >", "struct_system_1_1_is_boxable_3_01_value_type_01_4.html", null ],
    [ "IsBoxedValue", "struct_system_1_1_is_boxed_value.html", null ],
    [ "IsBoxedValue< BoxedValue< T > >", "struct_system_1_1_is_boxed_value_3_01_boxed_value_3_01_t_01_4_01_4.html", null ],
    [ "IsExceptionWrapper", "struct_system_1_1_is_exception_wrapper.html", null ],
    [ "IsNonConstStringArray", "struct_system_1_1_is_non_const_string_array.html", null ],
    [ "IsNullable", "struct_system_1_1_is_nullable.html", null ],
    [ "IsSmartPtr", "struct_system_1_1_is_smart_ptr.html", null ],
    [ "IsStringByteSequence", "struct_system_1_1_is_string_byte_sequence.html", null ],
    [ "IsStringLiteral", "struct_system_1_1_is_string_literal.html", null ],
    [ "IsStringPointer", "struct_system_1_1_is_string_pointer.html", null ],
    [ "IsWeakPtr", "struct_system_1_1_is_weak_ptr.html", null ],
    [ "LockContext", "class_system_1_1_lock_context.html", "class_system_1_1_lock_context" ],
    [ "MakeConstRef", "struct_system_1_1_make_const_ref.html", null ],
    [ "MarshalByRefObject", "class_system_1_1_marshal_by_ref_object.html", "class_system_1_1_marshal_by_ref_object" ],
    [ "Math", "struct_system_1_1_math.html", "struct_system_1_1_math" ],
    [ "MethodArgumentTuple", "struct_system_1_1_method_argument_tuple.html", null ],
    [ "MethodArgumentTuple< R(*)(Args...)>", "struct_system_1_1_method_argument_tuple_3_01_r_07_5_08_07_args_8_8_8_08_4.html", "struct_system_1_1_method_argument_tuple_3_01_r_07_5_08_07_args_8_8_8_08_4" ],
    [ "MethodArgumentTuple< R(C::*)(Args...) const >", "struct_system_1_1_method_argument_tuple_3_01_r_07_c_1_1_5_08_07_args_8_8_8_08_01const_01_4.html", "struct_system_1_1_method_argument_tuple_3_01_r_07_c_1_1_5_08_07_args_8_8_8_08_01const_01_4" ],
    [ "MethodArgumentTuple< R(C::*)(Args...)>", "struct_system_1_1_method_argument_tuple_3_01_r_07_c_1_1_5_08_07_args_8_8_8_08_4.html", "struct_system_1_1_method_argument_tuple_3_01_r_07_c_1_1_5_08_07_args_8_8_8_08_4" ],
    [ "MulticastDelegate", "class_system_1_1_multicast_delegate.html", null ],
    [ "MulticastDelegate< ReturnType(ArgumentTypes...)>", "class_system_1_1_multicast_delegate_3_01_return_type_07_argument_types_8_8_8_08_4.html", "class_system_1_1_multicast_delegate_3_01_return_type_07_argument_types_8_8_8_08_4" ],
    [ "MulticastDelegateTypeInfo", "struct_system_1_1_multicast_delegate_type_info.html", "struct_system_1_1_multicast_delegate_type_info" ],
    [ "Nullable", "class_system_1_1_nullable.html", "class_system_1_1_nullable" ],
    [ "Object", "class_system_1_1_object.html", "class_system_1_1_object" ],
    [ "ObjectExt", "class_system_1_1_object_ext.html", "class_system_1_1_object_ext" ],
    [ "OperatingSystem", "class_system_1_1_operating_system.html", "class_system_1_1_operating_system" ],
    [ "Random", "class_system_1_1_random.html", "class_system_1_1_random" ],
    [ "RemoveShared", "struct_system_1_1_remove_shared.html", "struct_system_1_1_remove_shared" ],
    [ "RemoveShared< System::SharedPtr< X > >", "struct_system_1_1_remove_shared_3_01_system_1_1_shared_ptr_3_01_x_01_4_01_4.html", "struct_system_1_1_remove_shared_3_01_system_1_1_shared_ptr_3_01_x_01_4_01_4" ],
    [ "RemoveShared< System::WeakPtr< X > >", "struct_system_1_1_remove_shared_3_01_system_1_1_weak_ptr_3_01_x_01_4_01_4.html", "struct_system_1_1_remove_shared_3_01_system_1_1_weak_ptr_3_01_x_01_4_01_4" ],
    [ "SByte", "struct_system_1_1_s_byte.html", null ],
    [ "ScopedCulture", "class_system_1_1_scoped_culture.html", "class_system_1_1_scoped_culture" ],
    [ "ScopeGuard", "struct_system_1_1_scope_guard.html", "struct_system_1_1_scope_guard" ],
    [ "Single", "struct_system_1_1_single.html", null ],
    [ "SmartPtr", "class_system_1_1_smart_ptr.html", "class_system_1_1_smart_ptr" ],
    [ "SmartPtrInfo", "class_system_1_1_smart_ptr_info.html", "class_system_1_1_smart_ptr_info" ],
    [ "String", "class_system_1_1_string.html", "class_system_1_1_string" ],
    [ "StringComparer", "class_system_1_1_string_comparer.html", "class_system_1_1_string_comparer" ],
    [ "StringHashCompiletime", "class_system_1_1_string_hash_compiletime.html", null ],
    [ "StringHashCompiletime< 0 >", "class_system_1_1_string_hash_compiletime_3_010_01_4.html", null ],
    [ "TestCompare", "struct_system_1_1_test_compare.html", null ],
    [ "TestTools", "struct_system_1_1_test_tools.html", null ],
    [ "TestToolsExt", "struct_system_1_1_test_tools_ext.html", "struct_system_1_1_test_tools_ext" ],
    [ "TimeSpan", "class_system_1_1_time_span.html", "class_system_1_1_time_span" ],
    [ "TimeZone", "class_system_1_1_time_zone.html", "class_system_1_1_time_zone" ],
    [ "TimeZoneInfo", "class_system_1_1_time_zone_info.html", "class_system_1_1_time_zone_info" ],
    [ "Tuple", "class_system_1_1_tuple.html", "class_system_1_1_tuple" ],
    [ "TupleFactory", "class_system_1_1_tuple_factory.html", null ],
    [ "TypeInfo", "class_system_1_1_type_info.html", "class_system_1_1_type_info" ],
    [ "TypeInfoPtr", "struct_system_1_1_type_info_ptr.html", "struct_system_1_1_type_info_ptr" ],
    [ "UInt16", "struct_system_1_1_u_int16.html", null ],
    [ "UInt32", "struct_system_1_1_u_int32.html", null ],
    [ "UInt64", "struct_system_1_1_u_int64.html", null ],
    [ "Uri", "class_system_1_1_uri.html", "class_system_1_1_uri" ],
    [ "UriBuilder", "class_system_1_1_uri_builder.html", "class_system_1_1_uri_builder" ],
    [ "UriParser", "class_system_1_1_uri_parser.html", "class_system_1_1_uri_parser" ],
    [ "UriShim", "class_system_1_1_uri_shim.html", null ],
    [ "ValueType", "class_system_1_1_value_type.html", null ],
    [ "Version", "class_system_1_1_version.html", "class_system_1_1_version" ],
    [ "WeakPtr", "class_system_1_1_weak_ptr.html", "class_system_1_1_weak_ptr" ],
    [ "WeakPtrFromTypeParameter", "struct_system_1_1_weak_ptr_from_type_parameter.html", null ],
    [ "WeakReference", "class_system_1_1_weak_reference.html", "class_system_1_1_weak_reference" ]
];