var namespace_aspose_1_1_pdf_1_1_engine_1_1_common_data_1_1_page_content_1_1_operators_1_1_text_showing =
[
    [ "AuxillaryObjects", "namespace_aspose_1_1_pdf_1_1_engine_1_1_common_data_1_1_page_content_1_1_operators_1_1_text_showing_1_1_auxillary_objects.html", null ]
];