var namespace_system_1_1_net_1_1_http_1_1_headers =
[
    [ "AuthenticationHeaderValue", "class_system_1_1_net_1_1_http_1_1_headers_1_1_authentication_header_value.html", "class_system_1_1_net_1_1_http_1_1_headers_1_1_authentication_header_value" ],
    [ "CacheControlHeaderValue", "class_system_1_1_net_1_1_http_1_1_headers_1_1_cache_control_header_value.html", "class_system_1_1_net_1_1_http_1_1_headers_1_1_cache_control_header_value" ],
    [ "ContentDispositionHeaderValue", "class_system_1_1_net_1_1_http_1_1_headers_1_1_content_disposition_header_value.html", "class_system_1_1_net_1_1_http_1_1_headers_1_1_content_disposition_header_value" ],
    [ "ContentRangeHeaderValue", "class_system_1_1_net_1_1_http_1_1_headers_1_1_content_range_header_value.html", "class_system_1_1_net_1_1_http_1_1_headers_1_1_content_range_header_value" ],
    [ "EntityTagHeaderValue", "class_system_1_1_net_1_1_http_1_1_headers_1_1_entity_tag_header_value.html", "class_system_1_1_net_1_1_http_1_1_headers_1_1_entity_tag_header_value" ],
    [ "HttpContentHeaders", "class_system_1_1_net_1_1_http_1_1_headers_1_1_http_content_headers.html", "class_system_1_1_net_1_1_http_1_1_headers_1_1_http_content_headers" ],
    [ "HttpHeaders", "class_system_1_1_net_1_1_http_1_1_headers_1_1_http_headers.html", "class_system_1_1_net_1_1_http_1_1_headers_1_1_http_headers" ],
    [ "HttpHeaderValueCollection", "class_system_1_1_net_1_1_http_1_1_headers_1_1_http_header_value_collection.html", "class_system_1_1_net_1_1_http_1_1_headers_1_1_http_header_value_collection" ],
    [ "HttpHeaderValueCollection< System::String >", "class_system_1_1_net_1_1_http_1_1_headers_1_1_http_header_value_collection_3_01_system_1_1_string_01_4.html", "class_system_1_1_net_1_1_http_1_1_headers_1_1_http_header_value_collection_3_01_system_1_1_string_01_4" ],
    [ "HttpRequestHeaders", "class_system_1_1_net_1_1_http_1_1_headers_1_1_http_request_headers.html", "class_system_1_1_net_1_1_http_1_1_headers_1_1_http_request_headers" ],
    [ "HttpResponseHeaders", "class_system_1_1_net_1_1_http_1_1_headers_1_1_http_response_headers.html", "class_system_1_1_net_1_1_http_1_1_headers_1_1_http_response_headers" ],
    [ "MediaTypeHeaderValue", "class_system_1_1_net_1_1_http_1_1_headers_1_1_media_type_header_value.html", "class_system_1_1_net_1_1_http_1_1_headers_1_1_media_type_header_value" ],
    [ "MediaTypeWithQualityHeaderValue", "class_system_1_1_net_1_1_http_1_1_headers_1_1_media_type_with_quality_header_value.html", "class_system_1_1_net_1_1_http_1_1_headers_1_1_media_type_with_quality_header_value" ],
    [ "NameValueHeaderValue", "class_system_1_1_net_1_1_http_1_1_headers_1_1_name_value_header_value.html", "class_system_1_1_net_1_1_http_1_1_headers_1_1_name_value_header_value" ],
    [ "NameValueWithParametersHeaderValue", "class_system_1_1_net_1_1_http_1_1_headers_1_1_name_value_with_parameters_header_value.html", "class_system_1_1_net_1_1_http_1_1_headers_1_1_name_value_with_parameters_header_value" ],
    [ "ObjectCollection", "class_system_1_1_net_1_1_http_1_1_headers_1_1_object_collection.html", "class_system_1_1_net_1_1_http_1_1_headers_1_1_object_collection" ],
    [ "ProductHeaderValue", "class_system_1_1_net_1_1_http_1_1_headers_1_1_product_header_value.html", "class_system_1_1_net_1_1_http_1_1_headers_1_1_product_header_value" ],
    [ "ProductInfoHeaderValue", "class_system_1_1_net_1_1_http_1_1_headers_1_1_product_info_header_value.html", "class_system_1_1_net_1_1_http_1_1_headers_1_1_product_info_header_value" ],
    [ "RangeConditionHeaderValue", "class_system_1_1_net_1_1_http_1_1_headers_1_1_range_condition_header_value.html", "class_system_1_1_net_1_1_http_1_1_headers_1_1_range_condition_header_value" ],
    [ "RangeHeaderValue", "class_system_1_1_net_1_1_http_1_1_headers_1_1_range_header_value.html", "class_system_1_1_net_1_1_http_1_1_headers_1_1_range_header_value" ],
    [ "RangeItemHeaderValue", "class_system_1_1_net_1_1_http_1_1_headers_1_1_range_item_header_value.html", "class_system_1_1_net_1_1_http_1_1_headers_1_1_range_item_header_value" ],
    [ "RetryConditionHeaderValue", "class_system_1_1_net_1_1_http_1_1_headers_1_1_retry_condition_header_value.html", "class_system_1_1_net_1_1_http_1_1_headers_1_1_retry_condition_header_value" ],
    [ "StringWithQualityHeaderValue", "class_system_1_1_net_1_1_http_1_1_headers_1_1_string_with_quality_header_value.html", "class_system_1_1_net_1_1_http_1_1_headers_1_1_string_with_quality_header_value" ],
    [ "TransferCodingHeaderValue", "class_system_1_1_net_1_1_http_1_1_headers_1_1_transfer_coding_header_value.html", "class_system_1_1_net_1_1_http_1_1_headers_1_1_transfer_coding_header_value" ],
    [ "TransferCodingWithQualityHeaderValue", "class_system_1_1_net_1_1_http_1_1_headers_1_1_transfer_coding_with_quality_header_value.html", "class_system_1_1_net_1_1_http_1_1_headers_1_1_transfer_coding_with_quality_header_value" ],
    [ "ViaHeaderValue", "class_system_1_1_net_1_1_http_1_1_headers_1_1_via_header_value.html", "class_system_1_1_net_1_1_http_1_1_headers_1_1_via_header_value" ],
    [ "WarningHeaderValue", "class_system_1_1_net_1_1_http_1_1_headers_1_1_warning_header_value.html", "class_system_1_1_net_1_1_http_1_1_headers_1_1_warning_header_value" ]
];