var namespace_aspose_1_1_font =
[
    [ "Cff", "namespace_aspose_1_1_font_1_1_cff.html", "namespace_aspose_1_1_font_1_1_cff" ],
    [ "Glyphs", "namespace_aspose_1_1_font_1_1_glyphs.html", "namespace_aspose_1_1_font_1_1_glyphs" ],
    [ "Otl", "namespace_aspose_1_1_font_1_1_otl.html", null ],
    [ "Renderers", "namespace_aspose_1_1_font_1_1_renderers.html", "namespace_aspose_1_1_font_1_1_renderers" ],
    [ "Rendering", "namespace_aspose_1_1_font_1_1_rendering.html", "namespace_aspose_1_1_font_1_1_rendering" ],
    [ "RenderingPath", "namespace_aspose_1_1_font_1_1_rendering_path.html", "namespace_aspose_1_1_font_1_1_rendering_path" ],
    [ "Sources", "namespace_aspose_1_1_font_1_1_sources.html", "namespace_aspose_1_1_font_1_1_sources" ],
    [ "Tests", "namespace_aspose_1_1_font_1_1_tests.html", null ],
    [ "Ttf", "namespace_aspose_1_1_font_1_1_ttf.html", "namespace_aspose_1_1_font_1_1_ttf" ],
    [ "TtfCMapFormats", "namespace_aspose_1_1_font_1_1_ttf_c_map_formats.html", "namespace_aspose_1_1_font_1_1_ttf_c_map_formats" ],
    [ "TtfHelpers", "namespace_aspose_1_1_font_1_1_ttf_helpers.html", "namespace_aspose_1_1_font_1_1_ttf_helpers" ],
    [ "TtfTables", "namespace_aspose_1_1_font_1_1_ttf_tables.html", "namespace_aspose_1_1_font_1_1_ttf_tables" ],
    [ "Type1", "namespace_aspose_1_1_font_1_1_type1.html", "namespace_aspose_1_1_font_1_1_type1" ],
    [ "AssemblyConstants", "class_aspose_1_1_font_1_1_assembly_constants.html", "class_aspose_1_1_font_1_1_assembly_constants" ],
    [ "BuildVersionInfo", "class_aspose_1_1_font_1_1_build_version_info.html", "class_aspose_1_1_font_1_1_build_version_info" ],
    [ "Font", "class_aspose_1_1_font_1_1_font.html", "class_aspose_1_1_font_1_1_font" ],
    [ "FontBBox", "class_aspose_1_1_font_1_1_font_b_box.html", "class_aspose_1_1_font_1_1_font_b_box" ],
    [ "FontEnvironment", "class_aspose_1_1_font_1_1_font_environment.html", "class_aspose_1_1_font_1_1_font_environment" ],
    [ "FontMetrics", "class_aspose_1_1_font_1_1_font_metrics.html", "class_aspose_1_1_font_1_1_font_metrics" ],
    [ "IEncodingParameters", "class_aspose_1_1_font_1_1_i_encoding_parameters.html", null ],
    [ "IFont", "class_aspose_1_1_font_1_1_i_font.html", "class_aspose_1_1_font_1_1_i_font" ],
    [ "IFontEncoding", "class_aspose_1_1_font_1_1_i_font_encoding.html", "class_aspose_1_1_font_1_1_i_font_encoding" ],
    [ "IFontMetrics", "class_aspose_1_1_font_1_1_i_font_metrics.html", "class_aspose_1_1_font_1_1_i_font_metrics" ],
    [ "IFontSaver", "class_aspose_1_1_font_1_1_i_font_saver.html", "class_aspose_1_1_font_1_1_i_font_saver" ],
    [ "IFontSource", "class_aspose_1_1_font_1_1_i_font_source.html", "class_aspose_1_1_font_1_1_i_font_source" ],
    [ "ISupportsNameAddressing", "class_aspose_1_1_font_1_1_i_supports_name_addressing.html", "class_aspose_1_1_font_1_1_i_supports_name_addressing" ],
    [ "License", "class_aspose_1_1_font_1_1_license.html", "class_aspose_1_1_font_1_1_license" ],
    [ "MultiLanguageString", "class_aspose_1_1_font_1_1_multi_language_string.html", "class_aspose_1_1_font_1_1_multi_language_string" ],
    [ "NameToCodeMap", "class_aspose_1_1_font_1_1_name_to_code_map.html", "class_aspose_1_1_font_1_1_name_to_code_map" ],
    [ "TransformationMatrix", "class_aspose_1_1_font_1_1_transformation_matrix.html", "class_aspose_1_1_font_1_1_transformation_matrix" ]
];